#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3papi

MANFILES=				\
	papiAttributeListAddValue.3papi	\
	papiJobSubmit.3papi		\
	papiLibrarySupportedCall.3papi	\
	papiPrintersList.3papi		\
	papiServiceCreate.3papi		\
	papiStatusString.3papi

MANSO=					\
	papiAttributeListAddBoolean.3papi\
	papiAttributeListAddCollection.3papi\
	papiAttributeListAddDatetime.3papi\
	papiAttributeListAddInteger.3papi\
	papiAttributeListAddMetadata.3papi\
	papiAttributeListAddRange.3papi	\
	papiAttributeListAddResolution.3papi\
	papiAttributeListAddString.3papi\
	papiAttributeListDelete.3papi	\
	papiAttributeListFind.3papi	\
	papiAttributeListFree.3papi	\
	papiAttributeListFromString.3papi\
	papiAttributeListGetBoolean.3papi\
	papiAttributeListGetCollection.3papi\
	papiAttributeListGetDatetime.3papi\
	papiAttributeListGetInteger.3papi\
	papiAttributeListGetMetadata.3papi\
	papiAttributeListGetNext.3papi	\
	papiAttributeListGetRange.3papi	\
	papiAttributeListGetResolution.3papi\
	papiAttributeListGetString.3papi\
	papiAttributeListGetValue.3papi	\
	papiAttributeListToString.3papi	\
	papiJobCancel.3papi		\
	papiJobFree.3papi		\
	papiJobGetAttributeList.3papi	\
	papiJobGetId.3papi		\
	papiJobGetJobTicket.3papi	\
	papiJobGetPrinterName.3papi	\
	papiJobHold.3papi		\
	papiJobListFree.3papi		\
	papiJobModify.3papi		\
	papiJobMove.3papi		\
	papiJobPromote.3papi		\
	papiJobQuery.3papi		\
	papiJobRelease.3papi		\
	papiJobRestart.3papi		\
	papiJobStreamClose.3papi	\
	papiJobStreamOpen.3papi		\
	papiJobStreamWrite.3papi	\
	papiJobSubmitByReference.3papi	\
	papiJobValidate.3papi		\
	papiLibrarySupportedCalls.3papi	\
	papiPrinterAdd.3papi		\
	papiPrinterDisable.3papi	\
	papiPrinterEnable.3papi		\
	papiPrinterFree.3papi		\
	papiPrinterGetAttributeList.3papi\
	papiPrinterListFree.3papi	\
	papiPrinterListJobs.3papi	\
	papiPrinterModify.3papi		\
	papiPrinterPause.3papi		\
	papiPrinterPurgeJobs.3papi	\
	papiPrinterQuery.3papi		\
	papiPrinterRemove.3papi		\
	papiPrinterResume.3papi		\
	papiServiceDestroy.3papi	\
	papiServiceGetAppData.3papi	\
	papiServiceGetAttributeList.3papi\
	papiServiceGetEncryption.3papi	\
	papiServiceGetPassword.3papi	\
	papiServiceGetServiceName.3papi	\
	papiServiceGetStatusMessage.3papi\
	papiServiceGetUserName.3papi	\
	papiServiceSetAppData.3papi	\
	papiServiceSetAuthCB.3papi	\
	papiServiceSetEncryption.3papi	\
	papiServiceSetPassword.3papi	\
	papiServiceSetUserName.3papi

papiAttributeListAddBoolean.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListAddCollection.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListAddDatetime.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListAddInteger.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListAddMetadata.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListAddRange.3papi		:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListAddResolution.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListAddString.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListDelete.3papi		:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListFind.3papi		:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListFree.3papi		:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListFromString.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListGetBoolean.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListGetCollection.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListGetDatetime.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListGetInteger.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListGetMetadata.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListGetNext.3papi		:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListGetRange.3papi		:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListGetResolution.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListGetString.3papi	:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListGetValue.3papi		:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiAttributeListToString.3papi		:= SOFILE = man3papi/papiAttributeListAddValue.3papi
papiJobCancel.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobFree.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobGetAttributeList.3papi		:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobGetId.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobGetJobTicket.3papi		:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobGetPrinterName.3papi		:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobHold.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobListFree.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobModify.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobMove.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobPromote.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobQuery.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobRelease.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobRestart.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobStreamClose.3papi		:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobStreamOpen.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobStreamWrite.3papi		:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobSubmitByReference.3papi		:= SOFILE = man3papi/papiJobSubmit.3papi
papiJobValidate.3papi			:= SOFILE = man3papi/papiJobSubmit.3papi
papiLibrarySupportedCalls.3papi		:= SOFILE = man3papi/papiLibrarySupportedCall.3papi
papiPrinterAdd.3papi			:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterDisable.3papi		:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterEnable.3papi			:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterFree.3papi			:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterGetAttributeList.3papi	:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterListFree.3papi		:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterListJobs.3papi		:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterModify.3papi			:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterPause.3papi			:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterPurgeJobs.3papi		:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterQuery.3papi			:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterRemove.3papi			:= SOFILE = man3papi/papiPrintersList.3papi
papiPrinterResume.3papi			:= SOFILE = man3papi/papiPrintersList.3papi
papiServiceDestroy.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceGetAppData.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceGetAttributeList.3papi	:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceGetEncryption.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceGetPassword.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceGetServiceName.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceGetStatusMessage.3papi	:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceGetUserName.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceSetAppData.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceSetAuthCB.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceSetEncryption.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceSetPassword.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi
papiServiceSetUserName.3papi		:= SOFILE = man3papi/papiServiceCreate.3papi

include ../Makefile.man

install: $(ROOTMANFILES)
