#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3gss

MANFILES=				\
	gss_accept_sec_context.3gss	\
	gss_acquire_cred.3gss		\
	gss_add_cred.3gss		\
	gss_add_oid_set_member.3gss	\
	gss_canonicalize_name.3gss	\
	gss_compare_name.3gss		\
	gss_context_time.3gss		\
	gss_create_empty_oid_set.3gss	\
	gss_delete_sec_context.3gss	\
	gss_display_name.3gss		\
	gss_display_status.3gss		\
	gss_duplicate_name.3gss		\
	gss_export_name.3gss		\
	gss_export_sec_context.3gss	\
	gss_get_mic.3gss		\
	gss_import_name.3gss		\
	gss_import_sec_context.3gss	\
	gss_indicate_mechs.3gss		\
	gss_init_sec_context.3gss	\
	gss_inquire_context.3gss	\
	gss_inquire_cred_by_mech.3gss	\
	gss_inquire_cred.3gss		\
	gss_inquire_mechs_for_name.3gss	\
	gss_inquire_names_for_mech.3gss	\
	gss_oid_to_str.3gss		\
	gss_process_context_token.3gss	\
	gss_release_buffer.3gss		\
	gss_release_cred.3gss		\
	gss_release_name.3gss		\
	gss_release_oid_set.3gss	\
	gss_release_oid.3gss		\
	gss_store_cred.3gss		\
	gss_str_to_oid.3gss		\
	gss_test_oid_set_member.3gss	\
	gss_unwrap.3gss			\
	gss_verify_mic.3gss		\
	gss_wrap_size_limit.3gss	\
	gss_wrap.3gss

MANSO=					\

include ../Makefile.man

install: $(ROOTMANFILES)
