#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3bsm

MANFILES=				\
	au_open.3bsm			\
	au_preselect.3bsm		\
	au_to.3bsm			\
	au_user_mask.3bsm		\
	getacinfo.3bsm			\
	getauclassent.3bsm		\
	getauditflags.3bsm		\
	getauevent.3bsm			\
	getauusernam.3bsm		\
	getddent.3bsm			\
	getfauditflags.3bsm

MANSO=					\
	au_close.3bsm			\
	au_to_arg.3bsm			\
	au_to_arg32.3bsm		\
	au_to_arg64.3bsm		\
	au_to_attr.3bsm			\
	au_to_cmd.3bsm			\
	au_to_data.3bsm			\
	au_to_groups.3bsm		\
	au_to_in_addr.3bsm		\
	au_to_ipc.3bsm			\
	au_to_iport.3bsm		\
	au_to_me.3bsm			\
	au_to_newgroups.3bsm		\
	au_to_opaque.3bsm		\
	au_to_path.3bsm			\
	au_to_process_ex.3bsm		\
	au_to_process.3bsm		\
	au_to_return.3bsm		\
	au_to_return32.3bsm		\
	au_to_return64.3bsm		\
	au_to_socket.3bsm		\
	au_to_subject_ex.3bsm		\
	au_to_subject.3bsm		\
	au_to_text.3bsm			\
	au_write.3bsm			\
	endac.3bsm			\
	endauclass.3bsm			\
	endauevent.3bsm			\
	endauuser.3bsm			\
	endddent.3bsm			\
	getacdir.3bsm			\
	getacflg.3bsm			\
	getacmin.3bsm			\
	getacna.3bsm			\
	getauclassent_r.3bsm		\
	getauclassnam_r.3bsm		\
	getauclassnam.3bsm		\
	getauditflagsbin.3bsm		\
	getauditflagschar.3bsm		\
	getauevent_r.3bsm		\
	getauevnam_r.3bsm		\
	getauevnam.3bsm			\
	getauevnonam.3bsm		\
	getauevnum_r.3bsm		\
	getauevnum.3bsm			\
	getauuserent_r.3bsm		\
	getauuserent.3bsm		\
	getauusernam_r.3bsm		\
	getddnam.3bsm			\
	setac.3bsm			\
	setauclass.3bsm			\
	setauevent.3bsm			\
	setauuser.3bsm			\
	setddent.3bsm			\
	setddfile.3bsm

au_close.3bsm		:= SOFILE = man3bsm/au_open.3bsm
au_to_arg.3bsm		:= SOFILE = man3bsm/au_to.3bsm
au_to_arg32.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_arg64.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_attr.3bsm		:= SOFILE = man3bsm/au_to.3bsm
au_to_cmd.3bsm		:= SOFILE = man3bsm/au_to.3bsm
au_to_data.3bsm		:= SOFILE = man3bsm/au_to.3bsm
au_to_groups.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_in_addr.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_ipc.3bsm		:= SOFILE = man3bsm/au_to.3bsm
au_to_iport.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_me.3bsm		:= SOFILE = man3bsm/au_to.3bsm
au_to_newgroups.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_opaque.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_path.3bsm		:= SOFILE = man3bsm/au_to.3bsm
au_to_process_ex.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_process.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_return.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_return32.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_return64.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_socket.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_subject_ex.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_subject.3bsm	:= SOFILE = man3bsm/au_to.3bsm
au_to_text.3bsm		:= SOFILE = man3bsm/au_to.3bsm
au_write.3bsm		:= SOFILE = man3bsm/au_open.3bsm
endac.3bsm		:= SOFILE = man3bsm/getacinfo.3bsm
endauclass.3bsm		:= SOFILE = man3bsm/getauclassent.3bsm
endauevent.3bsm		:= SOFILE = man3bsm/getauevent.3bsm
endauuser.3bsm		:= SOFILE = man3bsm/getauusernam.3bsm
endddent.3bsm		:= SOFILE = man3bsm/getddent.3bsm
getacdir.3bsm		:= SOFILE = man3bsm/getacinfo.3bsm
getacflg.3bsm		:= SOFILE = man3bsm/getacinfo.3bsm
getacmin.3bsm		:= SOFILE = man3bsm/getacinfo.3bsm
getacna.3bsm		:= SOFILE = man3bsm/getacinfo.3bsm
getauclassent_r.3bsm	:= SOFILE = man3bsm/getauclassent.3bsm
getauclassnam_r.3bsm	:= SOFILE = man3bsm/getauclassent.3bsm
getauclassnam.3bsm	:= SOFILE = man3bsm/getauclassent.3bsm
getauditflagsbin.3bsm	:= SOFILE = man3bsm/getauditflags.3bsm
getauditflagschar.3bsm	:= SOFILE = man3bsm/getauditflags.3bsm
getauevent_r.3bsm	:= SOFILE = man3bsm/getauevent.3bsm
getauevnam_r.3bsm	:= SOFILE = man3bsm/getauevent.3bsm
getauevnam.3bsm		:= SOFILE = man3bsm/getauevent.3bsm
getauevnonam.3bsm	:= SOFILE = man3bsm/getauevent.3bsm
getauevnum_r.3bsm	:= SOFILE = man3bsm/getauevent.3bsm
getauevnum.3bsm		:= SOFILE = man3bsm/getauevent.3bsm
getauuserent_r.3bsm	:= SOFILE = man3bsm/getauusernam.3bsm
getauuserent.3bsm	:= SOFILE = man3bsm/getauusernam.3bsm
getauusernam_r.3bsm	:= SOFILE = man3bsm/getauusernam.3bsm
getddnam.3bsm		:= SOFILE = man3bsm/getddent.3bsm
setac.3bsm		:= SOFILE = man3bsm/getacinfo.3bsm
setauclass.3bsm		:= SOFILE = man3bsm/getauclassent.3bsm
setauevent.3bsm		:= SOFILE = man3bsm/getauevent.3bsm
setauuser.3bsm		:= SOFILE = man3bsm/getauusernam.3bsm
setddent.3bsm		:= SOFILE = man3bsm/getddent.3bsm
setddfile.3bsm		:= SOFILE = man3bsm/getddent.3bsm

include ../Makefile.man

install: $(ROOTMANFILES)
