#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	7i

MANFILES=				\
	agpgart_io.7i			\
	audio.7i			\
	cdio.7i				\
	dkio.7i				\
	dsp.7i				\
	fbio.7i				\
	fdio.7i				\
	hdio.7i				\
	iec61883.7i			\
	ipnat.7i			\
	isdnio.7i			\
	mhd.7i				\
	mixer.7i			\
	mtio.7i				\
	prnio.7i			\
	quotactl.7i			\
	sesio.7i			\
	sockio.7i			\
	streamio.7i			\
	termio.7i			\
	termiox.7i			\
	uscsi.7i			\
	visual_io.7i			\
	vt.7i

MANSO=					\

include ../Makefile.man

install: $(ROOTMANFILES)
