#!/bin/sh
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2006-2019 Jörg Schilling.  All rights reserved.
#

owd=`pwd`
arch=`uname -p`
if [ "$PKGARCHIVE" = "" ]; then
	PKGARCHIVE=../../../packages/$arch/nightly/
fi
INSROOT=""
insroot="$PKGARCHIVE/ROOT"
dorm=FALSE
pkglist=pkglist
found_pkglist=FALSE


usage() {
	echo "Usage: pkginstall [-rm] [-R root] [-pd dir] [pkglist]"
	echo "Options:"
	echo "	-rm	remove everything in install root directory before installing"
	echo "	-R root	Specify different install root directory"
	echo "	-pd dir	Specify different package source directory"
	echo
	echo "By default, package names are taken from the file './pkglist'"
	echo "Default install root directory is '$insroot'"
}

while [ $# -gt 0 ]; do
	case "$1" in
	-help)
		usage
		exit 0
		;;

	-rm)
		dorm=TRUE
		shift
		;;

	-R)
		INSROOT=$2
		shift 2 || exit
		;;

	-pd)
		PKGARCHIVE=$2
		shift 2 || exit
		insroot="$PKGARCHIVE/ROOT"
		;;

	-*)
		echo "Illegal option $1"
		usage
		exit 0
		;;

	*)
		if [ $found_pkglist = TRUE ]; then
			echo "Too many file type args."
			usage
			exit 1
		fi
		
		found_pkglist=TRUE
		pkglist=$1
		#echo "arg:  $1"
		#echo "args: $@"
		shift
		;;
	esac
done
if [ -r "$pkglist" ]; then
	echo "$pkglist" | grep "^/" > /dev/null
	if [ $? -ne 0 ]; then
		pkglist="$owd/$pkglist"
	fi
fi

INSROOT=${INSROOT:-$insroot}
echo "$INSROOT" | grep "^/" > /dev/null
if [ $? -ne 0 ]; then
	INSROOT="$owd/$INSROOT"
fi

#echo dorm $dorm
#echo found_pkglist $found_pkglist
#echo pklist $pkglist
#echo INSROOT "$INSROOT"

cd $PKGARCHIVE || exit
cwd=`pwd`

mkdir -p "$INSROOT"
chown root:root "$INSROOT"
chmod g+s "$INSROOT"
if [ $dorm = TRUE ]; then
	(cd "$INSROOT" && rm -rf *)
fi

#
# Canonicalize "$INSROOT"
#
cd "$INSROOT" || exit
INSROOT=`pwd`

#
# Back to the package directory...
#
cd "$cwd" || edit

pkgadd -a $owd/admin-fullauto  -R "$INSROOT" -d . ` cat $pkglist `
pkgadm sync -R "$INSROOT" -q
