#!/bin/sh
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2006-2011 Jörg Schilling.  All rights reserved.
#

owd=`pwd`
arch=`uname -p`
if [ "$PKGARCHIVE" = "" ]; then
	PKGARCHIVE=../../../packages/$arch/nightly/
fi
dorm=FALSE
pkglist=pkglist
found_pkglist=FALSE


usage() {
	echo "Usage: pkginstall [-rm] [pkglist]"
	echo "Options:"
	echo "	-rm	remove everything in $PKGARCHIVE/ROOT before installing"
	echo
	echo "By default, package names are taken from the file 'pkglist'"
}

while [ $# -gt 0 ]; do
	case "$1" in
	-help)
		usage
		exit 0
		;;

	-rm)
		dorm=TRUE
		shift
		;;

	-*)
		echo "Illegal option $1"
		usage
		exit 0
		;;

	*)
		if [ $found_pkglist = TRUE ]; then
			echo "Too many file type args."
			usage
			exit 1
		fi
		
		found_fileprefix=TRUE
		pkglist=$1
		#echo "arg:  $1"
		#echo "args: $@"
		shift
		;;
	esac
done
if [ -r "$pkglist" ]; then
	echo "$pkglist" | grep "^/" > /dev/null
	if [ $? -ne 0 ]; then
		pkglist="$owd/$pkglist"
	fi
fi
#echo dorm $dorm
#echo found_pkglist $found_pkglist
#echo pklist $pkglist

cd $PKGARCHIVE || exit
cwd=`pwd`

mkdir -p ROOT
chown root:root ROOT
chmod g+s ROOT
if [ $dorm = TRUE ]; then
	(cd ROOT && rm -rf *)
fi

pkgadd -a $owd/admin-fullauto  -R $cwd/ROOT -d . ` cat $pkglist `
