#!/bin/sh
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2006-2011 Jörg Schilling.  All rights reserved.
#
LC_ALL=C; export LC_ALL

arch=`uname -p`

if [ "$PKGARCHIVE" = "" ]; then
	PKGARCHIVE=../../../packages/$arch/nightly/
fi

list_depends()
{
	for i in *; do
		if [ ! -f $i/pkginfo ]; then
			continue
		fi
		pkgname=`sed -n 's/^PKG=//p' $i/pkginfo`
		echo $pkgname $pkgname
		if [ ! -f $i/install/depend ]; then
			continue
		fi
		depends=`grep '^P[ 	]' $i/install/depend | awk '{ print $2 }'`
		for x in $depends; do
			echo $pkgname $x
		done
	done
}

cd $PKGARCHIVE || exit 1

list_depends | tsort | tail -r | \
( while read line; do
	fnames=`eval echo /dev/null $line*/pkginfo`
	grep "^PKG=$line"'$' $fnames | sed 's,/.*,,'
done) 2> /dev/null
