#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3resolv

MANFILES=				\
	resolver.3resolv

MANSO=					\
	dn_comp.3resolv			\
	dn_expand.3resolv		\
	fp_resstat.3resolv		\
	herror.3resolv			\
	hstrerror.3resolv		\
	res_getservers.3resolv		\
	res_hostalias.3resolv		\
	res_init.3resolv		\
	res_mkquery.3resolv		\
	res_nclose.3resolv		\
	res_ndestroy.3resolv		\
	res_ninit.3resolv		\
	res_nmkquery.3resolv		\
	res_nquery.3resolv		\
	res_nquerydomain.3resolv	\
	res_nsearch.3resolv		\
	res_nsend.3resolv		\
	res_nsendsigned.3resolv		\
	res_query.3resolv		\
	res_search.3resolv		\
	res_send.3resolv		\
	res_setservers.3resolv

dn_comp.3resolv				:= SOFILE = man3resolv/resolver.3resolv
dn_expand.3resolv			:= SOFILE = man3resolv/resolver.3resolv
fp_resstat.3resolv			:= SOFILE = man3resolv/resolver.3resolv
herror.3resolv				:= SOFILE = man3resolv/resolver.3resolv
hstrerror.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_getservers.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_hostalias.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_init.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_mkquery.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_nclose.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_ndestroy.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_ninit.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_nmkquery.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_nquery.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_nquerydomain.3resolv		:= SOFILE = man3resolv/resolver.3resolv
res_nsearch.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_nsend.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_nsendsigned.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_query.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_search.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_send.3resolv			:= SOFILE = man3resolv/resolver.3resolv
res_setservers.3resolv			:= SOFILE = man3resolv/resolver.3resolv

include ../Makefile.man

install: $(ROOTMANFILES)
