'\" te
.\" Copyright 1989 AT&T
.\" Copyright (c) 2009 Sun Microsystems, Inc. All Rights Reserved.
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH as 1 "24 Aug 2009" "SunOS 5.11" "User Commands"
.SH NAME
as \- assembler
.SH SYNOPSIS
.SS "SPARC"
.LP
.nf
\fBas\fR [\fB-b\fR] [\fB-i\fR] [\fB-K\fR {pic,PIC}] [\fB-L\fR] [\fB-m\fR] [\fB-n\fR] [\fB-o\fR \fIoutfile\fR]
     [\fB-P\fR] [\fB-D\fIname\fR] [\fB-D\fIname=def\fR] [\fB-I\fIpath\fR] [\fB-U\fIname\fR].\|.\|. [\fB-q\fR]
     [\fB-Q\fIy\fR | \fIn\fR] [\fB-s\fR] [\fB-S\fR [\fIa\fR | \fIb\fR | \fIc\fR | \fIl\fR | \fIA\fR | \fIB\fR | \fIC\fR | \fIL\fR]]
     [\fB-T\fR] [\fB-V\fR]
     [\fB-xarch=v7\fR | \fB-xarch=v8\fR | \fB-xarch=v8a\fR | \fB-xarch=v8plus\fR |
      \fB-xarch=v8plusa\fR | \fB-xarch=v8plusb\fR | \fB-xarch=v8plusd\fR |
      \fB-xarch=v8plusv\fR | \fB-xarch=v9\fR | \fB-xarch=v9a\fR |
      \fB-xarch=v9b\fR | \fB-xarch=v9d\fR | \fB-xarch=v9v\fR]
     [\fB-xF\fR] [\fB-Y\fR \fIdirname\fR] \fIfilename\fR.\|.\|.
.fi

.SS "x86"
.LP
.nf
\fBas\fR [\fB-b\fR] [\fB-i\fR] [\fB-K\fR PIC] [\fB-L\fR] [\fB-m\fR] [\fB-n\fR] [\fB-o\fR \fIoutfile\fR] [\fB-P\fR]
     [\fB-D\fIname\fR] [\fB-D\fIname=def\fR] [\fB-I\fIpath\fR] [\fB-U\fIname\fR].\|.\|. [\fB-Q\fIy\fR | \fIn\fR]
     [\fB-s\fR] [\fB-S\fR [\fIa\fR | \fIb\fR | \fIc\fR | \fIl\fR | \fIA\fR | \fIB\fR | \fIC\fR | \fIL\fR]] [\fB-T\fR] [\fB-V\fR]
     [\fB-xarch\fR=generic64 | \fB-xarch\fR=amd64] [\fB-Y\fR \fIdirname\fR]
     [\fB-xmodel\fR= [ SMALL | KERNEL ]] \fIfilename\fR.\|.\|.
.fi

.SH DESCRIPTION
.sp
.LP
The
.B as
command creates object files from assembly language source files.
.SH OPTIONS
.SS "Common Options"
.sp
.LP
The following flags are common to both SPARC and x86. They can be specified in
any order:
.sp
.ne 2
.mk
.na
.B -b
.ad
.RS 23n
.rt
Generates extra symbol table information.
.RE

.sp
.ne 2
.mk
.na
.B -i
.ad
.RS 23n
.rt
Ignore line number information from preprocessor.
.RE

.sp
.ne 2
.mk
.na
\fB-K pic\fR | \fBPIC\fR
.ad
.RS 23n
.rt
Generates position-independent code.
.RE

.sp
.ne 2
.mk
.na
.B -L
.ad
.RS 23n
.rt
Saves all symbols, including temporary labels that are normally discarded to
save space, in the ELF symbol table.
.RE

.sp
.ne 2
.mk
.na
.B -m
.ad
.RS 23n
.rt
Runs the
.BR m4 (1)
macro processor on the input to the assembler.
.RE

.sp
.ne 2
.mk
.na
.B -n
.ad
.RS 23n
.rt
Suppresses all the warnings while assembling.
.RE

.sp
.ne 2
.mk
.na
\fB-o\fR \fIoutfile\fR
.ad
.RS 23n
.rt
Puts the output of the assembly in
.IR outfile .
By default, the output file
name is formed by removing the \fB\&.s\fR suffix, if there is one, from the input
file name and appending a \fB\&.o\fR suffix.
.RE

.sp
.ne 2
.mk
.na
.B -P
.ad
.RS 23n
.rt
Runs
.BR cpp (1),
the C preprocessor, on the files being assembled. The
preprocessor is run separately on each input file, not on their concatenation.
The preprocessor output is passed to the assembler.
.RE

.sp
.ne 2
.mk
.na
\fB-D\fIname\fR
.ad
.br
.na
\fB-D\fIname=def\fR
.ad
.RS 23n
.rt
When the
.B -P
option is in effect, these options are passed to the
.BR cpp (1)
preprocessor without interpretation by the
.B as
command;
otherwise, they are ignored.
.RE

.sp
.ne 2
.mk
.na
\fB-I\fIpath\fR
.ad
.RS 23n
.rt
When the
.B -P
option is in effect, this option is passed to the \fBcpp\fR(1)
preprocessor without interpretation by the
.B as
command; otherwise, it is
ignored.
.RE

.sp
.ne 2
.mk
.na
\fB-U\fIname\fR
.ad
.RS 23n
.rt
When the
.B -P
option is in effect, this option is passed to the \fBcpp\fR(1)
preprocessor without interpretation by the
.B as
command; otherwise, it is
ignored.
.RE

.sp
.ne 2
.mk
.na
\fB-Q\fIy\fR | \fIn\fR
.ad
.RS 23n
.rt
If
.I y
is specified, this option produces the assembler version information
in the comment section of the output object file. If
.I n
is specified, the
information is suppressed.
.RE

.sp
.ne 2
.mk
.na
.B -s
.ad
.RS 23n
.rt
Places all stabs in the \fB\&.stabs\fR section. By default, stabs are placed in
\fBstabs.excl\fR sections, which are stripped out by the static linker,
.BR ld (1),
during final execution. When the
.B -s
option is used, stabs
remain in the final executable because \fB\&.stab\fR sections are not stripped by
the static linker.
.RE

.sp
.ne 2
.mk
.na
\fB-S\fR[\fIa\fR|\fIb\fR|\fIc\fR|\fIl\fR|\fIA\fR|\fIB\fR|\fIC\fR|\fIL\fR]\fR
.ad
.RS 23n
.rt
Produces a disassembly of the emitted code to the standard output. Adding each
of the following characters to the
.B -S
option produces:
.sp
.ne 2
.mk
.na
.I a
.ad
.RS 5n
.rt
disassembling with address
.RE

.sp
.ne 2
.mk
.na
.I b
.ad
.RS 5n
.rt
disassembling with ".bof"
.RE

.sp
.ne 2
.mk
.na
.I c
.ad
.RS 5n
.rt
disassembling with comments
.RE

.sp
.ne 2
.mk
.na
.I l
.ad
.RS 5n
.rt
disassembling with line numbers
.RE

Capital letters turn the switch off for the corresponding option.
.RE

.sp
.ne 2
.mk
.na
.B -T
.ad
.RS 23n
.rt
This is a migration option for 4.\fIx\fR assembly files to be assembled on
5.\fIx\fR systems. With this option, the symbol names in 4.\fIx\fR assembly files
are interpreted as 5.\fIx\fR symbol names.
.RE

.sp
.ne 2
.mk
.na
.B -V
.ad
.RS 23n
.rt
Writes the version number of the assembler being run on the standard error
output.
.RE

.sp
.ne 2
.mk
.na
.B -xF
.ad
.RS 23n
.rt
Allows function reordering by the Performance Analyzer. If you compile with the
\fB-xF\fR option, and then run the Performance Analyzer, you can generate a map
file that shows an optimized order for the functions. The subsequent link to
build the executable file can be directed to use that map file by using the
linker
.B -M
\fImapfile\fR option. It places each function from the executable
file into a separate section.
.RE

.sp
.ne 2
.mk
.na
\fB-Y\fR \fIdirname\fR
.ad
.RS 23n
.rt
Specify directory
.B m4
and/or \fBcm4def\fR.
.RE

.SS "Options for SPARC only"
.sp
.ne 2
.mk
.na
.B -q
.ad
.RS 18n
.rt
Performs a quick assembly. When the
.B -q
option is used, many error checks
are not performed. This option disables many error checks. Use of this option to
assemble handwritten assembly language is not recommended.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v7
.ad
.RS 18n
.rt
This option instructs the assembler to accept instructions defined in the SPARC
version 7 (V7) architecture. The resulting object code is in ELF format.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v8
.ad
.RS 18n
.rt
This option instructs the assembler to accept instructions defined in the
SPARC-V8 architecture, less the quad-precision floating-point instructions. The
resulting object code is in ELF format.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v8a
.ad
.RS 18n
.rt
This option instructs the assembler to accept instructions defined in the
SPARC-V8 architecture, less the quad-precision floating-point instructions and
less the \fIfsmuld\fR instruction. The resulting object code is in ELF format.
This is the default choice of the \fB-xarch\fB=\fIoptions\fR.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v8plus
.ad
.RS 18n
.rt
This option instructs the assembler to accept instructions defined in the
SPARC-V9 architecture, less the quad-precision floating-point instructions. The
resulting object code is in ELF format. It does not execute on a Solaris V8
system (a machine with a V8 processor). It   executes on a Solaris V8+ system.
This combination is a SPARC 64-bit processor and a 32-bit OS.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v8plusa
.ad
.RS 18n
.rt
This option instructs the assembler to accept instructions defined in the
SPARC-V9 architecture, less the quad-precision floating-point instructions, plus
the instructions in the Visual Instruction Set (VIS). The resulting object code
is in V8+ ELF format. It does not execute on a Solaris V8 system (a machine with
a V8 processor). It executes on a Solaris V8+ system
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v8plusb
.ad
.RS 18n
.rt
This option enables the assembler to accept instructions defined in the SPARC-V9
architecture, plus the instructions in the Visual Instruction Set (VIS), with
UltraSPARC-III extensions. The resulting object code is in V8+ ELF32 format.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v8plusd
.ad
.RS 18n
.rt
This option enables the assembler to accept instructions DEFIned in UltraSPARC
Architecture 2009. The resulting object code is in V8+ ELF32 format.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v8plusv
.ad
.RS 18n
.rt
This option enables the assembler to accept instructions defined in UltraSPARC
Architecture 2005, including the extensions dealing with the sun4v virtual
machine model. The resulting object code is in V8+ ELF32 format.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v9
.ad
.RS 18n
.rt
This option limits the instruction set to the SPARC-V9 architecture. The
resulting .o object files are in 64-bit ELF format and can only be linked with
other object files in the same format. The resulting executable can only be run
on a 64-bit SPARC processor running 64-bit Solaris with the 64-bit kernel.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v9a
.ad
.RS 18n
.rt
This option limits the instruction set to the SPARC-V9 architecture, adding the
Visual Instruction Set (VIS) and extensions specific to UltraSPARC processors.
The resulting .o object files are in 64-bit ELF format and can only be linked
with other object files in the same format. The resulting executable can only be
run on a 64-bit SPARC processor running 64-bit Solaris with the 64-bit kernel.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v9b
.ad
.RS 18n
.rt
This option enables the assembler to accept instructions defined in the SPARC-V9
architecture, plus the Visual Instruction Set (VIS), with UltraSPARC-III
extensions. The resulting .o object files are in ELF64 format and can only be
linked with other V9 object files in the same format. The resulting executable
can only be run on a 64-bit processor running a 64-bit Solaris operating
environment with the 64-bit kernel.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v9d
.ad
.RS 18n
.rt
This option enables the assembler to accept instructions defined in UltraSPARC
Architecture 2009. The resulting object code is in ELF64 format.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=v9v
.ad
.RS 18n
.rt
This option enables the assembler to accept instructions defined in UltraSPARC
Architecture 2005, including the extensions dealing with the sun4v virtual
machine model. The resulting object code is in ELF64 format.
.RE

.SS "Options for x86 Only"
.sp
.ne 2
.mk
.na
.B -xarch>=generic64
.ad
.RS 28n
.rt
Limits the instruction set to AMD64. The resulting object code is in 64-bit ELF
format.
.RE

.sp
.ne 2
.mk
.na
.B -xarch=amd64
.ad
.RS 28n
.rt
Limits the instruction set to AMD64. The resulting object code is in 64-bit ELF
format.
.RE

.sp
.ne 2
.mk
.na
\fB-xmodel\fR=[SMALL | KERNEL]\fR
.ad
.RS 28n
.rt
For AMD64 only, generate
.B R_X86_64_32S
relocatable type for static data
access under
.BR KERNEL .
Otherwise, generate
.B R_X86_64_32
under
.BR SMALL .
\fBSMALL\fR is the default.
.RE

.SH OPERANDS
.sp
.LP
The following operand is supported:
.sp
.ne 2
.mk
.na
\fIfilename\fR
.ad
.RS 12n
.rt
Assembly language source file
.RE

.SH ENVIRONMENT VARIABLES
.sp
.ne 2
.mk
.na
.B TMPDIR
.ad
.RS 10n
.rt
The
.B as
command normally creates temporary files in the directory
.BR /tmp .
Another directory can be specified by setting the environment
variable
.B TMPDIR
to the chosen directory. (If
.B TMPDIR
is not a valid
directory, then
.B as
uses
.BR /tmp ).
.RE

.SH FILES
.sp
.LP
By default,
.B as
creates its temporary files in
.BR /tmp .
.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i)
lw(2.75i) |lw(2.75i)
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
.TE

.SH SEE ALSO
.sp
.LP
\fBcpp\fR(1),\fBld\fR(1), \fBm4\fR(1), \fBnm\fR(1), \fBstrip\fR(1),
.BR tmpnam (3C),
.BR a.out (4),
.BR attributes (5)
.sp
.LP
\fBdbx\fR and \fBanalyzer\fR manual pages available with Sun Studio
documentation.
.SH NOTES
.sp
.LP
If the
.B -m
option, which invokes the
.BR m4 (1)
macro processor, is used,
keywords for
.B m4
cannot be used as symbols (variables, functions, labels) in
the input file, since
.B m4
cannot determine which keywords are assembler
symbols and which keywords are real
.B m4
macros.
.sp
.LP
Whenever possible, access the assembler through a compilation system interface
program.
.sp
.LP
All undefined symbols are treated as global.
