'\" te
.\" Copyright (c) 2008, Sun Microsystems, Inc. All Rights Reserved
.\" Copyright (c) 2012-2013, J. Schilling
.\" Copyright (c) 2013, Andreas Roehler
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH ctrun 1 "25 Feb 2008" "SunOS 5.11" "User Commands"
.SH NAME
ctrun \- execute command in a process contract
.SH SYNOPSIS
.LP
.nf
\fB/usr/bin/ctrun\fR [\fIoptions\fR] \fIcommand\fR [ \fIargument\fR].\|.\|.
.fi

.SH DESCRIPTION
.sp
.LP
The
.B ctrun
utility starts a command in a newly created process
contract.
.B ctrun
holds the contract and can be instructed to output or
respond to events that occur within the contract.
.sp
.LP
For additional information about process contracts, see
.BR contract (4)
and
.BR process (4).
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
.B -A
.I fmri aux
.ad
.RS 26n
.rt
Sets the process contract creator's auxiliary field.
.RE

.sp
.ne 2
.mk
.na
\fB-i\fR \fIevent\fR,[\fIevent\fR .\|.\|.]\fR
.ad
.br
.na
\fB-f\fR \fIevent\fR,[\fIevent\fR .\|.\|.]\fR
.ad
.RS 26n
.rt
Sets the informative and fatal events, respectively.
.sp
The following are valid
.IR event s:
.sp
.ne 2
.mk
.na
.B core
.ad
.RS 10n
.rt
A member process dumped core.
.sp
.B core
events are informative by default.
.RE

.sp
.ne 2
.mk
.na
.B empty
.ad
.RS 10n
.rt
The last member of the process contract exited.
.RE

.sp
.ne 2
.mk
.na
.B exit
.ad
.RS 10n
.rt
A member process exited.
.RE

.sp
.ne 2
.mk
.na
.B fork
.ad
.RS 10n
.rt
A process was added to the process contract.
.RE

.sp
.ne 2
.mk
.na
.B hwerr
.ad
.RS 10n
.rt
A member process encountered a hardware error.
.sp
.B hwerr
events are fatal by default.
.RE

.sp
.ne 2
.mk
.na
.B signal
.ad
.RS 10n
.rt
A member process received a fatal signal from a process in a different
process contract.
.RE

Only
.BR core ,
.BR hwerr ,
and
.B signal
events can be made fatal.
.sp
More events can be delivered than requested if
.B ctrun
requires them
for its own purposes. For example,
.B empty
messages are always requested
if a lifetime of
.B contract
is specified. See
.BR -l .
.RE

.sp
.ne 2
.mk
.na
.B -F
.I fmri
.ad
.RS 26n
.rt
Sets the process contract service
.B FMRI
field. To set this field the
caller is required to have the
.B {PRIV_CONTRACT_IDENTITY}
in its
effective set.
.RE

.sp
.ne 2
.mk
.na
.B -l
.I lifetime
.ad
.RS 26n
.rt
The following valid
.I lifetime
values are supported:
.sp
.ne 2
.mk
.na
.B child
.ad
.RS 12n
.rt
.B ctrun
exits when the command exits, regardless of whether the
contract is empty.
.RE

.sp
.ne 2
.mk
.na
.B contract
.ad
.RS 12n
.rt
.B ctrun
exits only when the contract exits. This is the default.
.RE

.sp
.ne 2
.mk
.na
.B none
.ad
.RS 12n
.rt
.B ctrun
exits immediately, orphaning the contract.
.RE

.RE

.sp
.ne 2
.mk
.na
\fB-o\fR \fIoption\fR,[\fIoption\fR .\|.\|.]\fR
.ad
.RS 26n
.rt
The following
.IR option "s are supported:"
.sp
.ne 2
.mk
.na
.B noorphan
.ad
.RS 12n
.rt
Kills all processes in the contract if the holder
.RB ( ctrun )
exits.
.sp
This option is invalid when a lifetime of
.B none
is specified.
.RE

.sp
.ne 2
.mk
.na
.B pgrponly
.ad
.RS 12n
.rt
If a fatal error occurs, kills at most the process group of which the
errant process is a member.
.RE

.sp
.ne 2
.mk
.na
.B regent
.ad
.RS 12n
.rt
The contract inherits inheritable contracts when abandoned by member
processes.
.RE

.RE

.sp
.ne 2
.mk
.na
.B -r
.I count
.ad
.RS 26n
.rt
If the contract encounters a fault, this option attempts to restart the
command
.I count
times. If
.I count
is
.BR 0 ,
the attempt to restart
continues indefinitely. By default,
.B ctrun
does not attempt to restart
the command.
.sp
This option is invalid if a lifetime other than
.B contract
is specified
or if the
.B pgrponly
option is used.
.RE

.sp
.ne 2
.mk
.na
.B -t
.ad
.RS 26n
.rt
If the contract created by
.B ctrun
inherited subcontracts from its
member processes, attempts to transfer them to the new contract when
restarting.
.sp
This option is invalid unless
.B -r
is also specified.
.RE

.sp
.ne 2
.mk
.na
.B -v
.ad
.RS 26n
.rt
Displays contract events and
.B ctrun
actions as they occur.
.RE

.sp
.ne 2
.mk
.na
.B -V
.ad
.RS 26n
.rt
Displays verbose contract events, as are displayed by the
.B -v
option
of
.BR ctwatch .
Implies
.BR -v .
.RE

.SH OPERANDS
.sp
.LP
The following operands are supported:
.sp
.ne 2
.mk
.na
.I argument
.ad
.RS 12n
.rt
One of the strings treated as an argument to
.IR command .
.RE

.sp
.ne 2
.mk
.na
.I command
.ad
.RS 12n
.rt
The command to be passed to
.BR execvp (2).
See
.BR exec (2).
.RE

.SH EXAMPLES
.LP
.B Example 1
Running a Shell in a New Process Contract
.sp
.LP
The following example runs a shell in a new process contract:

.sp
.in +2
.nf
example% ctrun -l child -o pgrponly ksh
.fi
.in -2
.sp

.sp
.LP
The
.B "-l child"
option argument is specified so that
.BR ctrun
won't wait until all children of the shell have exited.
.B -o
.B pgrponly
is specified because an interactive
.B ksh
puts each job
in a new process group, and an error in one job is unlikely to affect the
others.

.LP
.B Example 2
Running a Simple Server
.sp
.LP
The following example runs a simple server:

.sp
.in +2
.nf
example% \fBctrun -r 0 -t -f hwerr,core,signal server\fR
.fi
.in -2
.sp

.sp
.LP
The
.B "-r 0"
and
.B -t
options are specified to indicate that if
the server encounters a fatal error,
.B ctrun
should try to restart it.
The \fB-f\fR option makes "\fBhwerr\fR", "\fBcore\fR", and "\fBsignal\fR"
fatal events.

.SH EXIT STATUS
.sp
.LP
If
.I command
is specified and successfully invoked (see
.BR exec (2)),
the exit status of
.B ctrun
is the exit status of
.IR command .
Otherwise,
.B ctrun
exits with one of the following values:
.sp
.ne 2
.mk
.na
.B 123
.ad
.RS 7n
.rt
The child process exited abnormally.
.RE

.sp
.ne 2
.mk
.na
.B 124
.ad
.RS 7n
.rt
.B ctrun
encountered an internal error.
.RE

.sp
.ne 2
.mk
.na
.B 125
.ad
.RS 7n
.rt
Invalid arguments were provided to
.BR ctrun .
.RE

.sp
.ne 2
.mk
.na
.B 126
.ad
.RS 7n
.rt
.I command
was found but could not be invoked.
.RE

.sp
.ne 2
.mk
.na
.B 127
.ad
.RS 7n
.rt
.I command
could not be found.
.RE

.SH FILES
.sp
.ne 2
.mk
.na
.B /system/contract/process/*
.ad
.RS 30n
.rt

.RE

.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i)
lw(2.75i) |lw(2.75i)
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWcsu
_
Interface StabilitySee below.
.TE

.sp
.LP
Human Readable Output is Uncommitted. Invocation is Committed.
.SH SEE ALSO
.sp
.LP
.BR ctstat (1),
.BR ctwatch (1),
.BR exec (2),
.BR contract (4),
.BR process (4),
.BR attributes (5)
