'\" te
.\" Copyright (C) 1990, Regents of the University of Michigan.  All Rights Reserved.
.\" Portions Copyright (C) 2004, Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright (c) 2012-2013, J. Schilling
.\" Copyright (c) 2013, Andreas Roehler
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH ldapmodify 1 "15 Jan 2004" "SunOS 5.11" "User Commands"
.SH NAME
ldapmodify, ldapadd \- ldap entry addition and modification tools
.SH SYNOPSIS
.LP
.nf
\fBldapmodify\fR [\fB-a\fR] [\fB-c\fR] [\fB-r\fR] [\fB-n\fR] [\fB-v\fR] [\fB-F\fR] [\fB-b\fR] [\fB-A\fR] [\fB-q\fR]
     [\fB-H\fR] [\fB-?\fR] [\fB-E\fR] [\fB-J\fR] [\fB-Z\fR] [\fB-M\fR] [\fB-d\fR \fIdebuglevel\fR]
     [\fB-D\fR \fIbindDN\fR] [\fB-j\fR \fIfilename\fR] [\fB-J\fR [:\fIcriticality\fR]]
     [\fB-B\fR \fIbaseDN\fR] [\fB-V\fR \fIversion\fR] [\fB-Y\fR \fIproxyDN\fR] [\fB-O\fR \fIhopLimit\fR]
     [\fB-i\fR \fIlocale\fR] [\fB-k\fR \fIpath\fR] [\fB-e\fR \fIerrorFile\fR] [\fB-P\fR \fIpath\fR]
     [\fB-N\fR \fIcertificate\fR] [\fB-w\fR \fIpasswd\fR] [\fB-o\fR \fIattributename\fR=\fIvalue\fR]
     [\fB-h\fR \fIldaphost\fR] [\fB-W\fR \fIpassword\fR] [\fB-p\fR \fIldapport\fR] [\fB-f\fR \fIfile\fR]
     [\fB-l\fR \fInb-ldap-connections\fR]
.fi

.LP
.nf
\fBldapadd\fR [\fB-c\fR] [\fB-n\fR] [\fB-v\fR] [\fB-F\fR]
     [ [\fB-b\fR] [\fB-A\fR] [\fB-q\fR] [\fB-H\fR] [\fB-?\fR] [\fB-E\fR] [\fB-J\fR] [\fB-Z\fR] [\fB-M\fR]\fB-d\fR \fIdebuglevel\fR]
     [\fB-D\fR \fIbindDN\fR] [\fB-j\fR \fIfilename\fR] [\fB-B\fR \fIbaseDN\fR] [\fB-V\fR \fIversion\fR]
     [\fB-Y\fR \fIproxyDN\fR] [\fB-O\fR \fIhopLimit\fR] [\fB-i\fR \fIlocale\fR] [\fB-k\fR \fIpath\fR]
     [\fB-e\fR \fIerrorFile\fR] [\fB-P\fR \fIpath\fR] [\fB-N\fR \fIcertificate\fR] [\fB-w\fR \fIpasswd\fR]
     [\fB-o\fR \fIattributename\fR=\fIvalue\fR] [\fB-h\fR \fIldaphost\fR] [\fB-W\fR \fIpassword\fR]
     [\fB-p\fR \fIldapport\fR] [\fB-f\fR \fIfile\fR] [\fB-l\fR \fInb-ldap-connections\fR]
.fi

.SH DESCRIPTION
.sp
.LP
The
.B ldapmodify
utility opens a connection to an
.B LDAP
server,
binds and modifies or adds entries. The entry information is read from
standard input or from
.IR file ,
specified using the
.B -f
option. The
.B ldapadd
utility is implemented as a hard link to the \fBldapmodify\fR
tool. When invoked as
.BR ldapadd ,
the
.B -a
(add new entry) option is
turned on automatically.
.sp
.LP
Both
.B ldapadd
and
.B ldapmodify
reject duplicate
attribute-name/value pairs for the same entry.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
.B -a
.ad
.sp .6
.RS 4n
Adds new entries. The default for
.B ldapmodify
is to modify existing
entries. If invoked as
.BR ldapadd ,
this option is always set.
.RE

.sp
.ne 2
.mk
.na
.B -A
.ad
.sp .6
.RS 4n
.RB "Non-ASCII mode: display non-ASCII values, in conjunction with the" " -v"
option.
.RE

.sp
.ne 2
.mk
.na
.B -b
.ad
.sp .6
.RS 4n
Handle binary files. The
.B ldapmodify
tool will scan every attribute
value in the input to determine whether it is a valid file reference. If the
reference is valid, it will use the contents of the file as the attribute's
value. This option is used to input binary data, such as a JPEG image, for
an attribute. For example, the corresponding LDIF input would be: "\fB
jpegPhoto: /tmp/photo.jpg\fR" The \fBldapmodify\fR tool also supports the
LDIF \fB:< \fIURL\fR notation for directly including file contents.
.RE

.sp
.ne 2
.mk
.na
\fB-B\fR\ \fIbaseDN\fR
.ad
.sp .6
.RS 4n
Specify the base DN when performing additions, usually in double quotes
(\fB""\fR) for the shell. All entries will be placed under this suffix, thus
providing bulk import functionality.
.RE

.sp
.ne 2
.mk
.na
.B -c
.ad
.sp .6
.RS 4n
Specifies continuous operation mode. Errors are reported, but
.B ldapmodify
and
.B ldapadd
continue with modifications. The default
is to exit after reporting an error.
.RE

.sp
.ne 2
.mk
.na
.B -D
.I bindDN
.ad
.sp .6
.RS 4n
Uses the distinguished name
.I bindDN
to bind to the directory.
.RE

.sp
.ne 2
.mk
.na
.B -d
.I debuglevel
.ad
.sp .6
.RS 4n
Sets the
.B LDAP
debugging level. Useful levels of debugging for
.B ldapmodify
and
.B ldapadd
are:
.sp
.ne 2
.mk
.na
.B 1
.ad
.RS 7n
.rt
Trace
.RE

.sp
.ne 2
.mk
.na
.B 2
.ad
.RS 7n
.rt
Packets
.RE

.sp
.ne 2
.mk
.na
.B 4
.ad
.RS 7n
.rt
Arguments
.RE

.sp
.ne 2
.mk
.na
.B 32
.ad
.RS 7n
.rt
Filters
.RE

.sp
.ne 2
.mk
.na
.B 128
.ad
.RS 7n
.rt
Access control
.RE

To request more than one category of debugging information, add the masks.
For example, to request trace and filter information, specify a
.I debuglevel
of 33.
.RE

.sp
.ne 2
.mk
.na
\fB-e\fR\ \fIerrorFile\fR
.ad
.sp .6
.RS 4n
Invalid update statements in the input will be copied to the
.I errorFile
for debugging. Use with the
.B -c
option to correct
errors when processing large LDIF input.
.RE

.sp
.ne 2
.mk
.na
.B -E
.ad
.sp .6
.RS 4n
Ask server to expose (report) bind identity by means of authentication
response control.
.RE

.sp
.ne 2
.mk
.na
.B -F
.ad
.sp .6
.RS 4n
Forces application of all changes regardless of the content of input lines
that begin with
.BR replica: .
By default,
.B replica:
lines are
compared against the
.B LDAP
server host and port in use to decide
whether a replog record should be applied.
.RE

.sp
.ne 2
.mk
.na
.B -f
.I file
.ad
.sp .6
.RS 4n
Reads the entry modification information from
.I file
instead of from
standard input.
.RE

.sp
.ne 2
.mk
.na
.B -?
.ad
.sp .6
.RS 4n
Display the usage help text that briefly describes all options.
.RE

.sp
.ne 2
.mk
.na
.B -H
.ad
.sp .6
.RS 4n
Display the usage help text that briefly describes all options.
.RE

.sp
.ne 2
.mk
.na
.B -h
.I ldaphost
.ad
.sp .6
.RS 4n
Specifies an alternate host on which the LAPD server is running.
.RE

.sp
.ne 2
.mk
.na
.B -i
.I locale
.ad
.sp .6
.RS 4n
Specify the character set to use for the \fB-f\fR \fILDIFfile\fR or
standard input. The default is the character set specified in the \fBLANG\fR
environment variable. You might choose to use this option to perform the
conversion from the specified character set to UTF8, thus overriding the
.B LANG
setting.
.RE

.sp
.ne 2
.mk
.na
.B -j
.I filename
.ad
.sp .6
.RS 4n
Specify a file containing the password for the bind DN or the password for
the SSL client's key database. To protect the password, use this option in
scripts and place the password in a secure file. This option is mutually
exclusive of the
.B -w
and
.B -W
options.
.RE

.sp
.ne 2
.mk
.na
.B -J
[:\fIcriticality\fR[:\fIvalue\fR|::\fIb64value\fR|\fIb64value\fR|:\fIfileurl\fR]]\fR
.ad
.sp .6
.RS 4n
Criticality is a boolean value (default is
.BR false ).
.RE

.sp
.ne 2
.mk
.na
.B -k
.I path
.ad
.sp .6
.RS 4n
Specify the path to a directory containing conversion routines. These
routines are used if you want to specify a locale that is not supported by
default by your directory server. This is for NLS support.
.RE

.sp
.ne 2
.mk
.na
.BI -l " nb-ldap-connections"
.ad
.sp .6
.RS 4n
Specifies the number of
.B LDAP
connections that
.B ldapadd
or
.B ldapmodify
will open to process the modifications in the directory.
The default is one connection.
.RE

.sp
.ne 2
.mk
.na
.B -M
.ad
.sp .6
.RS 4n
Manage smart referrals. When they are the target of the operation, modify
the entry containing the referral instead of the entry obtained by following
the referral.
.RE

.sp
.ne 2
.mk
.na
.B -n
.ad
.sp .6
.RS 4n
Previews modifications, but makes no changes to entries. Useful in
conjunction with
.B -v
and
.B -d
for debugging.
.RE

.sp
.ne 2
.mk
.na
.B -N
.I certificate
.ad
.sp .6
.RS 4n
Specify the certificate name to use for certificate-based client
authentication. For example: \fB-N "Directory-Cert"\fR.
.RE

.sp
.ne 2
.mk
.na
\fB-o\fR \fIattributename\fR=\fIvalue\fR
.ad
.sp .6
.RS 4n
For SASL mechanisms and other options such as security properties, mode of
operation, authorization ID, authentication ID, and so forth.
.sp
The different attribute names and their values are as follows:
.sp
.ne 2
.mk
.na
\fBsecProp\fR=\fI"number"\fR
.ad
.RS 20n
.rt
For defining SASL security properties.
.RE

.sp
.ne 2
.mk
.na
\fBrealm\fR=\fI"value"\fR
.ad
.RS 20n
.rt
Specifies SASL realm (default is
.BR realm=none ).
.RE

.sp
.ne 2
.mk
.na
\fBauthzid\fR=\fI"value"\fR
.ad
.RS 20n
.rt
Specify the authorization ID name for SASL bind.
.RE

.sp
.ne 2
.mk
.na
\fBauthid\fR=\fI"value"\fR
.ad
.RS 20n
.rt
Specify the authentication ID for SASL bind.
.RE

.sp
.ne 2
.mk
.na
\fBmech\fR=\fI"value"\fR
.ad
.RS 20n
.rt
Specifies the various SASL mechanisms.
.RE

.RE

.sp
.ne 2
.mk
.na
.B -O
.I hopLimit
.ad
.sp .6
.RS 4n
Specify the maximum number of referral hops to follow while finding an
entry to modify. By default, there is no limit.
.RE

.sp
.ne 2
.mk
.na
.B -p
.I ldapport
.ad
.sp .6
.RS 4n
Specifies an alternate
.B TCP
port where the secure LDAP server is
listening.
.RE

.sp
.ne 2
.mk
.na
.B -P
.I path
.ad
.sp .6
.RS 4n
Specify the path and filename of the client's certificate database. For
example:
.sp
.in +2
.nf
-P /home/uid/.netscape/cert7.db
.fi
.in -2

When using the command on the same host as the directory server, you can
use the server's own certificate database. For example:
.sp
.in +2
.nf
-P \fIinstallDir\fR/lapd-serverID/alias/cert7.db
.fi
.in -2

Use the
.B -P
option alone to specify server authentication only.
.RE

.sp
.ne 2
.mk
.na
.B -r
.ad
.sp .6
.RS 4n
Replaces existing value with the specified value. This is the default for
.BR ldapmodify .
When
.B ldapadd
is called, or if the
.B -a
option is
specified, the
.B -r
option is ignored.
.RE

.sp
.ne 2
.mk
.na
.B -v
.ad
.sp .6
.RS 4n
Uses verbose mode, with diagnostics written to standard output.
.RE

.sp
.ne 2
.mk
.na
.B -V
.I version
.ad
.sp .6
.RS 4n
Specify the LDAP protocol version number to be used for the delete
operation, either 2 or 3. LDAP v3 is the default. Specify LDAP v2 when
connecting to servers that do not support v3.
.RE

.sp
.ne 2
.mk
.na
.B -W
.I password
.ad
.sp .6
.RS 4n
Specify the password for the client's key database given in the \fB-P\fR
option. This option is required for certificate-based client authentication.
Specifying
.I password
on the command line has security issues because
the password can be seen by others on the system by means of the
.BR ps
command. Use the
.B -j
instead to specify the password from the file.
This option is mutually exclusive of
.BR -j .
.RE

.sp
.ne 2
.mk
.na
.B -w
.I passwd
.ad
.sp .6
.RS 4n
Use
.I passwd
as the password for authentication to the directory. When
you use \fB-w\fI passwd\fR to specify the password to be used for
authentication, the password is visible to other users of the system by
means of the
.B ps
command, in script files or in shell history. If you
use either the
.B ldapmodify
command or the
.B ldapadd
command without
this option, the command will prompt for the password and read it from
standard in. When used without the
.B -w
option, the password will not be
visible to other users.
.RE

.sp
.ne 2
.mk
.na
.B -Y
.I proxyid
.ad
.sp .6
.RS 4n
Specify the proxy DN (proxied authorization id) to use for the modify
operation, usually in double quotes ("") for the shell.
.RE

.sp
.ne 2
.mk
.na
.B -Z
.ad
.sp .6
.RS 4n
Specify that SSL be used to provide certificate-based client
authentication. This option requires the
.B -N
and SSL password and any
other of the SSL options needed to identify the certificate and the key
database.
.RE

.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.mk
.na
.B 0
.ad
.RS 13n
.rt
Successful completion.
.RE

.sp
.ne 2
.mk
.na
.B Non-zero
.ad
.RS 13n
.rt
An error occurred. A diagnostic message is written to standard error.
.RE

.SH EXAMPLES
.sp
.LP
The format of the content of \fIfile\fR (or standard input if no \fB-f\fR
option is specified) is illustrated in the following examples.
.LP
.B Example 1
Modifying an Entry
.sp
.LP
The file
.B /tmp/entrymods
contains the following modification
instructions:

.sp
.in +2
.nf
     dn: cn=Modify Me, o=XYZ, c=US
    changetype: modify
    replace: mail
    mail: modme@atlanta.xyz.com
    -
    add: title
    title: System Manager
    -
    add: jpegPhoto
    jpegPhoto:< file:///tmp/modme.jpeg
    -
    delete: description
    -
.fi
.in -2

.sp
.LP
The command:

.sp
.in +2
.nf
example% \fBldapmodify -r -f /tmp/entrymods\fR
.fi
.in -2
.sp

.sp
.LP
modifies the
.B "Modify Me"
entry as follows:

.RS +4
.TP
1.
The current value of the
.B mail
attribute is replaced with the value,
.BR modme@atlanta.xyz.com .
.RE
.RS +4
.TP
2.
A
.B title
attribute with the value,
.BR "System Manager" ,
is added.
.RE
.RS +4
.TP
3.
A
.B jpegPhoto
attribute is added, using the contents of the file,
.BR /tmp/modme.jpeg ,
as the attribute value.
.RE
.RS +4
.TP
4.
The
.B description
attribute is removed.
.RE
.LP
.B Example 2
Creating a New Entry
.sp
.LP
The file,
.BR /tmp/newentry ,
contains the following information for
creating a new entry:

.sp
.in +2
.nf
    dn: cn=Ann Jones, o=XYZ, c=US
    objectClass: person
    cn: Ann Jones
    cn: Annie Jones
    sn: Jones
    title: Director of Research and Development
    mail: ajones@londonrd.xyz.us.com
    uid: ajones
.fi
.in -2

.sp
.LP
The command

.sp
.in +2
.nf
example% \fBldapadd -f /tmp/newentry\fR
.fi
.in -2
.sp

.sp
.LP
adds a new entry for
.BR "Ann Jones" ,
using the information in the file.

.LP
.B Example 3
Creating a New Entry on an IPv6 Server
.sp
.LP
The file,
.BR /tmp/newentry ,
contains the following information for
creating a new entry: on an IPv6 server.

.sp
.in +2
.nf
    dn: cn=Ann Jones, o=XYZ, c=US
    objectClass: person
    cn: Ann Jones
    cn: Annie Jones
    sn: Jones
    title: Director of Research and Development
    mail: ajones@londonrd.xyz.us.com
    uid: ajones
.fi
.in -2

.sp
.LP
The command

.sp
.in +2
.nf
example% \fBldapadd -c -v -h '['fec0::111:a00:20ff:feaa:a364']':389 \e
                         -D cn=Directory Manager -w secret \e
                         -f /tmp/entry \fR
.fi
.in -2
.sp

.sp
.LP
adds a new entry for
.BR "Directory Manager" ,
using the information in the
file.

.LP
.B Example 4
Deleting an Entry
.sp
.LP
The file,
.BR /tmp/badentry ,
contains the following information about an
entry to be deleted:

.sp
.in +2
.nf
    dn: cn=Ann Jones, o=XYZ, c=US
    changetype: delete
.fi
.in -2

.sp
.LP
The command:

.sp
.in +2
.nf
example% \fBldapmodify -f /tmp/badentry\fR
.fi
.in -2
.sp

.sp
.LP
removes Ann Jones' entry.

.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for a description of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i)
lw(2.75i) |lw(2.75i)
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWcsu
Stability LevelEvolving
.TE

.SH SEE ALSO
.sp
.LP
.BR ldap (1),
.BR ldapdelete (1),
.BR ldaplist (1),
.BR ldapmodrdn (1),
.BR ldapsearch (1),
.BR ldapaddent (1M),
.BR ldap_cachemgr (1M),
.BR ldap_get_option (3LDAP),
.BR ldap_set_option (3LDAP),
.BR attributes (5)
