.\" @(#)local.1	1.1 16/09/12 Copyr 2016 J. Schilling
.\" Manual page for local
.\"@@C@@
.\"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.75n'U
.if t .ds s \\(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH local 1 "2016/09/12" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
local \- shell built-in to set up shell variables local to a function
.SH SYNOPSIS
\fBlocal\fR [ \fIname\fR[\fB=\fIvalue\fR] .\|.\|. ]
.SH DESCRIPTION
The given
.IR name s
are marked for local scope to the
.B function
from where
.B local
is called.
The scope is effective for the rest of the
.B function
and its children or until
.B local
is called again with the same variable
.IR name .
The local variable is created with the same content and attributes as the
current variable.
If the local variable is exported, it's local value is seen by child
processes called from a function.
If no arguments are given, variable names that have been marked
for local scope are listed.
It is an error to use
.B local
when not within a function.
.SH OPTIONS
.LP
None.

.SH EXAMPLES
.SH ENVIRONMENT
.SH FILES
.SH "SEE ALSO"
.BR bosh (1)
.SH DIAGNOSTICS
.SH NOTES
.SH BUGS
.SH AUTHOR
.nf
J\*org Schilling
D-13353 Berlin
Germany
.fi
.PP
Mail bugs and suggestions to:
.PP
.B
joerg.schilling@fokus.fraunhofer.de
or
.B
joerg@schily.net
