#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	1

MANFILES=				\
	Intro.1				\
	acctcom.1			\
	adb.1				\
	addbib.1			\
	alias.1				\
	allocate.1			\
	amt.1				\
	appcert.1			\
	apptrace.1			\
	apropos.1			\
	ar.1				\
	arch.1				\
	as.1				\
	asa.1				\
	at.1				\
	atq.1				\
	atrm.1				\
	audioconvert.1			\
	audioctl.1			\
	audioplay.1			\
	audiorecord.1			\
	audiotest.1			\
	auths.1				\
	auto_ef.1			\
	awk.1				\
	banner.1			\
	basename.1			\
	bc.1				\
	bdiff.1				\
	bfs.1				\
	bosh.1				\
	break.1				\
	builtin.1			\
	cal.1				\
	calendar.1			\
	cancel.1			\
	cat.1				\
	cd.1				\
	cdrw.1				\
	checknr.1			\
	chgrp.1				\
	chkey.1				\
	chmod.1				\
	chown.1				\
	ckdate.1			\
	ckgid.1				\
	ckint.1				\
	ckitem.1			\
	ckkeywd.1			\
	ckpath.1			\
	ckrange.1			\
	ckstr.1				\
	cksum.1				\
	cktime.1			\
	ckuid.1				\
	ckyorn.1			\
	clear.1				\
	cmp.1				\
	col.1				\
	comm.1				\
	command.1			\
	compress.1			\
	cp.1				\
	cpio.1				\
	cputrack.1			\
	crle.1				\
	crontab.1			\
	crypt.1				\
	csh.1				\
	csplit.1			\
	ctags.1				\
	ctrun.1				\
	ctstat.1			\
	ctwatch.1			\
	cut.1				\
	date.1				\
	dc.1				\
	deallocate.1			\
	deroff.1			\
	des.1				\
	dhcpinfo.1			\
	diff.1				\
	diff3.1				\
	diffmk.1			\
	digest.1			\
	dircmp.1			\
	dis.1				\
	disown.1			\
	dispgid.1			\
	dispuid.1			\
	dos2unix.1			\
	download.1			\
	dpost.1				\
	dtappsession.1			\
	du.1				\
	dump.1				\
	dumpcs.1			\
	echo.1				\
	ed.1				\
	edit.1				\
	egrep.1				\
	eject.1				\
	elfdump.1			\
	elfedit.1			\
	elfsign.1			\
	elfwrap.1			\
	enable.1			\
	encrypt.1			\
	enhance.1			\
	env.1				\
	eqn.1				\
	ex.1				\
	exec.1				\
	exit.1				\
	expand.1			\
	expr.1				\
	exstr.1				\
	factor.1			\
	fdformat.1			\
	fgrep.1				\
	file.1				\
	filebench.1			\
	filesync.1			\
	find.1				\
	finger.1			\
	fmli.1				\
	fmt.1				\
	fmtmsg.1			\
	fold.1				\
	ftp.1				\
	ftpcount.1			\
	ftpwho.1			\
	gcore.1				\
	gencat.1			\
	genmsg.1			\
	getconf.1			\
	getfacl.1			\
	getlabel.1			\
	getopt.1			\
	getoptcvt.1			\
	getopts.1			\
	gettext.1			\
	gettxt.1			\
	getzonepath.1			\
	glob.1				\
	gprof.1				\
	graph.1				\
	grep.1				\
	groups.1			\
	hash.1				\
	head.1				\
	history.1			\
	hostid.1			\
	hostname.1			\
	iconv.1				\
	indxbib.1			\
	ipcrm.1				\
	ipcs.1				\
	isainfo.1			\
	isalist.1			\
	jobs.1				\
	join.1				\
	kbd.1				\
	kdestroy.1			\
	keylogin.1			\
	keylogout.1			\
	kill.1				\
	kinit.1				\
	klist.1				\
	kmdb.1				\
	kmfcfg.1			\
	kpasswd.1			\
	krb5-config.1			\
	ksh.1				\
	ksh93.1				\
	ktutil.1			\
	lari.1				\
	last.1				\
	lastcomm.1			\
	ld.1				\
	ld.so.1.1			\
	ldap.1				\
	ldapdelete.1			\
	ldaplist.1			\
	ldapmodify.1			\
	ldapmodrdn.1			\
	ldapsearch.1			\
	ldd.1				\
	let.1				\
	lex.1				\
	lgrpinfo.1			\
	limit.1				\
	line.1				\
	list_devices.1			\
	listusers.1			\
	ln.1				\
	loadkeys.1			\
	locale.1			\
	localedef.1			\
	logger.1			\
	login.1				\
	logname.1			\
	logout.1			\
	look.1				\
	lookbib.1			\
	lorder.1			\
	lp.1				\
	lpstat.1			\
	ls.1				\
	m4.1				\
	mac.1				\
	mach.1				\
	machid.1			\
	madv.so.1.1			\
	mail.1				\
	mailcompat.1			\
	mailq.1				\
	mailstats.1			\
	mailx.1				\
	Makefile			\
	makekey.1			\
	man.1				\
	mconnect.1			\
	mcs.1				\
	mdb.1				\
	mesg.1				\
	mixerctl.1			\
	mkdir.1				\
	mkmsgs.1			\
	mktemp.1			\
	moe.1				\
	more.1				\
	mpss.so.1.1			\
	msgcc.1				\
	msgcpp.1			\
	msgcvt.1			\
	msgfmt.1			\
	msggen.1			\
	msgget.1			\
	mt.1				\
	mv.1				\
	nawk.1				\
	nc.1				\
	nca.1				\
	ncab2clf.1			\
	ncakmod.1			\
	newform.1			\
	newgrp.1			\
	news.1				\
	newtask.1			\
	nice.1				\
	NIS+.1				\
	niscat.1			\
	nischgrp.1			\
	nischmod.1			\
	nischown.1			\
	nischttl.1			\
	nisdefaults.1			\
	niserror.1			\
	nisgrpadm.1			\
	nisln.1				\
	nisls.1				\
	nismatch.1			\
	nismkdir.1			\
	nisopaccess.1			\
	nispasswd.1			\
	nisrm.1				\
	nisrmdir.1			\
	nistbladm.1			\
	nistest.1			\
	nl.1				\
	nm.1				\
	nohup.1				\
	nroff.1				\
	od.1				\
	on.1				\
	optisa.1			\
	pack.1				\
	pagesize.1			\
	pargs.1				\
	passwd.1			\
	paste.1				\
	patch.1				\
	pathchk.1			\
	pax.1				\
	pfexec.1			\
	pg.1				\
	pgrep.1				\
	pkcs11_inspect.1		\
	pkginfo.1			\
	pkgmk.1				\
	pkgparam.1			\
	pkgproto.1			\
	pkgtrans.1			\
	pklogin_finder.1		\
	pktool.1			\
	plabel.1			\
	plgrp.1				\
	plimit.1			\
	pmadvise.1			\
	pmap.1				\
	postdaisy.1			\
	postdmd.1			\
	postio.1			\
	postmd.1			\
	postplot.1			\
	postprint.1			\
	postreverse.1			\
	posttek.1			\
	ppgsz.1				\
	ppriv.1				\
	pr.1				\
	praliases.1			\
	prctl.1				\
	preap.1				\
	prex.1				\
	print.1				\
	printf.1			\
	priocntl.1			\
	proc.1				\
	prof.1				\
	profiles.1			\
	projects.1			\
	ps.1				\
	ptree.1				\
	pvs.1				\
	pwd.1				\
	ranlib.1			\
	rcapstat.1			\
	rcp.1				\
	rdist.1				\
	read.1				\
	readonly.1			\
	refer.1				\
	regcmp.1			\
	renice.1			\
	rev.1				\
	rlogin.1			\
	rm.1				\
	rmformat.1			\
	rmmount.1			\
	roffbib.1			\
	roles.1				\
	rpcgen.1			\
	rpm2cpio.1			\
	rsh.1				\
	runat.1				\
	rup.1				\
	ruptime.1			\
	rusers.1			\
	rwho.1				\
	sag.1				\
	sar.1				\
	sccs-admin.1			\
	sccs-cdc.1			\
	sccs-comb.1			\
	sccs-delta.1			\
	sccs-get.1			\
	sccs-help.1			\
	sccs-prs.1			\
	sccs-prt.1			\
	sccs-rmdel.1			\
	sccs-sact.1			\
	sccs-sccsdiff.1			\
	sccs-unget.1			\
	sccs-val.1			\
	sccs.1				\
	scp.1				\
	script.1			\
	sdiff.1				\
	sed.1				\
	set.1				\
	setfacl.1			\
	setlabel.1			\
	setpgrp.1			\
	sftp.1				\
	sh.1				\
	shcomp.1			\
	shell_builtins.1		\
	shift.1				\
	size.1				\
	sleep.1				\
	smbutil.1			\
	soelim.1			\
	sort.1				\
	sortbib.1			\
	sotruss.1			\
	spell.1				\
	spline.1			\
	split.1				\
	srchtxt.1			\
	ssh-add.1			\
	ssh-agent.1			\
	ssh-http-proxy-connect.1	\
	ssh-keygen.1			\
	ssh-keyscan.1			\
	ssh-socks5-proxy-connect.1	\
	ssh.1				\
	strchg.1			\
	strings.1			\
	strip.1				\
	stty.1				\
	sum.1				\
	suspend.1			\
	svcprop.1			\
	svcs.1				\
	symorder.1			\
	sys-suspend.1			\
	sysV-make.1			\
	tabs.1				\
	tail.1				\
	talk.1				\
	tar.1				\
	tbl.1				\
	tcopy.1				\
	tee.1				\
	telnet.1			\
	test.1				\
	tftp.1				\
	time.1				\
	times.1				\
	timex.1				\
	tip.1				\
	tnfdump.1			\
	tnfxtract.1			\
	touch.1				\
	tplot.1				\
	tput.1				\
	tr.1				\
	trap.1				\
	troff.1				\
	true.1				\
	truss.1				\
	tsort.1				\
	tty.1				\
	type.1				\
	typeset.1			\
	ul.1				\
	umask.1				\
	uname.1				\
	unifdef.1			\
	uniq.1				\
	units.1				\
	unix2dos.1			\
	uptime.1			\
	vacation.1			\
	vc.1				\
	vgrind.1			\
	vi.1				\
	volcheck.1			\
	volrmmount.1			\
	w.1				\
	wait.1				\
	wc.1				\
	what.1				\
	whatis.1			\
	which.1				\
	who.1				\
	whocalls.1			\
	whois.1				\
	write.1				\
	xargs.1				\
	xgettext.1			\
	xstr.1				\
	yacc.1				\
	yes.1				\
	ypcat.1				\
	ypmatch.1			\
	yppasswd.1			\
	ypwhich.1			\
	zlogin.1			\
	zonename.1

MANSO=					\
	admin.1				\
	batch.1				\
	bg.1				\
	case.1				\
	cdc.1				\
	chdir.1				\
	checkeq.1			\
	comb.1				\
	continue.1			\
	decrypt.1			\
	delta.1				\
	dirname.1			\
	dirs.1				\
	disable.1			\
	dumpkeys.1			\
	errange.1			\
	errdate.1			\
	errgid.1			\
	errint.1			\
	erritem.1			\
	errpath.1			\
	errstr.1			\
	errtime.1			\
	erruid.1			\
	erryorn.1			\
	eval.1				\
	export.1			\
	false.1				\
	fc.1				\
	fg.1				\
	for.1				\
	foreach.1			\
	function.1			\
	get.1				\
	goto.1				\
	hashcheck.1			\
	hashmake.1			\
	hashstat.1			\
	help.1				\
	helpdate.1			\
	helpgid.1			\
	helpint.1			\
	helpitem.1			\
	helppath.1			\
	helprange.1			\
	helpstr.1			\
	helptime.1			\
	helpuid.1			\
	helpyorn.1			\
	hist.1				\
	i286.1				\
	i386.1				\
	i486.1				\
	i860.1				\
	iAPX286.1			\
	if.1				\
	intro.1				\
	jsh.1				\
	ldapadd.1			\
	neqn.1				\
	nis.1				\
	nis+.1				\
	nisgrep.1			\
	notify.1			\
	onintr.1			\
	page.1				\
	pcat.1				\
	pcred.1				\
	pdp11.1				\
	pfcsh.1				\
	pfiles.1			\
	pfksh.1				\
	pflags.1			\
	pfsh.1				\
	pkill.1				\
	pldd.1				\
	popd.1				\
	prs.1				\
	prt.1				\
	prun.1				\
	psig.1				\
	pstack.1			\
	pstop.1				\
	ptime.1				\
	pushd.1				\
	pwait.1				\
	pwdx.1				\
	red.1				\
	rehash.1			\
	remote_shell.1			\
	remsh.1				\
	repeat.1			\
	return.1			\
	rksh.1				\
	rksh93.1			\
	rmail.1				\
	rmdel.1				\
	rmdir.1				\
	rmumount.1			\
	sact.1				\
	sccsdiff.1			\
	select.1			\
	setenv.1			\
	settime.1			\
	snca.1				\
	source.1			\
	sparc.1				\
	spellin.1			\
	stop.1				\
	strconf.1			\
	sun.1				\
	switch.1			\
	t300.1				\
	t300s.1				\
	t4014.1				\
	t450.1				\
	tek.1				\
	u370.1				\
	u3b.1				\
	u3b15.1				\
	u3b2.1				\
	u3b5.1				\
	ulimit.1			\
	unalias.1			\
	uncompress.1			\
	unexpand.1			\
	unget.1				\
	unhash.1			\
	unlimit.1			\
	unpack.1			\
	unset.1				\
	unsetenv.1			\
	until.1				\
	val.1				\
	valdate.1			\
	valgid.1			\
	valint.1			\
	valpath.1			\
	valrange.1			\
	valstr.1			\
	valtime.1			\
	valuid.1			\
	valyorn.1			\
	vax.1				\
	vedit.1				\
	ver.1				\
	view.1				\
	whence.1			\
	while.1				\
	zcat.1

admin.1			:= SOFILE = man1/sccs-admin.1
batch.1			:= SOFILE = man1/at.1
bg.1			:= SOFILE = man1/jobs.1
case.1			:= SOFILE = man1/shell_builtins.1
cdc.1			:= SOFILE = man1/sccs-cdc.1
chdir.1			:= SOFILE = man1/cd.1
checkeq.1		:= SOFILE = man1/eqn.1
comb.1			:= SOFILE = man1/sccs-comb.1
continue.1		:= SOFILE = man1/break.1
decrypt.1		:= SOFILE = man1/encrypt.1
delta.1			:= SOFILE = man1/sccs-delta.1
dirname.1		:= SOFILE = man1/basename.1
dirs.1			:= SOFILE = man1/cd.1
disable.1		:= SOFILE = man1/enable.1
dumpkeys.1		:= SOFILE = man1/loadkeys.1
errange.1		:= SOFILE = man1/ckrange.1
errdate.1		:= SOFILE = man1/ckdate.1
errgid.1		:= SOFILE = man1/ckgid.1
errint.1		:= SOFILE = man1/ckint.1
erritem.1		:= SOFILE = man1/ckitem.1
errpath.1		:= SOFILE = man1/ckpath.1
errstr.1		:= SOFILE = man1/ckstr.1
errtime.1		:= SOFILE = man1/cktime.1
erruid.1		:= SOFILE = man1/ckuid.1
erryorn.1		:= SOFILE = man1/ckyorn.1
eval.1			:= SOFILE = man1/exec.1
export.1		:= SOFILE = man1/set.1
false.1			:= SOFILE = man1/true.1
fc.1			:= SOFILE = man1/history.1
fg.1			:= SOFILE = man1/jobs.1
for.1			:= SOFILE = man1/shell_builtins.1
foreach.1		:= SOFILE = man1/shell_builtins.1
function.1		:= SOFILE = man1/shell_builtins.1
get.1			:= SOFILE = man1/sccs-get.1
goto.1			:= SOFILE = man1/exit.1
hashcheck.1		:= SOFILE = man1/spell.1
hashmake.1		:= SOFILE = man1/spell.1
hashstat.1		:= SOFILE = man1/hash.1
help.1			:= SOFILE = man1/sccs-help.1
helpdate.1		:= SOFILE = man1/ckdate.1
helpgid.1		:= SOFILE = man1/ckgid.1
helpint.1		:= SOFILE = man1/ckint.1
helpitem.1		:= SOFILE = man1/ckitem.1
helppath.1		:= SOFILE = man1/ckpath.1
helprange.1		:= SOFILE = man1/ckrange.1
helpstr.1		:= SOFILE = man1/ckstr.1
helptime.1		:= SOFILE = man1/cktime.1
helpuid.1		:= SOFILE = man1/ckuid.1
helpyorn.1		:= SOFILE = man1/ckyorn.1
hist.1			:= SOFILE = man1/history.1
i286.1			:= SOFILE = man1/machid.1
i386.1			:= SOFILE = man1/machid.1
i486.1			:= SOFILE = man1/machid.1
i860.1			:= SOFILE = man1/machid.1
iAPX286.1		:= SOFILE = man1/machid.1
if.1			:= SOFILE = man1/shell_builtins.1
intro.1			:= SOFILE = man1/Intro.1
jsh.1			:= SOFILE = man1/sh.1
ldapadd.1		:= SOFILE = man1/ldapmodify.1
neqn.1			:= SOFILE = man1/eqn.1
nis.1			:= SOFILE = man1/NIS+.1
nis+.1			:= SOFILE = man1/NIS+.1
nisgrep.1		:= SOFILE = man1/nismatch.1
notify.1		:= SOFILE = man1/jobs.1
onintr.1		:= SOFILE = man1/trap.1
page.1			:= SOFILE = man1/more.1
pcat.1			:= SOFILE = man1/pack.1
pcred.1			:= SOFILE = man1/proc.1
pdp11.1			:= SOFILE = man1/machid.1
pfcsh.1			:= SOFILE = man1/pfexec.1
pfiles.1		:= SOFILE = man1/proc.1
pfksh.1			:= SOFILE = man1/pfexec.1
pflags.1		:= SOFILE = man1/proc.1
pfsh.1			:= SOFILE = man1/pfexec.1
pkill.1			:= SOFILE = man1/pgrep.1
pldd.1			:= SOFILE = man1/proc.1
popd.1			:= SOFILE = man1/cd.1
prs.1			:= SOFILE = man1/sccs-prs.1
prt.1			:= SOFILE = man1/sccs-prt.1
prun.1			:= SOFILE = man1/proc.1
psig.1			:= SOFILE = man1/proc.1
pstack.1		:= SOFILE = man1/proc.1
pstop.1			:= SOFILE = man1/proc.1
ptime.1			:= SOFILE = man1/proc.1
pushd.1			:= SOFILE = man1/cd.1
pwait.1			:= SOFILE = man1/proc.1
pwdx.1			:= SOFILE = man1/proc.1
red.1			:= SOFILE = man1/ed.1
rehash.1		:= SOFILE = man1/hash.1
remote_shell.1		:= SOFILE = man1/rsh.1
remsh.1			:= SOFILE = man1/rsh.1
repeat.1		:= SOFILE = man1/shell_builtins.1
return.1		:= SOFILE = man1/exit.1
rksh.1			:= SOFILE = man1/ksh.1
rksh93.1		:= SOFILE = man1/ksh93.1
rmail.1			:= SOFILE = man1/mail.1
rmdel.1			:= SOFILE = man1/sccs-rmdel.1
rmdir.1			:= SOFILE = man1/rm.1
rmumount.1		:= SOFILE = man1/rmmount.1
sact.1			:= SOFILE = man1/sccs-sact.1
sccsdiff.1		:= SOFILE = man1/sccs-sccsdiff.1
select.1		:= SOFILE = man1/shell_builtins.1
setenv.1		:= SOFILE = man1/set.1
settime.1		:= SOFILE = man1/touch.1
snca.1			:= SOFILE = man1/nca.1
source.1		:= SOFILE = man1/exec.1
sparc.1			:= SOFILE = man1/machid.1
spellin.1		:= SOFILE = man1/spell.1
stop.1			:= SOFILE = man1/jobs.1
strconf.1		:= SOFILE = man1/strchg.1
sun.1			:= SOFILE = man1/machid.1
switch.1		:= SOFILE = man1/shell_builtins.1
t300.1			:= SOFILE = man1/tplot.1
t300s.1			:= SOFILE = man1/tplot.1
t4014.1			:= SOFILE = man1/tplot.1
t450.1			:= SOFILE = man1/tplot.1
tek.1			:= SOFILE = man1/tplot.1
u370.1			:= SOFILE = man1/machid.1
u3b.1			:= SOFILE = man1/machid.1
u3b15.1			:= SOFILE = man1/machid.1
u3b2.1			:= SOFILE = man1/machid.1
u3b5.1			:= SOFILE = man1/machid.1
ulimit.1		:= SOFILE = man1/limit.1
unalias.1		:= SOFILE = man1/alias.1
uncompress.1		:= SOFILE = man1/compress.1
unexpand.1		:= SOFILE = man1/expand.1
unget.1			:= SOFILE = man1/sccs-unget.1
unhash.1		:= SOFILE = man1/hash.1
unlimit.1		:= SOFILE = man1/limit.1
unpack.1		:= SOFILE = man1/pack.1
unset.1			:= SOFILE = man1/set.1
unsetenv.1		:= SOFILE = man1/set.1
until.1			:= SOFILE = man1/shell_builtins.1
val.1			:= SOFILE = man1/sccs-val.1
valdate.1		:= SOFILE = man1/ckdate.1
valgid.1		:= SOFILE = man1/ckgid.1
valint.1		:= SOFILE = man1/ckint.1
valpath.1		:= SOFILE = man1/ckpath.1
valrange.1		:= SOFILE = man1/ckrange.1
valstr.1		:= SOFILE = man1/ckstr.1
valtime.1		:= SOFILE = man1/cktime.1
valuid.1		:= SOFILE = man1/ckuid.1
valyorn.1		:= SOFILE = man1/ckyorn.1
vax.1			:= SOFILE = man1/machid.1
vedit.1			:= SOFILE = man1/vi.1
ver.1			:= SOFILE = man1/tplot.1
view.1			:= SOFILE = man1/vi.1
whence.1		:= SOFILE = man1/typeset.1
while.1			:= SOFILE = man1/shell_builtins.1
zcat.1			:= SOFILE = man1/compress.1

include ../Makefile.man

install: $(ROOTMANFILES)
