'\" te
.\" Copyright 1989 AT&T  Copyright (c) 1992, Sun Microsystems, Inc.  All Rights Reserved
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH postplot 1 "17 Jun 1992" "SunOS 5.11" "User Commands"
.SH NAME
postplot \- PostScript translator for plot(4B) graphics files
.SH SYNOPSIS
.LP
.nf
\fBpostplot\fR [\fB-c\fR \fInum\fR] [\fB-f\fR \fIname\fR] [\fB-m\fR \fInum\fR] [\fB-n\fR \fInum\fR] [\fB-o\fR \fIlist\fR]
     [\fB-p\fR \fImode\fR] [\fB-w\fR \fInum\fR] [\fB-x\fR \fInum\fR] [\fB-y\fR \fInum\fR] [\fIfilename\fR]...
.fi

.LP
.nf
\fB/usr/lib/lp/postscript/postplot\fR
.fi

.SH DESCRIPTION
.sp
.LP
The
.B postplot
filter translates
.BR plot "(1B) graphics"
\fIfilenames\fR into PostScript and writes the results on the standard
output. If no \fIfilenames\fR are specified, or if \fB\(mi\fR is one of the
input
.IR filenames ,
the standard input is read.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
.BI -c " num"
.ad
.RS 11n
.rt
Print
.I num
copies of each page. By default, only one copy is
printed.
.RE

.sp
.ne 2
.mk
.na
\fB-f\fI name\fR
.ad
.RS 11n
.rt
Print text using font
.IR name .
Any PostScript font can be used, although
the best results will be obtained  only with constant width fonts. The
default font is Courier.
.RE

.sp
.ne 2
.mk
.na
.BI -m " num"
.ad
.RS 11n
.rt
Magnify each logical page by the factor
.IR num .
Pages are scaled
uniformly about the origin which, by default, is located at the center of
each page. The default magnification is 1.0.
.RE

.sp
.ne 2
.mk
.na
.BI -n " num"
.ad
.RS 11n
.rt
Print
.I num
logical pages on each piece of paper, where
.I num
can
be any positive integer. By default,
.I num
is set to 1.
.RE

.sp
.ne 2
.mk
.na
.BI -o " list"
.ad
.RS 11n
.rt
Print pages whose numbers are given in the comma-separated
.IR list .
The
list contains single numbers
.I N
and ranges
.I N1
\(mi\fI N2\fR. A
missing
.I N1
means the lowest numbered page, a missing
.I N2
means
the highest.
.RE

.sp
.ne 2
.mk
.na
.BI -p " mode"
.ad
.RS 11n
.rt
Print \fIfilenames\fR in either portrait or landscape
.IR mode .
Only the
first character of
.I mode
is significant. The default
.I mode
is
landscape.
.RE

.sp
.ne 2
.mk
.na
.BI -w " num"
.ad
.RS 11n
.rt
Set the line width used for graphics to
.I num
points, where a point is
approximately 1/72 of an inch. By default,
.I num
is set to 0 points,
which forces lines to be one pixel wide.
.RE

.sp
.ne 2
.mk
.na
.BI -x " num"
.ad
.RS 11n
.rt
Translate the origin
.I num
inches along the positive x axis. The
default coordinate system has the origin fixed at the center of the page,
.RI "with positive x to the right and positive y up the page. Positive" " num"
moves everything right. The default offset is 0.0 inches.
.RE

.sp
.ne 2
.mk
.na
.BI -y " num"
.ad
.RS 11n
.rt
Translate the origin
.I num
inches along the positive y axis. Positive
\fInum\fR moves everything up the page. The default offset is 0.0.
.RE

.SH OPERANDS
.sp
.LP
The following operand is supported:
.sp
.ne 2
.mk
.na
\fIfilename\fR
.ad
.RS 12n
.rt
The graphics filename to be translated
.RE

.SH EXIT STATUS
.sp
.LP
The following exit value is returned:
.sp
.ne 2
.mk
.na
.B 0
.ad
.RS 5n
.rt
\fIfilename\fR(s) were successfully processed.
.RE

.SH FILES
.sp
.ne 2
.mk
.na
\fB/usr/lib/lp/postscript/forms.ps\fR
.ad
.sp .6
.RS 4n

.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/lp/postscript/postplot.ps
.ad
.sp .6
.RS 4n

.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/lp/postscript/ps.requests
.ad
.sp .6
.RS 4n

.RE

.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i)
lw(2.75i) |lw(2.75i)
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWlps
.TE

.SH SEE ALSO
.sp
.LP
.BR download (1),
.BR dpost (1),
.BR plot (1B),
.BR postdaisy (1),
.BR postdmd (1),
.BR postio (1),
.BR postmd (1),
.BR postprint (1),
.BR postreverse (1),
.BR plot (4B),
.BR attributes (5)
.SH NOTES
.sp
.LP
The default line width is too small for write-white print engines, such as
the one used by the PS-2400.
