'\" te
.\" Copyright (c) 2008, Sun Microsystems, Inc. All Rights Reserved
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH sccs-val 1 "17 Jan 2008" "SunOS 5.11" "User Commands"
.SH NAME
sccs-val, val \- validate an SCCS file
.SH SYNOPSIS
.LP
.nf
\fBval\fR [\fB-s\fR] [\fB-m\fR \fIname\fR] [\fB-r\fIsid\fR] [\fB-y\fR \fItype\fR] \fIs.filename\fR...
.fi

.SH DESCRIPTION
.sp
.LP
The
.B val
utility determines if the specified \fBs.\fRfiles meet the
characteristics specified by the indicated arguments.
.B val
can process
up to 50 files on a single command line.
.sp
.LP
\fBval\fR has a special argument, `\fB\(mi\fR\&', which reads the standard
input until the end-of-file condition is detected. Each line read is
independently processed as if it were a command line argument list.
.sp
.LP
\fBval\fR generates diagnostic messages on the standard output for each
command line and file processed and also returns a single 8\(mibit code upon
exit as described below.
.sp
.LP
The 8-bit code returned by
.B val
is a disjunction of the possible
errors, that is, it can be interpreted as a bit string where (moving from
left to right) the bits set are interpreted as follows:
.sp
.in +2
.nf
bit 0 = missing file argument
bit 1 = unknown or duplicate option
bit 2 = corrupted s.file
bit 3 = can not open file or file not in s.file format
bit 4 = the SCCS delta ID (SID) is invalid or ambiguous
bit 5 = the SID does not exist
bit 6 = mismatch between Y% and -y argument
bit 7 = mismatch between sccs-val.1 and -m argument
.fi
.in -2
.sp

.sp
.LP
\fBval\fR can process two or more files on a given command line, and in
turn can process multiple command lines (when reading the standard input).
.RB "In these cases, an aggregate code is returned which is the logical" " OR"
of the codes generated for each command line and file processed.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
.B -s
.ad
.RS 11n
.rt
Silent.  Suppresses the normal error or warning messages.
.RE

.sp
.ne 2
.mk
.na
\fB-m\fR \fIname\fR
.ad
.RS 11n
.rt
Compares
.I name
with the
.B %M%
ID keyword in the \fBs.\fRfile.
.RE

.sp
.ne 2
.mk
.na
\fB-r\fIsid\fR
.ad
.RS 11n
.rt
Checks to see if the indicated
.B SID
is ambiguous, invalid, or absent
from the \fBs.\fRfile.
.RE

.sp
.ne 2
.mk
.na
\fB-y\fR \fItype\fR
.ad
.RS 11n
.rt
Compares
.I type
with the
.B %Y%
ID keyword.
.RE

.SH ENVIRONMENT VARIABLES
.sp
.LP
See
.BR environ (5)
for descriptions of the following environment
variables that affect the execution of
.BR val :
.BR LANG ,
.BR LC_ALL ,
.BR LC_CTYPE ,
.BR LC_MESSAGES ,
and
.BR NLSPATH .
.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i)
lw(2.75i) |lw(2.75i)
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
_
Interface StabilityCommitted
_
StandardSee \fBstandards\fR(5).
.TE

.SH SEE ALSO
.sp
.LP
.BR sccs (1),
.BR sccs-admin (1),
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-help (1),
.BR what (1),
.BR sccsfile (4),
.BR attributes (5),
.BR environ (5),
.BR standards (5)
.SH DIAGNOSTICS
.sp
.LP
Use the SCCS
.B help
command for explanations (see
.BR sccs-help (1)).
