'\" te
.\" Copyright (c) 2006, Sun Microsystems, Inc. All Rights Reserved
.\" Copyright (c) 2012-2013, J. Schilling
.\" Copyright (c) 2013, Andreas Roehler
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH setfacl 1 "19 Dec 2006" "SunOS 5.11" "User Commands"
.SH NAME
setfacl \- modify the Access Control List (ACL) for a file or files
.SH SYNOPSIS
.LP
.nf
\fBsetfacl\fR [\fB-r\fR] \fB-s\fR \fIacl_entries\fR \fIfile\fR
.fi

.LP
.nf
\fBsetfacl\fR [\fB-r\fR] \fB-md\fR \fIacl_entries\fR \fIfile\fR
.fi

.LP
.nf
\fBsetfacl\fR [\fB-r\fR] \fB-f\fR \fIacl_file\fR \fIfile\fR
.fi

.SH DESCRIPTION
.sp
.LP
For each file specified,
.B setfacl
either replaces its entire
.BR ACL ,
including the default
.B ACL
on a directory, or it adds, modifies, or
deletes one or more
.B ACL
entries, including default entries on
directories.
.sp
.LP
When the
.B setfacl
command is used, it can result in changes to the file
permission bits. When the user
.B ACL
entry for the file owner is changed,
the file owner class permission bits are modified. When the group \fBACL\fR
entry for the file group class is changed, the file group class permission bits
are modified. When the other
.B ACL
entry is changed, the file other class
permission bits are modified.
.sp
.LP
If you use the
.BR chmod (1)
command to change the file group owner
permissions on a file with
.B ACL
entries, both the file group owner
permissions and the
.B ACL
mask are changed to the new permissions. Be aware
that the new
.B ACL
mask permissions can change the effective permissions
for additional users and groups who have
.B ACL
entries on the file.
.sp
.LP
A directory can contain default
.B ACL
entries. If a file or directory is
created in a directory that contains default
.B ACL
entries, the newly
created file has permissions generated according to the intersection of the
default
.B ACL
entries and the permissions requested at creation time. The
.BR umask (1)
are not applied if the directory contains default
.BR ACL
entries. If a default
.B ACL
is specified for a specific user (or users),
the file has a regular
.B ACL
created. Otherwise, only the mode bits are
initialized according to the intersection described above. The default
.B ACL
should be thought of as the maximum discretionary access permissions
that can be granted.
.sp
.LP
Use the
.B setfacl
command to set ACLs on files in a UFS file system, which
supports POSIX-draft ACLS (or
.B aclent_t
.RB "style ACLs). Use the" " chmod"
command to set ACLs on files in a ZFS file system, which supports NFSv4-style
ACLS (or
.B ace_t
style ACLs).
.SS "\fIacl_entries\fR Syntax"
.sp
.LP
For the
.B -m
and
.B -s
options,
.I acl_entries
are one or more
comma-separated
.B ACL
entries.
.sp
.LP
An
.B ACL
entry consists of the following fields separated by colons:
.sp
.ne 2
.mk
.na
.I entry_type
.ad
.RS 14n
.rt
Type of
.B ACL
entry on which to set file permissions. For example,
.I entry_type
can be
.B user
(the owner of a file) or
.B mask
(the
.B ACL
mask).
.RE

.sp
.ne 2
.mk
.na
.I uid
or
.IR gid
.ad
.RS 14n
.rt
User name or user identification number. Or, group name or group
identification number.
.RE

.sp
.ne 2
.mk
.na
.I perms
.ad
.RS 14n
.rt
Represents the permissions that are set on
.IR entry_type .
.I perms
can
be indicated by the symbolic characters
.B rwx
or a number (the same
permissions numbers used with the
.B chmod
command).
.RE

.sp
.LP
The following table shows the valid
.B ACL
entries (default entries can
only be specified for directories):
.sp

.sp
.TS
tab();
cw(2i) cw(3.5i)
lw(2i) lw(3.5i)
.
\fBACL\fR EntryDescription
_
u[ser]::\fIperms\fR File owner permissions.
g[roup]::\fIperms\fR File group owner permissions.
o[ther]:\fIperms\fR T{
Permissions for users other than the file owner or members of file group owner.
T}
m[ask]:\fIperms\fR T{
The \fBACL\fR mask. The mask entry indicates the maximum permissions allowed for users (other than the owner) and for groups. The mask is a quick way to change permissions on all the users and groups.
T}
u[ser]:\fIuid:perms\fRT{
Permissions for a specific user. For \fIuid\fR, you can specify either a user name or a numeric UID.
T}
g[roup]:\fIgid:perms\fRT{
Permissions for a specific group. For \fIgid\fR, you can specify either a group name or a numeric GID.
T}
d[efault]:u[ser]::\fIperms\fR Default file owner permissions.
d[efault]:g[roup]::\fIperms\fR Default file group owner permissions.
d[efault]:o[ther]:\fIperms\fR T{
Default permissions for users other than the file owner or members of the file group owner.
T}
d[efault]:m[ask]:\fIperms\fR Default \fBACL\fR mask.
d[efault]:u[ser]:\fIuid\fR:\fIperms\fRT{
Default permissions for a specific user. For \fIuid\fR, you can specify either a user name or a numeric UID.
T}
d[efault]:g[roup]:\fIgid\fR:\fIperms\fRT{
Default permissions for a specific group. For \fIgid\fR, you can specify either a group name or a numeric GID.
T}
.TE

.sp
.LP
For the
.B -d
option,
.I acl_entries
are one or more comma-separated
.B ACL
entries without permissions. Notice that the entries for file owner,
file group owner,
.B ACL
mask, and others can not be deleted.
.SH OPTIONS
.sp
.LP
The options have the following meaning:
.sp
.ne 2
.mk
.na
.B -d
.I acl_entries
.ad
.RS 18n
.rt
Deletes one or more entries from the file. The entries for the file owner, the
file group owner, and others can not be deleted from the
.BR ACL .
Notice that
deleting an entry does not necessarily have the same effect as removing all
permissions from the entry.
.RE

.sp
.ne 2
.mk
.na
.B -f
.I acl_file
.ad
.RS 18n
.rt
Sets a file's
.B ACL
with the
.B ACL
entries contained in the file named
.IR acl_file .
The same constraints on specified entries hold as with the
.B -s
option. The entries are not required to be in any specific order in
the file. Also, if you specify a dash (\fB-\fR) for
.IR acl_file ,
standard
input is used to set the file's
.BR ACL .
.sp
The character
.B #
in
.I acl_file
can be used to indicate a comment. All
characters, starting with the
.B #
until the end of the line, are ignored.
Notice that if the
.I acl_file
has been created as the output of the
.BR getfacl (1)
command, any effective permissions, which follow a
.BR # ,
are ignored.
.RE

.sp
.ne 2
.mk
.na
.B -m
.I acl_entries
.ad
.RS 18n
.rt
Adds one or more new
.B ACL
entries to the file, and/or modifies one or
more existing
.B ACL
entries on the file. If an entry already exists for a
specified
.I uid
or
.IR gid ,
the specified permissions replace the current
permissions. If an entry does not exist for the specified
.I uid
or
.IR gid ,
an entry is created. When using the
.B -m
option to modify a
default
.BR ACL ,
you must specify a complete default
.B ACL
(user, group,
other, mask, and any additional entries) the first time.
.RE

.sp
.ne 2
.mk
.na
.B -r
.ad
.RS 18n
.rt
Recalculates the permissions for the
.B ACL
mask entry. The permissions
specified in the
.B ACL
mask entry are ignored and replaced by the maximum
permissions necessary to grant the access to all additional user, file group
owner, and additional group entries in the
.BR ACL .
The permissions in the
additional user, file group owner, and additional group entries are left
unchanged.
.RE

.sp
.ne 2
.mk
.na
.B -s
.I acl_entries
.ad
.RS 18n
.rt
Sets a file's
.BR ACL .
All old
.B ACL
entries are removed and replaced
with the newly specified
.BR ACL .
The entries need not be in any specific
order. They are sorted by the command before being applied to the file.
.sp
Required entries:
.RS +4
.TP
.ie t \(bu
.el o
Exactly one
.B user
entry specified for the file owner.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Exactly one
.B group
entry for the file group owner.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Exactly one
.B other
entry specified.
.RE
If there are additional user and group entries:
.RS +4
.TP
.ie t \(bu
.el o
Exactly one
.B mask
entry specified for the
.B ACL
mask that indicates
the maximum permissions allowed for users (other than the owner) and groups.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Must not be duplicate
.B user
entries with the same
.IR uid .
.RE
.RS +4
.TP
.ie t \(bu
.el o
Must not be duplicate
.B group
entries with the same
.IR gid .
.RE
If
.I file
is a directory, the following default
.B ACL
entries can be
specified:
.RS +4
.TP
.ie t \(bu
.el o
Exactly one
.B "default user"
entry for the file owner.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Exactly one
.B "default group"
entry for the file group owner.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Exactly one
.B "default mask"
entry for the
.B ACL
mask.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Exactly one
.B "default other"
entry.
.RE
There can be additional \fBdefault user\fR entries and additional \fBdefault
group\fR entries specified, but there can not be duplicate additional
.B default user
entries with the same
.IR uid ,
or duplicate \fBdefault
group\fR entries with the same
.IR gid .
.RE

.SH EXAMPLES
.LP
.B Example 1
Adding read permission only
.sp
.LP
The following example adds one
.B ACL
entry to file
.BR abc ,
which gives
user
.B shea
read permission only.

.sp
.in +2
.nf
\fBsetfacl -m user:shea:r\(mi\(mi abc\fR
.fi
.in -2
.sp

.LP
.B Example 2
Replacing a file's entire \fBACL\fR
.sp
.LP
The following example replaces the entire
.B ACL
for the file
.BR abc ,
which gives
.B shea
read access, the file owner all access, the file group
owner read access only, the
.B ACL
mask read access only, and others no
access.

.sp
.in +2
.nf
\fBsetfacl -s user:shea:rwx,user::rwx,group::rw-,mask:r--,other:--- abc\fR
.fi
.in -2
.sp

.sp
.LP
Notice that after this command, the file permission bits are
.BR rwxr----- .
Even though the file group owner was set with read/write permissions, the
.B ACL
mask entry limits it to have only read permission. The mask entry
also specifies the maximum permissions available to all additional user and
group
.B ACL
entries. Once again, even though the user
.B shea
was set
.RB "with all access, the mask limits it to have only read permission. The" " ACL"
mask entry is a quick way to limit or open access to all the user and group
entries in an
.BR ACL .
For example, by changing the mask entry to read/write,
both the file group owner and user
.B shea
would be given read/write
access.

.LP
.B Example 3
Setting the same
.B ACL
on two files
.sp
.LP
The following example sets the same
.B ACL
on file
.B abc
as the file
.BR xyz .

.sp
.in +2
.nf
\fBgetfacl xyz | setfacl -f \(mi abc\fR
.fi
.in -2
.sp

.SH FILES
.sp
.ne 2
.mk
.na
.B /etc/passwd
.ad
.RS 15n
.rt
password file
.RE

.sp
.ne 2
.mk
.na
.B /etc/group
.ad
.RS 15n
.rt
group file
.RE

.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i)
lw(2.75i) |lw(2.75i)
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWcsu
.TE

.SH SEE ALSO
.sp
.LP
.BR chmod (1),
.BR getfacl (1),
.BR umask (1),
.BR aclcheck (3SEC),
.BR aclsort (3SEC),
.BR group (4),
.BR passwd (4),
.BR attributes (5)
