'\" te
.\" Copyright (c) 1999, Sun Microsystems, Inc.  All Rights Reserved
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH xgettext 1 "23 Mar 1999" "SunOS 5.11" "User Commands"
.SH NAME
xgettext \- extract gettext call strings from C programs
.SH SYNOPSIS
.LP
.nf
\fBxgettext\fR [\fB-ns\fR] [\fB-a\fR [\fB-x\fR \fIexclude-file\fR]] [\fB-c\fR \fIcomment-tag\fR]
     [\fB-d\fR \fIdefault-domain\fR] [\fB-j\fR] [\fB-m\fR \fIprefix\fR] [\fB-M\fR \fIsuffix\fR]
     [\fB-p\fR \fIpathname\fR] \fB-|\fR \fIfilename\fR...
.fi

.LP
.nf
\fBxgettext\fR \fB-h\fR
.fi

.SH DESCRIPTION
.sp
.LP
The
.B xgettext
utility is used to automate the creation of portable
message files (\fB\&.po\fR). A \fB\&.po\fR file contains copies of "C"
strings that are found in  ANSI C source code in \fIfilename\fR or the
standard input if  `\fB\(mi\fR\&' is specified on the command line. The
\fB\&.po\fR file can be used as input to the
.BR msgfmt (1)
utility, which
produces a binary form of the message file that can be  used by application
during run-time.
.sp
.LP
\fBxgettext\fR writes \fImsgid\fR strings from \fBgettext\fR(3C) calls in
\fIfilename\fR to the default output file
.BR messages.po .
The default
output file name can be changed by
.B -d
option.
.I msgid
strings in
\fBdgettext()\fR calls are written to the output file
\fBdomainname\&.po\fR where \fBdomainname\fR is the first parameter to
the
.B dgettext()
call.
.sp
.LP
By default,
.B xgettext
creates a  \fB\&.po\fR file in the current
working directory, and each entry is in the same order that the strings are
extracted from
.IR filenames .
When the
.B -p
option is specified, the
\fB\&.po\fR file is created in the  \fIpathname\fR directory. An existing
\fB\&.po\fR file is overwritten.
.sp
.LP
Duplicate  \fImsgid\fRs are written to the  \fB\&.po\fR file as comment
lines. When the
.B -s
option is specified, the  \fB\&.po\fR is sorted by
the
.I msgid
string, and all duplicated \fImsgid\fRs are removed. All
\fImsgstr\fR directives in the \fB\&.po\fR file are empty unless the \fB-m\fR
option is used.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
.B -n
.ad
.RS 21n
.rt
Add comment lines to the output file indicating file name and line number in
the source file where each extracted string is encountered. These lines
appear before each
.I msgid
in the following format:
.sp
.in +2
.nf
# # File: \fIfilename\fR, line: \fIline-number\fR
.fi
.in -2
.sp

.RE

.sp
.ne 2
.mk
.na
.B -s
.ad
.RS 21n
.rt
Generate output sorted by  \fImsgid\fRs with all duplicate  \fImsgid\fRs
removed.
.RE

.sp
.ne 2
.mk
.na
.B -a
.ad
.RS 21n
.rt
Extract all strings, not just those found in
.BR gettext (3C),
and
\fBdgettext()\fR () calls. Only one  \fB\&.po\fR file is created.
.RE

.sp
.ne 2
.mk
.na
\fB-c\fR \fIcomment-tag\fR
.ad
.RS 21n
.rt
The comment block beginning with
.I comment-tag
as the first token of the
comment block is added to the output \fB\&.po\fR file as
.I #
delimited
comments. For multiple domains,
.B xgettext
directs comments and messages
to the prevailing text domain.
.RE

.sp
.ne 2
.mk
.na
\fB-d\fR \fIdefault-domain\fR
.ad
.RS 21n
.rt
Rename default output file from
.B messages.po
to \fIdefault-domain\fR
.BR \&.po .
.RE

.sp
.ne 2
.mk
.na
.B -j
.ad
.RS 21n
.rt
Join messages with existing message files.  If a \fB\&.po\fR file does not
exist, it is created.  If a \fB\&.po\fR file does exist, new messages are
appended. Any duplicate \fBmsgid\fRs are commented out in the resulting
\fB\&.po\fR file.  Domain directives in the existing \fB\&.po\fR file are
ignored. Results not guaranteed if the existing message file has been
edited.
.RE

.sp
.ne 2
.mk
.na
\fB-m\fR \fIprefix\fR
.ad
.RS 21n
.rt
Fill in the
.I msgstr
with
.IR prefix .
This is useful for debugging
purposes. To make
.I msgstr
identical to
.IR msgid ,
use an empty string
(\fB""\fR) for \fIprefix\fR.
.RE

.sp
.ne 2
.mk
.na
\fB-M\fR \fIsuffix\fR
.ad
.RS 21n
.rt
Fill in the
.I msgstr
with
.IR suffix .
This is useful for debugging
purposes.
.RE

.sp
.ne 2
.mk
.na
\fB-p\fR \fIpathname\fR
.ad
.RS 21n
.rt
Specify the directory where the output files will be placed. This option
overrides the current working directory.
.RE

.sp
.ne 2
.mk
.na
\fB-x\fR \fIexclude-file\fR
.ad
.RS 21n
.rt
Specify a  \fB\&.po\fR file that contains a list of \fImsgid\fRs that are
not to be extracted from the input files. The format of \fIexclude-file\fR is
identical to the \fB\&.po\fR file. However, only the
.I msgid
directive
line in \fIexclude-file\fR is used. All other lines are simply ignored.  The
\fB-x\fR option can only be used with the \fB-a\fR option.
.RE

.sp
.ne 2
.mk
.na
.B -h
.ad
.RS 21n
.rt
Print a help message on the standard output.
.RE

.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i)
lw(2.75i) |lw(2.75i)
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWloc
.TE

.SH SEE ALSO
.sp
.LP
.BR msgfmt (1),
.BR gettext (3C),
.BR attributes (5)
.SH NOTES
.sp
.LP
\fBxgettext\fR is not able to extract cast strings, for example ANSI C casts
of literal strings to
.BR "(const char *)" .
This is unnecessary anyway, since
the prototypes in
.B <libintl.h>
already specify this type.
.sp
.LP
In messages and translation notes, lines greater than 2048 characters are
truncated to 2048 characters and a warning message is printed to stderr.
