#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2020 Jörg Schilling.  All rights reserved.
#

MANSECT=	3schily

MANFILES=				\
	abspath.3schily			\
	astoi.3schily			\
	astol.3schily			\
	breakline.3schily		\
	cmpbytes.3schily		\
	comerr.3schily			\
	comerrno.3schily		\
	errmsg.3schily			\
	errmsgno.3schily		\
	error.3schily			\
	fdown.3schily			\
	fdup.3schily			\
	fexecl.3schily			\
	fexecle.3schily			\
	fexecv.3schily			\
	fexecve.3schily			\
	fgetline.3schily		\
	file_raise.3schily		\
	fileclose.3schily		\
	fileluopen.3schily		\
	fileopen.3schily		\
	filepos.3schily			\
	fileread.3schily		\
	filereopen.3schily		\
	fileseek.3schily		\
	filesize.3schily		\
	filestat.3schily		\
	filewrite.3schily		\
	findline.3schily		\
	flush.3schily			\
	fnmatch.3schily			\
	format.3schily			\
	fpipe.3schily			\
	fprintf.3schily			\
	getallargs.3schily		\
	getargerror.3schily		\
	getarginit.3schily		\
	getargs.3schily			\
	geterrno.3schily		\
	getfiles.3schily		\
	getline.3schily			\
	handlecond.3schily		\
	movebytes.3schily		\
	ofindline.3schily		\
	patcompile.3schily		\
	patmatch.3schily		\
	peekc.3schily			\
	printf.3schily			\
	raisecond.3schily		\
	resolvepath.3schily		\
	spawnl.3schily			\
	spawnv.3schily			\
	sprintf.3schily			\
	strcatl.3schily			\
	streql.3schily

MANSO=					\
	absfpath.3schily		\
	absnpath.3schily		\
	getlallargs.3schily		\
	getlargs.3schily		\
	getlfiles.3schily		\
	getvallargs.3schily		\
	getvargs.3schily		\
	getvfiles.3schily		\
	resolvefpath.3schily		\
	resolvenpath.3schily		\
	starthandlecond.3schily		\
	unhandlecond.3schily


absfpath.3schily		:= SOFILE = man3schily/abspath.3schily
absnpath.3schily		:= SOFILE = man3schily/abspath.3schily
getlallargs.3schily		:= SOFILE = man3schily/getallargs.3schily
getlargs.3schily		:= SOFILE = man3schily/getargs.3schily
getlfiles.3schily		:= SOFILE = man3schily/getfiles.3schily
getvallargs.3schily		:= SOFILE = man3schily/getallargs.3schily
getvargs.3schily		:= SOFILE = man3schily/getargs.3schily
getvfiles.3schily		:= SOFILE = man3schily/getfiles.3schily
resolvefpath.3schily		:= SOFILE = man3schily/resolvepath.3schily
resolvenpath.3schily		:= SOFILE = man3schily/resolvepath.3schily
starthandlecond.3schily		:= SOFILE = man3schily/handlecond.3schily
unhandlecond.3schily		:= SOFILE = man3schily/handlecond.3schily

include ../Makefile.man

install: $(ROOTMANFILES)
