#! /usr/bin/sh
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2011 Jörg Schilling.  All rights reserved.
#

DRVS="rdsv3"
BD=${BASEDIR:-/}
EX=0

for DRV in $DRVS; do
	if grep -w $DRV $BD/etc/name_to_major > /dev/null 2>&1
	then
		if grep -w clone:$DRV $BD/etc/name_to_major > /dev/null 2>&1
		then
			update_drv -d -b ${BD} clone:$DRV
			if [ $? -ne 0 ]
			then
				EX=1
			fi
		fi
		rem_drv -b ${BD} $DRV
		if [ $? -ne 0 ]
		then
			EX=1
		fi
	fi
done

exit $EX
