#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3head

MANFILES=				\
	acct.h.3head			\
	aio.h.3head			\
	ar.h.3head			\
	archives.h.3head		\
	assert.h.3head			\
	complex.h.3head			\
	cpio.h.3head			\
	dirent.h.3head			\
	errno.h.3head			\
	fcntl.h.3head			\
	fenv.h.3head			\
	float.h.3head			\
	floatingpoint.h.3head		\
	fmtmsg.h.3head			\
	fnmatch.h.3head			\
	ftw.h.3head			\
	glob.h.3head			\
	grp.h.3head			\
	iconv.h.3head			\
	if.h.3head			\
	in.h.3head			\
	inet.h.3head			\
	inttypes.h.3head		\
	ipc.h.3head			\
	iso646.h.3head			\
	langinfo.h.3head		\
	libgen.h.3head			\
	libintl.h.3head			\
	limits.h.3head			\
	locale.h.3head			\
	math.h.3head			\
	mman.h.3head			\
	monetary.h.3head		\
	mqueue.h.3head			\
	msg.h.3head			\
	ndbm.h.3head			\
	netdb.h.3head			\
	nl_types.h.3head		\
	poll.h.3head			\
	pthread.h.3head			\
	pwd.h.3head			\
	regex.h.3head			\
	resource.h.3head		\
	sched.h.3head			\
	search.h.3head			\
	select.h.3head			\
	sem.h.3head			\
	semaphore.h.3head		\
	setjmp.h.3head			\
	shm.h.3head			\
	siginfo.h.3head			\
	signal.h.3head			\
	socket.h.3head			\
	spawn.h.3head			\
	stat.h.3head			\
	statvfs.h.3head			\
	stdbool.h.3head			\
	stddef.h.3head			\
	stdint.h.3head			\
	stdio.h.3head			\
	stdlib.h.3head			\
	string.h.3head			\
	strings.h.3head			\
	stropts.h.3head			\
	syslog.h.3head			\
	tar.h.3head			\
	tcp.h.3head			\
	termios.h.3head			\
	tgmath.h.3head			\
	time.h.3head			\
	timeb.h.3head			\
	times.h.3head			\
	types.h.3head			\
	types32.h.3head			\
	ucontext.h.3head		\
	uio.h.3head			\
	ulimit.h.3head			\
	un.h.3head			\
	unistd.h.3head			\
	utime.h.3head			\
	utmpx.h.3head			\
	utsname.h.3head			\
	values.h.3head			\
	wait.h.3head			\
	wchar.h.3head			\
	wctype.h.3head			\
	wordexp.h.3head

MANSO=					\
	acct.3head			\
	aio.3head			\
	ar.3head			\
	archives.3head			\
	assert.3head			\
	complex.3head			\
	cpio.3head			\
	dirent.3head			\
	errno.3head			\
	fcntl.3head			\
	fenv.3head			\
	float.3head			\
	floatingpoint.3head		\
	fmtmsg.3head			\
	fnmatch.3head			\
	ftw.3head			\
	glob.3head			\
	grp.3head			\
	iconv.3head			\
	if.3head			\
	in.3head			\
	inet.3head			\
	inttypes.3head			\
	ipc.3head			\
	iso646.3head			\
	langinfo.3head			\
	libgen.3head			\
	libintl.3head			\
	limits.3head			\
	locale.3head			\
	math.3head			\
	mman.3head			\
	monetary.3head			\
	mqueue.3head			\
	msg.3head			\
	ndbm.3head			\
	netdb.3head			\
	nl_types.3head			\
	poll.3head			\
	pthread.3head			\
	pwd.3head			\
	regex.3head			\
	resource.3head			\
	sched.3head			\
	search.3head			\
	select.3head			\
	sem.3head			\
	semaphore.3head			\
	setjmp.3head			\
	shm.3head			\
	siginfo.3head			\
	signal.3head			\
	socket.3head			\
	spawn.3head			\
	stat.3head			\
	statvfs.3head			\
	stdbool.3head			\
	stddef.3head			\
	stdint.3head			\
	stdio.3head			\
	stdlib.3head			\
	string.3head			\
	strings.3head			\
	stropts.3head			\
	syslog.3head			\
	tar.3head			\
	tcp.3head			\
	termios.3head			\
	tgmath.3head			\
	time.3head			\
	timeb.3head			\
	times.3head			\
	types.3head			\
	types32.3head			\
	ucontext.3head			\
	uio.3head			\
	ulimit.3head			\
	un.3head			\
	unistd.3head			\
	utime.3head			\
	utmpx.3head			\
	utsname.3head			\
	values.3head			\
	wait.3head			\
	wchar.3head			\
	wctype.3head			\
	wordexp.3head

acct.3head				:= SOFILE = man3head/acct.h.3head
aio.3head				:= SOFILE = man3head/aio.h.3head
ar.3head				:= SOFILE = man3head/ar.h.3head
archives.3head				:= SOFILE = man3head/archives.h.3head
assert.3head				:= SOFILE = man3head/assert.h.3head
complex.3head				:= SOFILE = man3head/complex.h.3head
cpio.3head				:= SOFILE = man3head/cpio.h.3head
dirent.3head				:= SOFILE = man3head/dirent.h.3head
errno.3head				:= SOFILE = man3head/errno.h.3head
fcntl.3head				:= SOFILE = man3head/fcntl.h.3head
fenv.3head				:= SOFILE = man3head/fenv.h.3head
float.3head				:= SOFILE = man3head/float.h.3head
floatingpoint.3head			:= SOFILE = man3head/floatingpoint.h.3head
fmtmsg.3head				:= SOFILE = man3head/fmtmsg.h.3head
fnmatch.3head				:= SOFILE = man3head/fnmatch.h.3head
ftw.3head				:= SOFILE = man3head/ftw.h.3head
glob.3head				:= SOFILE = man3head/glob.h.3head
grp.3head				:= SOFILE = man3head/grp.h.3head
iconv.3head				:= SOFILE = man3head/iconv.h.3head
if.3head				:= SOFILE = man3head/if.h.3head
in.3head				:= SOFILE = man3head/in.h.3head
inet.3head				:= SOFILE = man3head/inet.h.3head
inttypes.3head				:= SOFILE = man3head/inttypes.h.3head
ipc.3head				:= SOFILE = man3head/ipc.h.3head
iso646.3head				:= SOFILE = man3head/iso646.h.3head
langinfo.3head				:= SOFILE = man3head/langinfo.h.3head
libgen.3head				:= SOFILE = man3head/libgen.h.3head
libintl.3head				:= SOFILE = man3head/libintl.h.3head
limits.3head				:= SOFILE = man3head/limits.h.3head
locale.3head				:= SOFILE = man3head/locale.h.3head
math.3head				:= SOFILE = man3head/math.h.3head
mman.3head				:= SOFILE = man3head/mman.h.3head
monetary.3head				:= SOFILE = man3head/monetary.h.3head
mqueue.3head				:= SOFILE = man3head/mqueue.h.3head
msg.3head				:= SOFILE = man3head/msg.h.3head
ndbm.3head				:= SOFILE = man3head/ndbm.h.3head
netdb.3head				:= SOFILE = man3head/netdb.h.3head
nl_types.3head				:= SOFILE = man3head/nl_types.h.3head
poll.3head				:= SOFILE = man3head/poll.h.3head
pthread.3head				:= SOFILE = man3head/pthread.h.3head
pwd.3head				:= SOFILE = man3head/pwd.h.3head
regex.3head				:= SOFILE = man3head/regex.h.3head
resource.3head				:= SOFILE = man3head/resource.h.3head
sched.3head				:= SOFILE = man3head/sched.h.3head
search.3head				:= SOFILE = man3head/search.h.3head
select.3head				:= SOFILE = man3head/select.h.3head
sem.3head				:= SOFILE = man3head/sem.h.3head
semaphore.3head				:= SOFILE = man3head/semaphore.h.3head
setjmp.3head				:= SOFILE = man3head/setjmp.h.3head
shm.3head				:= SOFILE = man3head/shm.h.3head
siginfo.3head				:= SOFILE = man3head/siginfo.h.3head
signal.3head				:= SOFILE = man3head/signal.h.3head
socket.3head				:= SOFILE = man3head/socket.h.3head
spawn.3head				:= SOFILE = man3head/spawn.h.3head
stat.3head				:= SOFILE = man3head/stat.h.3head
statvfs.3head				:= SOFILE = man3head/statvfs.h.3head
stdbool.3head				:= SOFILE = man3head/stdbool.h.3head
stddef.3head				:= SOFILE = man3head/stddef.h.3head
stdint.3head				:= SOFILE = man3head/stdint.h.3head
stdio.3head				:= SOFILE = man3head/stdio.h.3head
stdlib.3head				:= SOFILE = man3head/stdlib.h.3head
string.3head				:= SOFILE = man3head/string.h.3head
strings.3head				:= SOFILE = man3head/strings.h.3head
stropts.3head				:= SOFILE = man3head/stropts.h.3head
syslog.3head				:= SOFILE = man3head/syslog.h.3head
tar.3head				:= SOFILE = man3head/tar.h.3head
tcp.3head				:= SOFILE = man3head/tcp.h.3head
termios.3head				:= SOFILE = man3head/termios.h.3head
tgmath.3head				:= SOFILE = man3head/tgmath.h.3head
time.3head				:= SOFILE = man3head/time.h.3head
timeb.3head				:= SOFILE = man3head/timeb.h.3head
times.3head				:= SOFILE = man3head/times.h.3head
types.3head				:= SOFILE = man3head/types.h.3head
types32.3head				:= SOFILE = man3head/types32.h.3head
ucontext.3head				:= SOFILE = man3head/ucontext.h.3head
uio.3head				:= SOFILE = man3head/uio.h.3head
ulimit.3head				:= SOFILE = man3head/ulimit.h.3head
un.3head				:= SOFILE = man3head/un.h.3head
unistd.3head				:= SOFILE = man3head/unistd.h.3head
utime.3head				:= SOFILE = man3head/utime.h.3head
utmpx.3head				:= SOFILE = man3head/utmpx.h.3head
utsname.3head				:= SOFILE = man3head/utsname.h.3head
values.3head				:= SOFILE = man3head/values.h.3head
wait.3head				:= SOFILE = man3head/wait.h.3head
wchar.3head				:= SOFILE = man3head/wchar.h.3head
wctype.3head				:= SOFILE = man3head/wctype.h.3head
wordexp.3head				:= SOFILE = man3head/wordexp.h.3head

include ../Makefile.man

install: $(ROOTMANFILES)
