'\" te
.\" Copyright (c) 2008, Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright 1989 AT&T
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH filesystem 5 "24 Aug 2009" "SunOS 5.11" "Standards, Environments, and Macros"
.SH NAME
filesystem \- File system organization
.SH SYNOPSIS
.LP
.nf
/
.fi

.LP
.nf
/usr
.fi

.SH DESCRIPTION
.sp
.LP
The file system tree is organized for administrative convenience. Distinct
areas within the file system tree are provided for files that are private to
one machine, files that can be shared by multiple machines of a common
platform, files that can be shared by all machines, and home directories.
This organization allows sharable files to be stored on one machine but
accessed by many machines using a remote file access mechanism such as
.BR NFS .
Grouping together similar files makes the file system tree easier
to upgrade and manage.
.sp
.LP
The file system tree consists of a root file system and a collection of
mountable file systems. The
.BR mount (2)
program attaches mountable file
systems to the file system tree at mount points (directory entries) in the
root file system or other previously mounted file systems. Two file systems,
\fB/\fR (the root) and
.BR /usr ,
must be mounted and
.B /var
must be
accessible to have a functional system. The root file system is mounted
automatically by the kernel at boot time; the
.B /usr
file system is
mounted by the system start-up script, which is run as part of the booting
process.
.B /var
can be mounted as its own file system or be part of
.BR /usr ,
as it is by default.
.sp
.LP
Certain locations, noted below, are approved installation locations for
bundled Foundation Solaris software. In some cases, the approved locations
for bundled software are also approved locations for add-on system software
or for applications. The following descriptions make clear where the two
locations differ. For example,
.B /etc
is the installation location for
platform-dependent configuration files that are bundled with Solaris
software. The analogous location for applications is
\fB/etc/opt/\fIpackagename\fR.
.sp
.LP
In the following descriptions,
.I subsystem
is a category of application
or system software, such as a window system (\fBdt\fR) or a language
(\fBjava1.2\fR)
.sp
.LP
The following descriptions make use of the terms
.BR platform ,
.BR platform-dependent ,
.BR platform-independent ,
and
\fBplatform-specific\fR. Platform refers to a machines Instruction Set
Architecture or processor type, such as is returned by
.BR "uname -i" .
\fBPlatform-dependent\fR refers to a file that is installed on all platforms
and whose contents vary depending on the platform. Like a platform-dependent
file, a \fBplatform-independent\fR file is installed on all platforms.
However, the contents of the latter type remains the same on all platforms.
An example of a platform-dependent file is compiled, executable program. An
example of a platform-independent file is a standard configuration file,
such as
.BR /etc/hosts .
Unlike a platform-dependent or a
platform-independent file, the \fBplatform-specific\fR file is installed
only on a subset of supported platforms. Most platform-specific files are
gathered under \fB/platform\fR and \fB/usr/platform\fR.
.sp
.LP
In the following file or directory descriptions, GNOME stands for GNU
Network Object Model Environment. The GNOME Desktop is shipped with the
Solaris operating system.
.SS "Root File System"
.sp
.LP
The root file system contains files that are unique to each machine. It
contains the following directories:
.sp
.ne 2
.mk
.na
.B /
.ad
.sp .6
.RS 4n
Root of the overall file system name space.
.RE

.sp
.ne 2
.mk
.na
.B /dev
.ad
.sp .6
.RS 4n
Primary location for special files. Typically, device files are built to
match the kernel and hardware configuration of the machine.
.RE

.sp
.ne 2
.mk
.na
\fB/dev/cfg\fR
.ad
.sp .6
.RS 4n
Symbolic links to physical
.BR ap_ids.
.RE

.sp
.ne 2
.mk
.na
.B /dev/cpu
.ad
.sp .6
.RS 4n
Provides configuration and capability information about the processor
type
.RE

.sp
.ne 2
.mk
.na
.B /dev/cua
.ad
.sp .6
.RS 4n
Device files for
.BR uucp .
.RE

.sp
.ne 2
.mk
.na
.B /dev/dsk
.ad
.sp .6
.RS 4n
Block disk devices.
.RE

.sp
.ne 2
.mk
.na
.B /dev/dtrace
.ad
.sp .6
.RS 4n
Pseudo-devices used by the DTrace framework.
.RE

.sp
.ne 2
.mk
.na
.B /dev/dtrace/provider
.ad
.sp .6
.RS 4n
Pseudo-device drivers representing instrumentation providers for the DTrace
framework.
.RE

.sp
.ne 2
.mk
.na
\fB/dev/fbs\fR
.ad
.sp .6
.RS 4n
Frame buffer device files.
.RE

.sp
.ne 2
.mk
.na
\fB/dev/fd\fR
.ad
.sp .6
.RS 4n
File descriptors.
.RE

.sp
.ne 2
.mk
.na
.B /dev/md
.ad
.sp .6
.RS 4n
Logical volume management meta-disk devices.
.RE

.sp
.ne 2
.mk
.na
.B /dev/net
.ad
.sp .6
.RS 4n
Network data-link interface devices.
.RE

.sp
.ne 2
.mk
.na
.B /dev/printers
.ad
.sp .6
.RS 4n
USB printer device files.
.RE

.sp
.ne 2
.mk
.na
.B /dev/pts
.ad
.sp .6
.RS 4n
Pseudo-terminal devices.
.RE

.sp
.ne 2
.mk
.na
.B /dev/rdsk
.ad
.sp .6
.RS 4n
Raw disk devices.
.RE

.sp
.ne 2
.mk
.na
.B /dev/rmt
.ad
.sp .6
.RS 4n
Raw tape devices.
.RE

.sp
.ne 2
.mk
.na
.B /dev/sad
.ad
.sp .6
.RS 4n
Entry points for the
.B STREAMS
Administrative driver.
.RE

.sp
.ne 2
.mk
.na
.B /dev/sound
.ad
.sp .6
.RS 4n
Audio device and audio device control files.
.RE

.sp
.ne 2
.mk
.na
.B /dev/swap
.ad
.sp .6
.RS 4n
Default swap device.
.RE

.sp
.ne 2
.mk
.na
.B /dev/term
.ad
.sp .6
.RS 4n
Terminal devices.
.RE

.sp
.ne 2
.mk
.na
.B /devices
.ad
.sp .6
.RS 4n
Physical device files.
.RE

.sp
.ne 2
.mk
.na
.B /etc
.ad
.sp .6
.RS 4n
Platform-dependent administrative and configuration files and databases
that are not shared among systems.
.B /etc
may be viewed as the directory
that defines the machine's identity. An approved installation location for
bundled Solaris software. The analogous location for add-on system software
or for applications is \fB/etc/opt/\fIpackagename\fR.
.RE

.sp
.ne 2
.mk
.na
.B /etc/X11
.ad
.sp .6
.RS 4n
Xorg Xserver (X11) configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/acct
.ad
.sp .6
.RS 4n
Accounting system configuration information.
.RE

.sp
.ne 2
.mk
.na
.B /etc/apache
.ad
.sp .6
.RS 4n
Apache configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/apoc
.ad
.sp .6
.RS 4n
Files for configuring Sun Java Desktop System Configuration Manager remote
access.
.RE

.sp
.ne 2
.mk
.na
.B /etc/bonobo-activation
.ad
.sp .6
.RS 4n
GNOME XML configuration file for identifying CORBA servers.
.RE

.sp
.ne 2
.mk
.na
.B /etc/cron.d
.ad
.sp .6
.RS 4n
Configuration information for
.BR cron (1M).
.RE

.sp
.ne 2
.mk
.na
.B /etc/dat
.ad
.sp .6
.RS 4n
Contains a list of interface adapters supported by uDAPL service
providers.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/default\fR
.ad
.sp .6
.RS 4n
Defaults information for various programs.
.RE

.sp
.ne 2
.mk
.na
.B /etc/devices
.ad
.sp .6
.RS 4n
Contains device-related data.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/dfs\fR
.ad
.sp .6
.RS 4n
Configuration information for shared file systems.
.RE

.sp
.ne 2
.mk
.na
.B /etc/dhcp
.ad
.sp .6
.RS 4n
Dynamic Host Configuration Protocol (\fBDHCP\fR) configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/dmi
.ad
.sp .6
.RS 4n
Solstice Enterprise Agents configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/dt
.ad
.sp .6
.RS 4n
Desktop configuration files.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/flash\fR
.ad
.sp .6
.RS 4n
Solaris Flash Archive configuration files.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/fm\fR
.ad
.sp .6
.RS 4n
Fault manager configuration files. For more information, see
.BR fmd (1M).
.RE

.sp
.ne 2
.mk
.na
\fB/etc/fonts\fR
.ad
.sp .6
.RS 4n
Font configuration information.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/fs\fR
.ad
.sp .6
.RS 4n
Binaries organized by file system types for operations required before
\fB/usr\fR is mounted.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/ftpd\fR
.ad
.sp .6
.RS 4n
\fBftpd\fR configuration files.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/gconf\fR
.ad
.sp .6
.RS 4n
GConf system configuration (including system defaults and system mandatory
settings)
.RE

.sp
.ne 2
.mk
.na
.B /etc/gimp
.ad
.sp .6
.RS 4n
GNU Image Manipulation Program (GIMP) configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/gnome
.ad
.sp .6
.RS 4n
GNOME Desktop configuration files.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/gnome-vfs-2.0\fR
.ad
.sp .6
.RS 4n
Files for customizing GNOME 2.0 desktop menus.
.RE

.sp
.ne 2
.mk
.na
.B /etc/gnopernicus-1.0
.ad
.sp .6
.RS 4n
Configuration files for GNOME's Gnopernicus, an Assistive Technology (AT)
screen reader.
.RE

.sp
.ne 2
.mk
.na
.B /etc/gss
.ad
.sp .6
.RS 4n
Generic Security Service (\fBGSS\fR) Application Program Interface
configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/gtk
.ad
.sp .6
.RS 4n
GTK+ configuration files
.RE

.sp
.ne 2
.mk
.na
.B /etc/gtk-2.0
.ad
.sp .6
.RS 4n
GTK+ Pixbuf loaders and Input Method modules
.RE

.sp
.ne 2
.mk
.na
.B /etc/imq
.ad
.sp .6
.RS 4n
Sun Java System Message Queue security configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/inet
.ad
.sp .6
.RS 4n
Configuration files for Internet services.
.RE

.sp
.ne 2
.mk
.na
.B /etc/init.d
.ad
.sp .6
.RS 4n
Shell scripts for transitioning between run levels.
.RE

.sp
.ne 2
.mk
.na
.B /etc/krb5
.ad
.sp .6
.RS 4n
Kerberos configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/lib
.ad
.sp .6
.RS 4n
Shared libraries needed during booting.
.RE

.sp
.ne 2
.mk
.na
.B /etc/llc2
.ad
.sp .6
.RS 4n
Logical link control (\fBllc2\fR) driver configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/lp
.ad
.sp .6
.RS 4n
Configuration information for the printer subsystem.
.RE

.sp
.ne 2
.mk
.na
.B /etc/lu
.ad
.sp .6
.RS 4n
Solaris Live Upgrade configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/lvm
.ad
.sp .6
.RS 4n
Solaris Logical Volume Manager configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/mail
.ad
.sp .6
.RS 4n
Mail subsystem configuration.
.RE

.sp
.ne 2
.mk
.na
.B /etc/nca
.ad
.sp .6
.RS 4n
Solaris Network Cache and Accelerator (\fBNCA\fR) configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/net
.ad
.sp .6
.RS 4n
Configuration information for transport independent network services.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/nfs\fR
.ad
.sp .6
.RS 4n
NFS server logging configuration file.
.RE

.sp
.ne 2
.mk
.na
.B /etc/opt
.ad
.sp .6
.RS 4n
Configuration information for optional packages.
.RE

.sp
.ne 2
.mk
.na
.B /etc/pango
.ad
.sp .6
.RS 4n
Pango configuration and module information.
.RE

.sp
.ne 2
.mk
.na
.B /etc/patch
.ad
.sp .6
.RS 4n
Configuration files for patch management.
.RE

.sp
.ne 2
.mk
.na
.B /etc/ppp
.ad
.sp .6
.RS 4n
Solaris
.B PPP
configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/rc0.d
.ad
.sp .6
.RS 4n
Scripts for entering or leaving run level 0. See \fBinit\fR(1M).
.RE

.sp
.ne 2
.mk
.na
.B /etc/rc1.d
.ad
.sp .6
.RS 4n
Scripts for entering or leaving run level 1. See \fBinit\fR(1M).
.RE

.sp
.ne 2
.mk
.na
.B /etc/rc2.d
.ad
.sp .6
.RS 4n
Scripts for entering or leaving run level 2. See \fBinit\fR(1M).
.RE

.sp
.ne 2
.mk
.na
.B /etc/rc3.d
.ad
.sp .6
.RS 4n
Scripts for entering or leaving run level 3. See \fBinit\fR(1M).
.RE

.sp
.ne 2
.mk
.na
.B /etc/rcS.d
.ad
.sp .6
.RS 4n
Scripts for bringing the system up in single user mode.
.RE

.sp
.ne 2
.mk
.na
.B /etc/rcm
.ad
.sp .6
.RS 4n
Directory for reconfiguration manager (RCM) custom scripts.
.RE

.sp
.ne 2
.mk
.na
.B /etc/rpcsec
.ad
.sp .6
.RS 4n
This directory might contain an
.B NIS+
authentication configuration
file.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/saf\fR
.ad
.sp .6
.RS 4n
Service Access Facility files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/sasl
.ad
.sp .6
.RS 4n
Simple Authentication and Security Layer (SASL) server configuration
files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/security
.ad
.sp .6
.RS 4n
Solaris-delivered security configuration files (Audit, RBAC, crypto,
Trusted Extensions).
.RE

.sp
.ne 2
.mk
.na
\fB/etc/sfw\fR
.ad
.sp .6
.RS 4n
Platform-dependent administrative, configuration files and databases for
subsystems from \fB/usr/sfw\fR that are not shared among systems.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/sfw/samba\fR
.ad
.sp .6
.RS 4n
Samba configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/skel
.ad
.sp .6
.RS 4n
Default profile scripts for new user accounts. See \fBuseradd\fR(1M).
.RE

.sp
.ne 2
.mk
.na
.B /etc/sma
.ad
.sp .6
.RS 4n
Systems Management Agent (SMA) configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/smartcard
.ad
.sp .6
.RS 4n
Solaris Smart Card configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/snmp
.ad
.sp .6
.RS 4n
Solstice Enterprise Agents configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/sound
.ad
.sp .6
.RS 4n
Sound Events configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /etc/ssh
.ad
.sp .6
.RS 4n
Secure Shell configuration files. See
.BR ssh (1)
.RE

.sp
.ne 2
.mk
.na
.B /etc/svc
.ad
.sp .6
.RS 4n
SMF service repository.
.RE

.sp
.ne 2
.mk
.na
.B /etc/sysevent
.ad
.sp .6
.RS 4n
\fBsyseventd\fR configuration files.
.RE

.sp
.ne 2
.mk
.na
\fB/etc/\fIsubsystem\fR
.ad
.sp .6
.RS 4n
Platform-dependent
.I subsystem
configuration files that are not shared
among systems. An approved installation location for bundled Solaris
software. The analogous location for add-on system software or for
applications is \fB/etc/opt/\fIpackagename\fR.
.RE

.sp
.ne 2
.mk
.na
.B /etc/tm
.ad
.sp .6
.RS 4n
Trademark files; contents displayed at boot time.
.RE

.sp
.ne 2
.mk
.na
.B /etc/usb
.ad
.sp .6
.RS 4n
\fBUSB\fR configuration information.
.RE

.sp
.ne 2
.mk
.na
.B /etc/uucp
.ad
.sp .6
.RS 4n
\fBUUCP\fR configuration information. See \fBuucp\fR(1C).
.RE

.sp
.ne 2
.mk
.na
.B /etc/xml
.ad
.sp .6
.RS 4n
Extensible Markup Language (XML) catalog.
.RE

.sp
.ne 2
.mk
.na
.B /etc/zones
.ad
.sp .6
.RS 4n
Solaris Zones configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /export
.ad
.sp .6
.RS 4n
Default root of the shared file system tree.
.RE

.sp
.ne 2
.mk
.na
.B /home
.ad
.sp .6
.RS 4n
Default root of a subtree for user directories.
.RE

.sp
.ne 2
.mk
.na
.B /kernel
.ad
.sp .6
.RS 4n
Subtree of platform-dependent loadable kernel modules required as part of
the boot process. It includes the generic part of the core kernel that is
platform-independent,
.BR /kernel/genunix .
See
.BR kernel "(1M) An"
approved installation location for bundled Solaris software and for add-on
system software.
.RE

.sp
.ne 2
.mk
.na
.B /kernel/drv
.ad
.sp .6
.RS 4n
32-bit x86 device drivers.
.RE

.sp
.ne 2
.mk
.na
.B /kernel/drv/sparcv9
.ad
.sp .6
.RS 4n
64-bit
.B SPARC
device drivers.
.RE

.sp
.ne 2
.mk
.na
.B /kernel/drv/amd64
.ad
.sp .6
.RS 4n
64-bit device drivers for 64-bit x86 platforms.
.RE

.sp
.ne 2
.mk
.na
.B /kernel/dtrace
.ad
.sp .6
.RS 4n
Kernel modules representing components in the DTrace framework.
.RE

.sp
.ne 2
.mk
.na
.B /kernel/genunix
.ad
.sp .6
.RS 4n
Platform-independent kernel.
.RE

.sp
.ne 2
.mk
.na
.B /kernel/amd64/genunix
.ad
.sp .6
.RS 4n
64-bit, platform-independent kernel.
.RE

.sp
.ne 2
.mk
.na
\fB/kernel/\fIsubsystem\fR/amd64\fR
.ad
.sp .6
.RS 4n
64-bit x86 platform-dependent modules required for boot. An approved
installation location for bundled Solaris software and for add-on system
software.
.RE

.sp
.ne 2
.mk
.na
\fB/kernel/\fIsubsystem\fR/sparcv9\fR
.ad
.sp .6
.RS 4n
64-bit
.B SPARC
platform-dependent modules required for boot. An
approved installation location for bundled Solaris software and for add-on
system software.
.RE

.sp
.ne 2
.mk
.na
\fB/lib/svc/manifest\fR
.ad
.sp .6
.RS 4n
SMF method scripts. An approved installation location for bundled Solaris
software. The analogous location for add-on system software or for
applications is
.BR /opt/packagename/lib/svc/manifest .
.RE

.sp
.ne 2
.mk
.na
.B /mnt
.ad
.sp .6
.RS 4n
Default temporary mount point for file systems. This is an empty directory
on which file systems can be temporarily mounted.
.RE

.sp
.ne 2
.mk
.na
.B /net
.ad
.sp .6
.RS 4n
Temporary mount point for file systems that are mounted by the
automounter.
.RE

.sp
.ne 2
.mk
.na
.B /opt
.ad
.sp .6
.RS 4n
Root of a subtree for add-on application packages.
.RE

.sp
.ne 2
.mk
.na
\fB/platform\fR
.ad
.sp .6
.RS 4n
Subtree of platform-specific objects which need to reside on the root
filesystem. It contains a series of directories, one per supported platform.
The semantics of the series of directories is equivalent to
.BR /
(root).
.RE

.sp
.ne 2
.mk
.na
\fB/platform/\fB`\fBuname\fR
\fB-i\fB`\fB/kernel\fR
.ad
.sp .6
.RS 4n
Platform-specific modules required for boot. These modules have semantics
equivalent to
.BR /kernel .
It includes the file
.BR unix ,
the core
kernel. See \fBkernel\fR(1M). An approved installation location for bundled
Solaris software and for add-on system software.
.RE

.sp
.ne 2
.mk
.na
\fB/platform/\fB`\fBuname\fR
\fB-m\fB`\fB/kernel\fR
.ad
.sp .6
.RS 4n
Hardware class-specific modules required for boot. An approved installation
location for bundled Solaris software and for add-on system software.
.RE

.sp
.ne 2
.mk
.na
\fB/platform/\fB`\fBuname\fR
\fB-i\fB`\fB/kernel/\fIsubsystem\fR/amd64\fR
.ad
.sp .6
.RS 4n
x86 64-bit, platform-dependent modules required for boot. This is an
approved installation location for bundled Solaris software.
.RE

.sp
.ne 2
.mk
.na
\fB/platform/\fB`\fBuname\fR
\fB-i\fB`\fB/kernel/\fIsubsystem\fR/sparcv9\fR
.ad
.sp .6
.RS 4n
\fBSPARC\fR 64-bit platform-specific modules required for boot. An approved
installation location for bundled Solaris software.
.RE

.sp
.ne 2
.mk
.na
\fB/platform/\fB`\fBuname\fR
\fB-i\fB`\fB/kernel/sparcv9/unix\fR
.ad
.sp .6
.RS 4n
64-bit platform-dependent kernel.
.RE

.sp
.ne 2
.mk
.na
\fB/platform/\fB`\fBuname\fR
\fB-i\fB`\fB/kernel/unix\fR
.ad
.sp .6
.RS 4n
32-bit platform-dependent kernel on i86 and a symlink to \fBsparcv9/unix\fR
on SPARC.
.RE

.sp
.ne 2
.mk
.na
\fB/platform/\fB`\fBuname\fR \fB-i\fB`\fB/lib\fR
.ad
.sp .6
.RS 4n
Platform-specific shared objects required for boot. Semantics are
equivalent to
.BR /lib .
An approved installation location for bundled
Solaris software and for add-on system software.
.RE

.sp
.ne 2
.mk
.na
\fB/platform/\fB`\fBuname\fR \fB-i\fB`\fB/sbin\fR
.ad
.sp .6
.RS 4n
Platform-specific administrative utilities required for boot. Semantics are
equivalent to
.BR /sbin .
An approved installation location for bundled
Solaris software and for add-on system software.
.RE

.sp
.ne 2
.mk
.na
.B /proc
.ad
.sp .6
.RS 4n
Root of a subtree for the process file system.
.RE

.sp
.ne 2
.mk
.na
.B /sbin
.ad
.sp .6
.RS 4n
Essential executables used in the booting process and in manual system
recovery. The full complement of utilities is available only after
\fB/usr\fR is mounted. \fB/sbin\fR is an approved installation location for
bundled Solaris software.
.RE

.sp
.ne 2
.mk
.na
.B /system
.ad
.sp .6
.RS 4n
Mount point for the contract (CTFS) and object (OBJFS) file systems.
.RE

.sp
.ne 2
.mk
.na
.B /tmp
.ad
.sp .6
.RS 4n
Temporary files; cleared during the boot operation.
.RE

.sp
.ne 2
.mk
.na
.B /usr
.ad
.sp .6
.RS 4n
Mount point for the
.B /usr
file system. See description of \fB/usr\fR
file system, below.
.RE

.sp
.ne 2
.mk
.na
.B /var
.ad
.sp .6
.RS 4n
Root of a subtree for varying files. Varying files are files that are
unique to a machine but that can grow to an arbitrary (that is, variable)
size. An example is a log file. An approved installation location for
bundled Solaris software. The analogous location for add-on system software
or for applications is \fB/var/opt/\fIpackagename\fR.
.RE

.sp
.ne 2
.mk
.na
.B /var/adm
.ad
.sp .6
.RS 4n
System logging and accounting files.
.RE

.sp
.ne 2
.mk
.na
.B /var/apache
.ad
.sp .6
.RS 4n
Scripts, icons, logs, and cache pages for Apache web server.
.RE

.sp
.ne 2
.mk
.na
.B /var/appserver
.ad
.sp .6
.RS 4n
Sun Java System Application Server administrative domain files.
.RE

.sp
.ne 2
.mk
.na
.B /var/audit
.ad
.sp .6
.RS 4n
Default location for Solaris Audit log files.
.RE

.sp
.ne 2
.mk
.na
.B /var/cores
.ad
.sp .6
.RS 4n
Directory provided for global core files storage.
.RE

.sp
.ne 2
.mk
.na
.B /var/crash
.ad
.sp .6
.RS 4n
Default depository for kernel crash dumps.
.RE

.sp
.ne 2
.mk
.na
.B /var/cron
.ad
.sp .6
.RS 4n
Log files for
.BR cron (1M).
.RE

.sp
.ne 2
.mk
.na
.B /var/dmi
.ad
.sp .6
.RS 4n
Solstice Enterprise Agents (\fBSEA\fR) Desktop Management Interface
(\fBDMI\fR) run-time components.
.RE

.sp
.ne 2
.mk
.na
.B /var/dt
.ad
.sp .6
.RS 4n
\fBdtlogin\fR configuration files.
.RE

.sp
.ne 2
.mk
.na
\fB/var/fm\fR
.ad
.sp .6
.RS 4n
Fault manager state files. For more information, see \fBfmd\fR(1M).
.RE

.sp
.ne 2
.mk
.na
.B /var/imq
.ad
.sp .6
.RS 4n
Message queue broker instance configuration file.
.RE

.sp
.ne 2
.mk
.na
\fB/var/ftp\fR
.ad
.sp .6
.RS 4n
\fBFTP\fR server directory.
.RE

.sp
.ne 2
.mk
.na
.B /var/inet
.ad
.sp .6
.RS 4n
IPv6 router state files.
.RE

.sp
.ne 2
.mk
.na
.B /var/krb5
.ad
.sp .6
.RS 4n
Database and log files for Kerberos.
.RE

.sp
.ne 2
.mk
.na
.B /var/ld
.ad
.sp .6
.RS 4n
Configuration files for runtime linker.
.RE

.sp
.ne 2
.mk
.na
.B /var/ldap
.ad
.sp .6
.RS 4n
LDAP client configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /var/lib
.ad
.sp .6
.RS 4n
Directory for variable state information.
.RE

.sp
.ne 2
.mk
.na
.B /var/log
.ad
.sp .6
.RS 4n
System log files.
.RE

.sp
.ne 2
.mk
.na
.B /var/lp
.ad
.sp .6
.RS 4n
Line printer subsystem logging information.
.RE

.sp
.ne 2
.mk
.na
.B /var/mail
.ad
.sp .6
.RS 4n
Directory where users' mail is kept.
.RE

.sp
.ne 2
.mk
.na
.B /var/mysql
.ad
.sp .6
.RS 4n
Dynamic database directory for MySQL Database Management System.
.RE

.sp
.ne 2
.mk
.na
.B /var/news
.ad
.sp .6
.RS 4n
Community service messages. This is not the same as USENET-style news.
.RE

.sp
.ne 2
.mk
.na
\fB/var/nfs\fR
.ad
.sp .6
.RS 4n
NFS server log files.
.RE

.sp
.ne 2
.mk
.na
.B /var/nis
.ad
.sp .6
.RS 4n
NIS+ databases.
.RE

.sp
.ne 2
.mk
.na
.B /var/ntp
.ad
.sp .6
.RS 4n
Network Time Protocol (\fBNTP\fR) server state directory.
.RE

.sp
.ne 2
.mk
.na
.B /var/opt
.ad
.sp .6
.RS 4n
Root of a subtree for varying files associated with optional software
packages. An approved installation location for add-on system software and
applications.
.RE

.sp
.ne 2
.mk
.na
.B /var/patchsrv
.ad
.sp .6
.RS 4n
Patch management log files.
.RE

.sp
.ne 2
.mk
.na
.B /var/preserve
.ad
.sp .6
.RS 4n
Backup files for
.BR vi (1)
and
.BR ex (1).
.RE

.sp
.ne 2
.mk
.na
.B /var/run
.ad
.sp .6
.RS 4n
Temporary files which are not needed across reboots. Only root may modify
the contents of this directory.
.RE

.sp
.ne 2
.mk
.na
.B /var/sadm
.ad
.sp .6
.RS 4n
Databases maintained by the software package management utilities.
.RE

.sp
.ne 2
.mk
.na
.B /var/sadm/system/logs
.ad
.sp .6
.RS 4n
Status log files produced by software management functions and/or
applications. For example, log files produced for product installation. An
approved installation location for bundled Solaris software and for add-on
system software and applications.
.RE

.sp
.ne 2
.mk
.na
\fB/var/saf\fR
.ad
.sp .6
.RS 4n
Service access facility logging and accounting files.
.RE

.sp
.ne 2
.mk
.na
.B /var/samba
.ad
.sp .6
.RS 4n
Log and lock files for Samba.
.RE

.sp
.ne 2
.mk
.na
.B /var/sma_snmp
.ad
.sp .6
.RS 4n
Systems Management Agent (SMA) security and MIB component information.
.RE

.sp
.ne 2
.mk
.na
.B /var/snmp
.ad
.sp .6
.RS 4n
SNMP status and configuration information.
.RE

.sp
.ne 2
.mk
.na
.B /var/spool
.ad
.sp .6
.RS 4n
Contains directories for files used in printer spooling, mail delivery,
.BR cron (1M),
.BR at (1),
and so forth.
.RE

.sp
.ne 2
.mk
.na
.B /var/spool/clientmqueue
.ad
.sp .6
.RS 4n
.BR sendmail (1M)
client files.
.RE

.sp
.ne 2
.mk
.na
.B /var/spool/cron
.ad
.sp .6
.RS 4n
.BR cron (1M)
and
.BR at (1)
spooling files.
.RE

.sp
.ne 2
.mk
.na
.B /var/spool/locks
.ad
.sp .6
.RS 4n
Spooling lock files.
.RE

.sp
.ne 2
.mk
.na
.B /var/spool/lp
.ad
.sp .6
.RS 4n
Line printer spool files. See
.BR lp (1).
.RE

.sp
.ne 2
.mk
.na
.B /var/spool/mqueue
.ad
.sp .6
.RS 4n
Mail queued for delivery.
.RE

.sp
.ne 2
.mk
.na
.B /var/spool/pkg
.ad
.sp .6
.RS 4n
Spooled packages.
.RE

.sp
.ne 2
.mk
.na
.B /var/spool/print
.ad
.sp .6
.RS 4n
LP print service client-side request staging area.
.RE

.sp
.ne 2
.mk
.na
.B /var/spool/samba
.ad
.sp .6
.RS 4n
Samba print queue.
.RE

.sp
.ne 2
.mk
.na
.B /var/spool/uucp
.ad
.sp .6
.RS 4n
Queued
.BR uucp "(1C) jobs."
.RE

.sp
.ne 2
.mk
.na
.B /var/spool/uucppublic
.ad
.sp .6
.RS 4n
Files deposited by
.BR uucp (1C).
.RE

.sp
.ne 2
.mk
.na
.B /var/statmon
.ad
.sp .6
.RS 4n
Network status monitor files.
.RE

.sp
.ne 2
.mk
.na
.B /var/svc/log
.ad
.sp .6
.RS 4n
SMF log files.
.RE

.sp
.ne 2
.mk
.na
\fB/var/svc/manifest\fR
.ad
.sp .6
.RS 4n
SMF service manifests. An approved installation location for bundled,
add-on system software and applications.
.RE

.sp
.ne 2
.mk
.na
\fB/var/svc/manifest/site\fR
.ad
.sp .6
.RS 4n
Site-local SMF service manifests.
.RE

.sp
.ne 2
.mk
.na
.B /var/tmp
.ad
.sp .6
.RS 4n
Files that vary in size or presence during normal system operations. This
directory is
.B not
cleared during the boot operation. An approved
installation location for bundled Solaris software and for add-on system
software and applications.
.sp
It is possible to change the default behavior for
.B /var/tmp
to clear
all of the files except editor temporary files by setting the
\fBclean_vartmp\fR property value of the \fBrmtmpfiles\fR service. This is
done with the following commands:
.sp
.in +2
.nf
# \fBsvccfg -s svc:/system/rmtmpfiles setprop \e\fR
      \fBoptions/clean_vartmp = "true"\fR
# \fBsvcadm refresh svc:/system/rmtmpfiles:default\fR
.fi
.in -2
.sp

The \fBsolaris.smf.value.rmtmpfiles\fR authorization is required to modify
this property.
.RE

.sp
.ne 2
.mk
.na
.B /var/uucp
.ad
.sp .6
.RS 4n
.BR uucp (1C)
log and status files.
.RE

.sp
.ne 2
.mk
.na
.B /var/yp
.ad
.sp .6
.RS 4n
Databases needed for backwards compatibility with
.B NIS
and
.BR ypbind (1M);
unnecessary after full transition to
.BR NIS+ .
.RE

.SS "\fB/usr\fR File System"
.sp
.LP
Because it is desirable to keep the root file system small and not
volatile, on disk-based systems larger file systems are often mounted on
.BR /home ,
.BR /opt ,
.BR /usr ,
and
.BR /var .
.sp
.LP
The file system mounted on
.B /usr
contains platform-dependent and
platform-independent sharable files. The subtree rooted at \fB/usr/share\fR
contains platform-independent sharable files; the rest of the \fB/usr\fR
tree contains platform-dependent files. By mounting a common remote file
system, a group of machines with a common platform may share a single
\fB/usr\fR file system. A single \fB/usr/share\fR file system can be shared
by machines of any platform. A machine acting as a file server can share
many different
.B /usr
file systems to support several different
architectures and operating system releases. Clients usually mount
\fB/usr\fR read-only so that they do not accidentally change any shared
files.
.sp
.LP
The
.B /usr
file system contains the following subdirectories:
.sp
.ne 2
.mk
.na
.B /usr/4lib
.ad
.sp .6
.RS 4n
\fBa.out\fR libraries for the Binary Compatibility Package.
.RE

.sp
.ne 2
.mk
.na
.B /usr/5bin
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /usr/bin
directory.
.RE

.sp
.ne 2
.mk
.na
.B /usr/SUNWale
.ad
.sp .6
.RS 4n
Configuration files for Asian Lanuguage Environment (ALE).
.RE

.sp
.ne 2
.mk
.na
.B /usr/X
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /usr/openwin
directory.
.RE

.sp
.ne 2
.mk
.na
.B /usr/X11
.ad
.sp .6
.RS 4n
Xorg Xserver (X11) executables and documentation.
.RE

.sp
.ne 2
.mk
.na
.B /usr/adm
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /var/adm
directory.
.RE

.sp
.ne 2
.mk
.na
.B /usr/apache
.ad
.sp .6
.RS 4n
Apache executables, loadable modules, and documentation.
.RE

.sp
.ne 2
.mk
.na
.B /usr/appserver
.ad
.sp .6
.RS 4n
Sun Java System Application Server software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/benchmarks
.ad
.sp .6
.RS 4n
Directory for benchmarks.
.RE

.sp
.ne 2
.mk
.na
.B /usr/bin
.ad
.sp .6
.RS 4n
Platform-dependent, user-invoked executables. These are commands users
expect to be run as part of their normal
.BR $PATH .
For executables that
are different on a 64-bit system than on a 32-bit system, a wrapper that
selects the appropriate executable is placed here. See
.BR isaexec (3C).
An
approved installation location for bundled Solaris software. The analogous
location for add-on system software or for applications is
\fB/opt/\fIpackagename\fR/bin\fR.
.RE

.sp
.ne 2
.mk
.na
.B /usr/bin/amd64
.ad
.sp .6
.RS 4n
x86 64-bit, platform-dependent, user-invoked executables. This directory
should not be part of a user's
.BR $PATH .
A wrapper in
.BR /usr/bin
should invoke the executable in this directory. See
.BR isaexec (3C).
An
approved installation location for bundled Solaris software. The analogous
location for add-on system software or for applications is
\fB/opt/\fIpackagename\fR/bin/amd64\fR.
.RE

.sp
.ne 2
.mk
.na
.B /usr/bin/sparcv9
.ad
.sp .6
.RS 4n
\fBSPARC\fR platform-dependent, user-invoked executables. This directory
should not be part of a user's
.BR $PATH .
A wrapper in
.BR /usr/bin
should invoke the executable in this directory. See
.BR isaexec (3C).
An
approved installation location for bundled Solaris software. The analogous
location for add-on system software or for applications is
\fB/opt/\fIpackagename\fR/bin/sparcv9\fR.
.RE

.sp
.ne 2
.mk
.na
.B /usr/bin/amd64
.ad
.sp .6
.RS 4n
x86 platform-dependent, user-invoked executables. This directory should not
be part of a user's
.BR $PATH .
A wrapper in
.B /usr/bin
should invoke
the executable in this directory. See
.BR isaexec (3C).
An approved
installation location for bundled Solaris software. The analogous location
for add-on system software or for applications is
\fB/opt/\fIpackagename\fR/bin/amd64\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/bin/\fIsubsystem\fR
.ad
.sp .6
.RS 4n
Platform-dependent user-invoked executables that are associated with
.IR subsystem .
These are commands users expect to be run as part of their
normal
.BR $PATH .
An approved installation location for bundled Solaris
software. The analogous location for add-on system software or for
applications is \fB/opt/\fIpackagename\fR/bin\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/\fIsubsystem\fR/bin\fR
.ad
.sp .6
.RS 4n
Platform-dependent user-invoked executables that are associated with
.IR subsystem .
These are commands users expect to be run as part of their
normal
.BR $PATH .
An approved installation location for bundled Solaris
software. The analogous location for add-on system software or for
applications is \fB/opt/\fIpackagename\fR/bin\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/\fIsubsystem\fR/bin/amd64\fR
.ad
.sp .6
.RS 4n
x86 64-bit, platform-dependent, user-invoked executables. This directory
should not be part of a user's
.BR $PATH .
A wrapper in
.BR /usr/bin
should invoke the executable in this directory. See
.BR isaexec (3C).
An
approved installation location for bundled Solaris software. The analogous
location for add-on system software or for applications is
\fB/opt/\fIpackagename\fR/bin/amd64\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/\fIsubsystem\fR/bin/sparcv9\fR
.ad
.sp .6
.RS 4n
\fBSPARC\fR 64-bit, platform-dependent, user-invoked executables. This
directory should not be part of a user's
.BR $PATH .
A wrapper in
\fB/usr/bin\fR should invoke the executable in this directory. See
.BR isaexec (3C).
An approved installation location for bundled Solaris
software. The analogous location for add-on system software or for
applications is \fB/opt/\fIpackagename\fR/bin/sparcv9\fR.
.RE

.sp
.ne 2
.mk
.na
.B /usr/ccs
.ad
.sp .6
.RS 4n
C compilation system.
.RE

.sp
.ne 2
.mk
.na
.B /usr/ccs/bin
.ad
.sp .6
.RS 4n
C compilation commands and system utilities.
.RE

.sp
.ne 2
.mk
.na
.B /usr/ccs/lib
.ad
.sp .6
.RS 4n
Symbolic link to
.BR /usr/lib .
.RE

.sp
.ne 2
.mk
.na
.B /usr/demo
.ad
.sp .6
.RS 4n
Demo programs and data.
.RE

.sp
.ne 2
.mk
.na
.B /usr/dict
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /usr/share/lib/dict
directory, which contains
the dictionary file used by the
.B UNIX
spell program.
.RE

.sp
.ne 2
.mk
.na
.B /usr/dt
.ad
.sp .6
.RS 4n
root of a subtree for CDE software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/dt/bin
.ad
.sp .6
.RS 4n
Primary location for CDE system utilities.
.RE

.sp
.ne 2
.mk
.na
.B /usr/dt/include
.ad
.sp .6
.RS 4n
Header files for CDE software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/dt/lib
.ad
.sp .6
.RS 4n
Libraries for CDE software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/dt/share/man
.ad
.sp .6
.RS 4n
On-line reference manual pages for CDE software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/games
.ad
.sp .6
.RS 4n
An empty directory, a remnant of the SunOS 4.0/4.1 software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/gnome
.ad
.sp .6
.RS 4n
This is an obsolete directory where 3rd party programs can install their
applications and
.B pixmap
files. It is supported for backwards
compatibility.
.RE

.sp
.ne 2
.mk
.na
.B /usr/include
.ad
.sp .6
.RS 4n
Include headers (for C programs).
.RE

.sp
.ne 2
.mk
.na
.B /usr/j2se
.ad
.sp .6
.RS 4n
Java 2 SDK executables, loadable modules, and documentation.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/java\fI*\fR
.ad
.sp .6
.RS 4n
Directories containing Java programs and libraries.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/jdk\fI*\fR
.ad
.sp .6
.RS 4n
Java Platform virtual machine and core class libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/kernel
.ad
.sp .6
.RS 4n
Subtree of platform-dependent loadable kernel modules, not needed in the
root filesystem. An approved installation location for bundled Solaris
software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/kvm
.ad
.sp .6
.RS 4n
A mount point, retained for backward compatibility, that formerly contained
platform-specific binaries and libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib
.ad
.sp .6
.RS 4n
Platform-dependent libraries, various databases, commands and daemons not
invoked directly by a human user. An approved installation location for
bundled Solaris software. The analogous location for add-on system software
or for applications is \fB/opt/\fIpackagename\fR/lib\fR.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/32
.ad
.sp .6
.RS 4n
Symbolic link to
.BR /usr/lib .
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/64
.ad
.sp .6
.RS 4n
Symbolic link to the most portable 64-bit Solaris interfaces, on both SPARC
and x86 platforms.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/acct
.ad
.sp .6
.RS 4n
Accounting scripts and binaries. See \fBacct\fR(1M).
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/adb
.ad
.sp .6
.RS 4n
\fBadb\fR accounting scripts.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/amd64
.ad
.sp .6
.RS 4n
Platform-dependent libraries, various databases, commands and daemons not
invoked directly by a human user on 64-bit x86. An approved installation
location for bundled Solaris software. The analogous location for add-on
system software or for applications is
\fB/opt/\fIpackagename\fR/lib/amd64\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/autofs\fR
.ad
.sp .6
.RS 4n
Contains the
.B automountd
executable.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/cfgadm\fR
.ad
.sp .6
.RS 4n
Contains \fBcfgadm\fR hardware-specific driver plugins.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/class
.ad
.sp .6
.RS 4n
Scheduling-class-specific directories containing executables for
.BR priocntl (1)
and
.BR dispadmin (1M).
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/crypto
.ad
.sp .6
.RS 4n
Contains the kernel-level cryptographic framework daemon (\fBkcfd\fR).
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/devfsadm\fR
.ad
.sp .6
.RS 4n
Contains
.BR devfsadm ,
the daemon version of
.BR devfsadm .
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/dict
.ad
.sp .6
.RS 4n
Database files for
.BR spell (1).
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/dns
.ad
.sp .6
.RS 4n
Contains DNS resolver libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/dtrace
.ad
.sp .6
.RS 4n
Contains
.B dtrace
D source files.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/flash\fR
.ad
.sp .6
.RS 4n
Contains Solaris flash archive deployment scripts.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/fm\fR
.ad
.sp .6
.RS 4n
Contains
.BR fmd ,
the fault manager daemon and the fault manager
library.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/font\fR
.ad
.sp .6
.RS 4n
\fBtroff\fR(1) font description files.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/fs\fR
.ad
.sp .6
.RS 4n
File system type dependent modules; generally not intended to be invoked
directly by the user.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/gss
.ad
.sp .6
.RS 4n
Secure services-related libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/iconv
.ad
.sp .6
.RS 4n
Conversion tables for
.BR iconv (1).
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/inet
.ad
.sp .6
.RS 4n
Contains many network-related daemons and libraries.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/ipf\fR
.ad
.sp .6
.RS 4n
Contains
.B IPFILTER.LICENCE
and
.BR ipftest .
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/ipqosconf\fR
.ad
.sp .6
.RS 4n
IPQoS configuration utility.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/krb5
.ad
.sp .6
.RS 4n
Contains the Kerberos database propagation program and libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/ld
.ad
.sp .6
.RS 4n
Contains the map files for the
.B ld
link editor.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/ldap
.ad
.sp .6
.RS 4n
Contains LDAP client configuration utilities.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/libp
.ad
.sp .6
.RS 4n
Profiled libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/llc2
.ad
.sp .6
.RS 4n
Contains logical link control (\fBllc2\fR) driver configuration files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/locale
.ad
.sp .6
.RS 4n
Localization databases.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/lp
.ad
.sp .6
.RS 4n
Line printer subsystem databases and back-end executables.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/lu
.ad
.sp .6
.RS 4n
Live Upgrade utilities.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/netsvc
.ad
.sp .6
.RS 4n
Internet network services.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/nfs\fR
.ad
.sp .6
.RS 4n
Auxiliary NFS-related programs and daemons.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/nis
.ad
.sp .6
.RS 4n
Contains NIS+ administrative commands.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/picl
.ad
.sp .6
.RS 4n
Platform Information and Control Library.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/pool
.ad
.sp .6
.RS 4n
Contains the automated resource pools partitioning daemon (\fBpoold\fR) and
associated libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/power
.ad
.sp .6
.RS 4n
Power management daemon,
.BR powerd .
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/print
.ad
.sp .6
.RS 4n
Contains
.B lp
conversion scripts and the
.B in.lpd
daemon.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/rcap
.ad
.sp .6
.RS 4n
Resource cap enforcement daemon,
.BR rcapd .
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/rcm
.ad
.sp .6
.RS 4n
Contains the Reconfiguration and Coordination Manager daemon
(\fBrcm_daemon\fR) and RCM scripts.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/refer\fR
.ad
.sp .6
.RS 4n
Auxiliary programs for
.BR refer (1).
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/rmmount
.ad
.sp .6
.RS 4n
Removable media mounter shared objects.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/sa
.ad
.sp .6
.RS 4n
Scripts and commands for the system activity report package. See
.BR sar (1).
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/saf\fR
.ad
.sp .6
.RS 4n
Auxiliary programs and daemons related to the service access facility.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/sasl
.ad
.sp .6
.RS 4n
Simple Authentication and Security Layer (SASL) plug-in modules.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/secure
.ad
.sp .6
.RS 4n
Default trusted libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/security
.ad
.sp .6
.RS 4n
Solaris security plug-in modules.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/smartcard
.ad
.sp .6
.RS 4n
IFD handler libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/smedia
.ad
.sp .6
.RS 4n
Removable media device server daemon,
.BR rpc.smserverd .
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/sparcv9
.ad
.sp .6
.RS 4n
\fBSPARC\fR 64-bit, platform-dependent libraries, various databases,
commands and daemons not invoked directly by a human user. An approved
installation location for bundled Solaris software. The analogous location
for add-on system software or for applications is
\fB/opt/\fIpackagename\fR/lib/sparcv9\fR.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/spell
.ad
.sp .6
.RS 4n
Auxiliary programs and databases for
.BR spell (1).
This directory is only
present when the Binary Compatibility Package is installed.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/ssh
.ad
.sp .6
.RS 4n
Contains the Secure Shell daemon (\fBsshd\fR) and supporting programs.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/\fIsubsystem\fR
.ad
.sp .6
.RS 4n
Platform-dependent libraries, various databases, commands and daemons that
are associated with
.I subsystem
and that are not invoked directly by a
human user. An approved installation location for bundled Solaris software.
The analogous location for add-on system software or for applications is
\fB/opt/\fIpackagename\fR/lib\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/\fIsubsystem\fR/amd64\fR
.ad
.sp .6
.RS 4n
x86 64-bit, platform-dependent libraries, various databases, commands and
daemons that are associated with
.I subsystem
and that are not invoked
directly by a human user. An approved installation location for bundled
Solaris software. The analogous location for add-on system software or for
applications is \fB/opt/\fIpackagename\fR/lib/amd64\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/lib/\fIsubsystem\fR/sparcv9\fR
.ad
.sp .6
.RS 4n
\fBSPARC\fR 64-bit, platform-dependent libraries, various databases,
commands and daemons that are associated with
.I subsystem
and that are
not invoked directly by a human user. An approved installation location for
bundled Solaris software. The analogous location for add-on system software
or for applications is \fB/opt/\fIpackagename\fR/lib/sparcv9\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/\fIsubsystem\fR/lib\fR
.ad
.sp .6
.RS 4n
Platform-dependent libraries, various databases, commands and daemons not
invoked directly by a human user. An approved installation location for
bundled Solaris software. The analogous location for add-on system software
or for applications is \fB/opt/\fIpackagename\fR/lib\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/\fIsubsystem\fR/lib/amd64\fR
.ad
.sp .6
.RS 4n
x86 64-bit, platform-dependent libraries, various databases, commands and
daemons that are associated with
.I subsystem
and that are not invoked
directly by a human user. An approved installation location for bundled
Solaris software. The analogous location for add-on system software or for
applications is \fB/opt/\fIpackagename\fR/lib/amd64\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/\fIsubsystem\fR/lib/sparcv9\fR
.ad
.sp .6
.RS 4n
\fBSPARC\fR 64-bit, platform-dependent libraries, various databases,
commands and daemons that are associated with
.I subsystem
and that are
not invoked directly by a human user. An approved installation location for
bundled Solaris software. The analogous location for add-on system software
or for applications is \fB/opt/\fIpackagename\fR/lib/sparcv9\fR.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/sysevent
.ad
.sp .6
.RS 4n
Contains the system event notification daemon (\fBsyseventd\fR) and the
\fBsyseventd\fR loadable module (SLM) repository.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/uucp
.ad
.sp .6
.RS 4n
Auxiliary programs and daemons for
.BR uucp (1C).
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/webconsole
.ad
.sp .6
.RS 4n
Sun Java web console programs and scripts.
.RE

.sp
.ne 2
.mk
.na
.B /usr/lib/zones
.ad
.sp .6
.RS 4n
Zone administration daemon
.RB ( zoneamd ).
.RE

.sp
.ne 2
.mk
.na
.B /usr/local
.ad
.sp .6
.RS 4n
Not part of the SVR4-based Solaris distribution. The
.B /usr
directory
is exclusively for software bundled with the Solaris operating system. If
needed for storing machine-local add-on software, create the directory
\fB/opt/local\fR and make \fB/usr/local\fR a symbolic link to
.BR /opt/local .
The
.B /opt
directory or filesystem is for storing
add-on software to the system.
.RE

.sp
.ne 2
.mk
.na
.B /usr/mail
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /var/mail
directory.
.RE

.sp
.ne 2
.mk
.na
.B /usr/man
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /usr/share/man
directory.
.RE

.sp
.ne 2
.mk
.na
.B /usr/net/servers
.ad
.sp .6
.RS 4n
Entry points for foreign name service requests relayed using the network
listener. See \fBlisten\fR(1M).
.RE

.sp
.ne 2
.mk
.na
.B /usr/news
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /var/news
directory.
.RE

.sp
.ne 2
.mk
.na
.B /usr/old
.ad
.sp .6
.RS 4n
Programs that are being phased out.
.RE

.sp
.ne 2
.mk
.na
.B /usr/openwin
.ad
.sp .6
.RS 4n
Installation or mount point for the OpenWindows software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/perl5
.ad
.sp .6
.RS 4n
Perl 5 programs and documentation
.RE

.sp
.ne 2
.mk
.na
\fB/usr/platform\fR
.ad
.sp .6
.RS 4n
Subtree of platform-specific objects which does not need to reside on the
root filesystem. It contains a series of directories, one per supported
platform. The semantics of the series of directories is equivalent to
\fB/platform\fR, except for subdirectories which do not provide utility
under one or the other (for example, \fB/platform/include\fR is not
needed).
.RE

.sp
.ne 2
.mk
.na
\fB/usr/platform/\fB`\fBuname\fR
\fB-i\fB`\fB/include\fR
.ad
.sp .6
.RS 4n
Symbolic link to \fB/../\fB`\fBuname\fR
\fB-i\fB`\fB/include\fR. Platform-specific system (\fBsys\fR,
.BR vm )
header files with semantics equivalent to
.BR /usr/include .
An
approved installation location for bundled Solaris software and for add-on
system software.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/platform/\fB`\fBuname\fR
\fB-i\fB`\fB/lib\fR
.ad
.sp .6
.RS 4n
Platform-specific shared objects with semantics equivalent to
.BR /usr/lib .
An approved installation location for bundled Solaris
software and for add-on system software.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/platform/\fB`\fBuname\fR
\fB-i\fB`\fB/lib/\fIsubsystem\fR/amd64\fR
.ad
.sp .6
.RS 4n
x86 64-bit, platform-specific daemon and shared objects. An approved
installation location for bundled Solaris software and for add-on system
software.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/platform/\fB`\fBuname\fR
\fB-i\fB`\fB/sbin\fR
.ad
.sp .6
.RS 4n
Platform-specific system administration utilities with semantics equivalent
to
.BR /usr/sbin .
An approved installation location for bundled Solaris
software and for add-on system software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/preserve
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /var/preserve
directory.
.RE

.sp
.ne 2
.mk
.na
.B /usr/proc
.ad
.sp .6
.RS 4n
Directory for the
.B proc
tools.
.RE

.sp
.ne 2
.mk
.na
.B /usr/pub
.ad
.sp .6
.RS 4n
Symbolic link to
.BR /share/lib/pub ,
which contains files for online man
page and character processing.
.RE

.sp
.ne 2
.mk
.na
.B /usr/sadm
.ad
.sp .6
.RS 4n
System administration files and directories.
.RE

.sp
.ne 2
.mk
.na
.B /usr/sadm/bin
.ad
.sp .6
.RS 4n
Binaries for the Form and Menu Language Interpreter (\fBFMLI\fR) scripts.
See
.BR fmli (1).
.RE

.sp
.ne 2
.mk
.na
.B /usr/sadm/install
.ad
.sp .6
.RS 4n
Executables and scripts for package management.
.RE

.sp
.ne 2
.mk
.na
.B /usr/sbin
.ad
.sp .6
.RS 4n
Platform-dependent executables for system administration, expected to be
run only by system administrators. An approved installation location for
bundled Solaris software. The analogous location for add-on system software
or for applications is \fB/opt/\fIpackagename\fR/sbin\fR.
.RE

.sp
.ne 2
.mk
.na
.B /usr/sbin/install.d
.ad
.sp .6
.RS 4n
Custom Jumpstart scripts and executables.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/sbin/sparc7\fR and \fBsparc9\fR
.ad
.sp .6
.RS 4n
32-bit and 64-bit versions of commands.
.RE

.sp
.ne 2
.mk
.na
.B /usr/sbin/amd64
.ad
.sp .6
.RS 4n
64-bit x86versions of commands.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/sbin/\fIsubsystem\fR
.ad
.sp .6
.RS 4n
Platform-dependent executables for system administration, expected to be
run only by system administrators, and associated with
.IR subsystem .
An
approved installation location for bundled Solaris software. The analogous
location for add-on system software or for applications is
\fB/opt/\fIpackagename\fR/sbin\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/\fIsubsystem\fR/sbin\fR
.ad
.sp .6
.RS 4n
Platform-dependent executables for system administration, expected to be
run only by system administrators, and associated with
.IR subsystem .
An
approved installation location for bundled Solaris software. The analogous
location for add-on system software or for applications is
\fB/opt/\fIpackagename\fR/sbin\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/sfw\fR
.ad
.sp .6
.RS 4n
\fBGNU\fR and open source executables, libraries, and documentation.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share
.ad
.sp .6
.RS 4n
Platform-independent sharable files. An approved installation location for
bundled Solaris software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/aclocal
.ad
.sp .6
.RS 4n
Open source
.B m4
files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/applications
.ad
.sp .6
.RS 4n
Open source desktop applications files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/audio
.ad
.sp .6
.RS 4n
Sample audio files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/glib-2.0
.ad
.sp .6
.RS 4n
Makefile for
.BR glib .
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/gnome
.ad
.sp .6
.RS 4n
GNOME desktop and application data.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/gtk-2.0
.ad
.sp .6
.RS 4n
GTK+ application data and demos
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/gtk-doc
.ad
.sp .6
.RS 4n
API documentation for libraries which use gtk-doc documentation format,
which mostly includes desktop interfaces.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/icons
.ad
.sp .6
.RS 4n
Sun Java Desktop icons.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/idl
.ad
.sp .6
.RS 4n
Open source Interface Definition Language (IDL) files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/intltool
.ad
.sp .6
.RS 4n
XML translation tools.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/share/ipfilter\fR
.ad
.sp .6
.RS 4n
Open source IP Filter sample files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/javadoc
.ad
.sp .6
.RS 4n
Help files for Message Queue broker and Smart Card applications.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/lib
.ad
.sp .6
.RS 4n
Platform-independent sharable databases. An approved installation location
for bundled Solaris software.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/lib/dict
.ad
.sp .6
.RS 4n
Contains word list for
.BR spell (1).
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/lib/keytables
.ad
.sp .6
.RS 4n
Keyboard layout description tables.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/lib/mailx
.ad
.sp .6
.RS 4n
Help files for
.BR mailx (1).
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/lib/nterm
.ad
.sp .6
.RS 4n
\fBnroff\fR(1) terminal tables.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/lib/pub
.ad
.sp .6
.RS 4n
Character set data files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/lib/tabset
.ad
.sp .6
.RS 4n
Tab setting escape sequences.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/share/lib/terminfo\fR
.ad
.sp .6
.RS 4n
Terminal description files for
.BR terminfo (4).
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/lib/tmac
.ad
.sp .6
.RS 4n
Macro packages and related files for text processing tools, for example,
\fBnroff\fR(1) and \fBtroff\fR(1).
.RE

.sp
.ne 2
.mk
.na
\fB/usr/share/lib/zoneinfo\fR
.ad
.sp .6
.RS 4n
Time zone information.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/man
.ad
.sp .6
.RS 4n
Platform-independent sharable manual pages. An approved installation
location for bundled Solaris software. The analogous location for add-on
system software or for applications is \fB/opt/\fIpackagename\fR/man\fR.
.RE

.sp
.ne 2
.mk
.na
\fB/usr/share/omf\fR
.ad
.sp .6
.RS 4n
GNOME Scrollkeeper database files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/pixmaps
.ad
.sp .6
.RS 4n
Sun Java graphics.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/scrollkeeper
.ad
.sp .6
.RS 4n
GNOME Scrollkeeper templates and
.B xslt
files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/sgml
.ad
.sp .6
.RS 4n
Open source SGML files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/sounds
.ad
.sp .6
.RS 4n
Sound files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/src
.ad
.sp .6
.RS 4n
Source code for kernel, utilities, and libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/themes
.ad
.sp .6
.RS 4n
GNOME 2.0 Desktop themes.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/webconsole
.ad
.sp .6
.RS 4n
Sun Web Console status files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/share/xml
.ad
.sp .6
.RS 4n
GNOME Scrollkeeper DTD files.
.RE

.sp
.ne 2
.mk
.na
.B /usr/snadm
.ad
.sp .6
.RS 4n
Files related to system and network administration.
.RE

.sp
.ne 2
.mk
.na
.B /usr/spool
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /var/spool
directory.
.RE

.sp
.ne 2
.mk
.na
.B /usr/src
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /usr/share/src
directory.
.RE

.sp
.ne 2
.mk
.na
.B /usr/tmp
.ad
.sp .6
.RS 4n
Symbolic link to the
.B /var/tmp
directory.
.RE

.sp
.ne 2
.mk
.na
.B /usr/ucb
.ad
.sp .6
.RS 4n
Berkeley compatibility package binaries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/ucbinclude
.ad
.sp .6
.RS 4n
Berkeley compatibility package headers.
.RE

.sp
.ne 2
.mk
.na
.B /usr/ucblib
.ad
.sp .6
.RS 4n
Berkeley compatibility package libraries.
.RE

.sp
.ne 2
.mk
.na
.B /usr/xpg4
.ad
.sp .6
.RS 4n
Directory for POSIX-compliant utilities.
.RE

.sp
.ne 2
.mk
.na
.B /usr/xpg6
.ad
.sp .6
.RS 4n
Directory for newer versions of POSIX-compliant utilities.
.RE

.SH SEE ALSO
.sp
.LP
.BR at (1),
.BR ex (1),
.BR fmli (1),
.BR iconv (1),
.BR lp (1),
\fBisainfo\fR(1), \fBmail\fR(1),
.BR mailx (1),
.BR nroff (1),
.BR priocntl (1),
.BR refer (1),
.BR sar (1),
.BR sh (1),
.BR spell (1),
.BR svcs (1),
\fBtroff\fR(1), \fBuname\fR(1),
.BR uucp (1C),
.BR vi (1),
.BR acct (1M),
.BR cron (1M),
.BR dispadmin (1M),
.BR dladm (1M),
\fBfmd\fR(1M), \fBfsck\fR(1M),
.BR init (1M),
.BR kernel (1M),
.BR mknod (1M),
.BR mount (1M),
.BR svcadm (1M),
\fBsvccfg\fR(1M), \fBuseradd\fR(1M), \fBypbind\fR(1M),
.BR mount (2),
.BR Intro (4),
.BR terminfo (4)
