'\" te
.\" Copyright (c) 2006, Sun Microsystems, Inc. All Rights Reserved.
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH ieee802.11 5 "28 Nov 2006" "SunOS 5.11" "Standards, Environments, and Macros"
.SH NAME
ieee802.11 \- 802.11 kernel statistics
.SH DESCRIPTION
.sp
.LP
This page describes the kernel statistics that can be used to monitor
attributes specific to the 802.11 physical layer. These statistics can be
retrieved using \fBkstat\fR(1M). Not all 802.11 devices will support all
statistics.
.sp
.ne 2
.mk
.na
\fBtx_frags\fR
.ad
.RS 16n
.rt
Count of data and management fragments transmitted.
.RE

.sp
.ne 2
.mk
.na
\fBrx_frags\fR
.ad
.RS 16n
.rt
Count of data and management fragments received.
.RE

.sp
.ne 2
.mk
.na
\fBrx_dups\fR
.ad
.RS 16n
.rt
Count of duplicate frames received. Duplicates are determined by the
sequence control field.
.RE

.sp
.ne 2
.mk
.na
\fBmcast_tx\fR
.ad
.RS 16n
.rt
Count of broadcast and multicast frames transmitted.
.RE

.sp
.ne 2
.mk
.na
\fBmcast_rx\fR
.ad
.RS 16n
.rt
Count of broadcast and multicast frames received.
.RE

.sp
.ne 2
.mk
.na
\fBtx_failed\fR
.ad
.RS 16n
.rt
Count of frames that could not be transmitted due to the retransmission
limit being reached.
.RE

.sp
.ne 2
.mk
.na
\fBtx_retrans\fR
.ad
.RS 16n
.rt
Count of frames successfully retransmitted after one or more
retransmissions.
.RE

.sp
.ne 2
.mk
.na
\fBtx_reretrans\fR
.ad
.RS 16n
.rt
Count of frames successfully retransmitted after more than one
retransmission.
.RE

.sp
.ne 2
.mk
.na
\fBrts_success\fR
.ad
.RS 16n
.rt
Count of times a \fBCTS\fR was received in response to an \fBRTS\fR.
.RE

.sp
.ne 2
.mk
.na
\fBrts_failure\fR
.ad
.RS 16n
.rt
 Count of times a \fBCTS\fR was not received in response to an \fBRTS\fR.
.RE

.sp
.ne 2
.mk
.na
\fBack_failure\fR
.ad
.RS 16n
.rt
Count of times an \fBACK\fR was expected but was not received.
.RE

.sp
.ne 2
.mk
.na
\fBfcs_errors\fR
.ad
.RS 16n
.rt
Count of frames received with \fBFCS\fR errors.
.RE

.sp
.ne 2
.mk
.na
\fBwep_errors\fR
.ad
.RS 16n
.rt
Count of frames received with the \fBWEP\fR bit set but that either should
not have been encrypted or that were discarded due to \fBWEP\fR not being
supported.
.RE

.SH SEE ALSO
.sp
.LP
\fBkstat\fR(1M)
