'\" te
.\" Copyright (c) 2001, Sun Microsystems, Inc.  All Rights Reserved
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH _lwp_kill 2 "8 Aug 2001" "SunOS 5.11" "System Calls"
.SH NAME
_lwp_kill \- send a signal to a LWP
.SH SYNOPSIS
.LP
.nf
#include <sys/lwp.h>
#include <signal.h>

\fBint\fR \fB_lwp_kill\fR(\fBlwpid_t\fR \fItarget_lwp\fR, \fBint\fR \fIsig\fR);
.fi

.SH DESCRIPTION
.sp
.LP
The
.B _lwp_kill()
function sends a signal to the LWP specified by
.IR target_lwp .
The signal that is to be sent is specified by
.IR sig
and must be one from the list given in \fBsignal.h\fR(3HEAD). If \fIsig\fR
is 0 (the null signal), error checking is performed but no signal is
actually sent. This can be used to check the validity of \fItarget_lwp\fR.
.sp
.LP
The
.I target_lwp
must be an LWP within the same process as the calling
LWP.
.SH RETURN VALUES
.sp
.LP
Upon successful completion,
.B 0
is returned. A non-zero value indicates
an error.
.SH ERRORS
.sp
.LP
If any of the following conditions occur,
.B _lwp_kill()
fails and
returns the corresponding value:
.sp
.ne 2
.mk
.na
.B EINVAL
.ad
.RS 10n
.rt
The
.I sig
argument is not a valid signal number.
.RE

.sp
.ne 2
.mk
.na
.B ESRCH
.ad
.RS 10n
.rt
The
.I target_lwp
argument cannot be found in the current process.
.RE

.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i)
lw(2.75i) |lw(2.75i)
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
MT-LevelAsync-Signal-Safe
.TE

.SH SEE ALSO
.sp
.LP
.BR kill (2),
.BR sigaction (2),
.BR sigprocmask (2),
.BR signal.h (3HEAD),
.BR attributes (5)
