'\" te
.\" Copyright (c) 2008, Sun Microsystems, Inc.  All Rights Reserved.
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH getauid 2 "16 Apr 2008" "SunOS 5.11" "System Calls"
.SH NAME
getauid, setauid \- get or set user audit identity
.SH SYNOPSIS
.LP
.nf
cc [ \fIflag\fR .\|.\|. ] \fIfile\fR .\|.\|. \fB-lbsm\fR \fB -lsocket \fR \fB -lnsl \fR  [ \fIlibrary\fR .\|.\|. ]
#include <sys/param.h>
#include <bsm/libbsm.h>

\fBint\fR \fBgetauid\fR(\fBau_id_t *\fIauid\fR);
.fi

.LP
.nf
\fBint\fR \fBsetauid\fR(\fBau_id_t *\fIauid\fR);
.fi

.SH DESCRIPTION
.sp
.LP
The
.B getauid()
function returns the audit user
.B ID
for the
current process. This value is initially set at login time and inherited by
all child processes. This value does not change when the real/effective user
.B IDs
change, so it can be used to identify the logged-in user even when
running a setuid program. The audit user
.B ID
governs audit decisions
for a process.
.sp
.LP
The
.B setauid()
function sets the audit user
.B ID
for the current
process.
.SH RETURN VALUES
.sp
.LP
Upon successful completion, the
.B getauid()
function returns the audit
user
.B ID
of the current process on success. Otherwise, it returns
\fB\(mi1\fR and sets \fBerrno\fR to indicate the error.
.sp
.LP
Upon successful completion the
.B setauid()
function returns
.BR 0 .
Otherwise, \fB\(mi1\fR is returned and
.B errno
is set to indicate the
error.
.SH ERRORS
.sp
.LP
The
.B getauid()
and
.B setauid()
functions will fail if:
.sp
.ne 2
.mk
.na
.B EFAULT
.ad
.RS 10n
.rt
The
.I auid
argument points to an invalid address.
.RE

.sp
.ne 2
.mk
.na
.B EPERM
.ad
.RS 10n
.rt
The {\fBPRIV_SYS_AUDIT\fR} privilege is not asserted in the effective set
of the calling process.
.RE

.sp
.LP
The
.B getauid()
function will fail if:
.sp
.ne 2
.mk
.na
.B EPERM
.ad
.RS 9n
.rt
The {\fBPRIV_PROC_AUDIT\fR} privilege is not asserted in the effective set
of the calling process.
.RE

.SH USAGE
.sp
.LP
Only a process with appropriate privileges can successfully execute these
calls.
.SH SEE ALSO
.sp
.LP
.BR bsmconv (1M),
.BR audit (2),
.BR getaudit (2),
.BR privileges (5)
.SH NOTES
.sp
.LP
The functionality described on this manual page is available only if the
Solaris Auditing has been enabled.  See \fBbsmconv\fR(1M) for more
information.
.sp
.LP
These functions have been superseded by
.BR getaudit (2)
and
.BR setaudit() .
