#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	7fs

MANFILES=				\
	ctfs.7fs			\
	dcfs.7fs			\
	dev.7fs				\
	devfs.7fs			\
	hsfs.7fs			\
	lofs.7fs			\
	objfs.7fs			\
	pcfs.7fs			\
	sharefs.7fs			\
	smbfs.7fs			\
	tmpfs.7fs			\
	udfs.7fs			\
	ufs.7fs

MANSO=					\

include ../Makefile.man

install: $(ROOTMANFILES)
