#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3plot

MANFILES=				\
	plot.3plot

MANSO=					\
	arc.3plot			\
	box.3plot			\
	circle.3plot			\
	closepl.3plot			\
	closevt.3plot			\
	cont.3plot			\
	erase.3plot			\
	label.3plot			\
	line.3plot			\
	linemod.3plot			\
	move.3plot			\
	openpl.3plot			\
	openvt.3plot			\
	point.3plot			\
	space.3plot

arc.3plot				:= SOFILE = man3plot/plot.3plot
box.3plot				:= SOFILE = man3plot/plot.3plot
circle.3plot				:= SOFILE = man3plot/plot.3plot
closepl.3plot				:= SOFILE = man3plot/plot.3plot
closevt.3plot				:= SOFILE = man3plot/plot.3plot
cont.3plot				:= SOFILE = man3plot/plot.3plot
erase.3plot				:= SOFILE = man3plot/plot.3plot
label.3plot				:= SOFILE = man3plot/plot.3plot
line.3plot				:= SOFILE = man3plot/plot.3plot
linemod.3plot				:= SOFILE = man3plot/plot.3plot
move.3plot				:= SOFILE = man3plot/plot.3plot
openpl.3plot				:= SOFILE = man3plot/plot.3plot
openvt.3plot				:= SOFILE = man3plot/plot.3plot
point.3plot				:= SOFILE = man3plot/plot.3plot
space.3plot				:= SOFILE = man3plot/plot.3plot

include ../Makefile.man

install: $(ROOTMANFILES)
