#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3xcurses

MANFILES=				\
	add_wch.3xcurses		\
	add_wchnstr.3xcurses		\
	addch.3xcurses			\
	addchstr.3xcurses		\
	addnstr.3xcurses		\
	addnwstr.3xcurses		\
	attr_get.3xcurses		\
	attroff.3xcurses		\
	baudrate.3xcurses		\
	beep.3xcurses			\
	bkgd.3xcurses			\
	bkgrnd.3xcurses			\
	border_set.3xcurses		\
	border.3xcurses			\
	can_change_color.3xcurses	\
	cbreak.3xcurses			\
	chgat.3xcurses			\
	clear.3xcurses			\
	clearok.3xcurses		\
	clrtobot.3xcurses		\
	clrtoeol.3xcurses		\
	COLS.3xcurses			\
	copywin.3xcurses		\
	cur_term.3xcurses		\
	curs_set.3xcurses		\
	curscr.3xcurses			\
	curses.3xcurses			\
	def_prog_mode.3xcurses		\
	del_curterm.3xcurses		\
	delay_output.3xcurses		\
	delch.3xcurses			\
	deleteln.3xcurses		\
	delscreen.3xcurses		\
	delwin.3xcurses			\
	derwin.3xcurses			\
	doupdate.3xcurses		\
	dupwin.3xcurses			\
	echo_wchar.3xcurses		\
	echo.3xcurses			\
	echochar.3xcurses		\
	endwin.3xcurses			\
	erasechar.3xcurses		\
	filter.3xcurses			\
	flushinp.3xcurses		\
	get_wch.3xcurses		\
	getbegyx.3xcurses		\
	getcchar.3xcurses		\
	getch.3xcurses			\
	getn_wstr.3xcurses		\
	getnstr.3xcurses		\
	getwin.3xcurses			\
	halfdelay.3xcurses		\
	has_ic.3xcurses			\
	hline_set.3xcurses		\
	hline.3xcurses			\
	idcok.3xcurses			\
	immedok.3xcurses		\
	in_wch.3xcurses			\
	in_wchnstr.3xcurses		\
	inch.3xcurses			\
	inchnstr.3xcurses		\
	initscr.3xcurses		\
	innstr.3xcurses			\
	innwstr.3xcurses		\
	ins_nwstr.3xcurses		\
	ins_wch.3xcurses		\
	insch.3xcurses			\
	insdelln.3xcurses		\
	insertln.3xcurses		\
	insnstr.3xcurses		\
	intrflush.3xcurses		\
	is_linetouched.3xcurses		\
	keyname.3xcurses		\
	keypad.3xcurses			\
	libcurses.3xcurses		\
	LINES.3xcurses			\
	longname.3xcurses		\
	meta.3xcurses			\
	move.3xcurses			\
	mvcur.3xcurses			\
	mvderwin.3xcurses		\
	mvprintw.3xcurses		\
	mvscanw.3xcurses		\
	mvwin.3xcurses			\
	napms.3xcurses			\
	newpad.3xcurses			\
	nl.3xcurses			\
	nodelay.3xcurses		\
	noqiflush.3xcurses		\
	notimeout.3xcurses		\
	overlay.3xcurses		\
	pechochar.3xcurses		\
	putp.3xcurses			\
	redrawwin.3xcurses		\
	resetty.3xcurses		\
	ripoffline.3xcurses		\
	scr_dump.3xcurses		\
	scrl.3xcurses			\
	set_term.3xcurses		\
	setcchar.3xcurses		\
	slk_attroff.3xcurses		\
	standend.3xcurses		\
	stdscr.3xcurses			\
	syncok.3xcurses			\
	termattrs.3xcurses		\
	termname.3xcurses		\
	tgetent.3xcurses		\
	tigetflag.3xcurses		\
	typeahead.3xcurses		\
	unctrl.3xcurses			\
	ungetch.3xcurses		\
	use_env.3xcurses		\
	vidattr.3xcurses		\
	vw_printw.3xcurses		\
	vw_scanw.3xcurses		\
	vwprintw.3xcurses		\
	vwscanw.3xcurses		\
	wunctrl.3xcurses

MANSO=					\
	add_wchstr.3xcurses		\
	addchnstr.3xcurses		\
	addstr.3xcurses			\
	addwstr.3xcurses		\
	attr_off.3xcurses		\
	attr_on.3xcurses		\
	attr_set.3xcurses		\
	attron.3xcurses			\
	attrset.3xcurses		\
	bkgdset.3xcurses		\
	bkgrndset.3xcurses		\
	box_set.3xcurses		\
	box.3xcurses			\
	color_content.3xcurses		\
	COLOR_PAIR.3xcurses		\
	COLOR_PAIRS.3xcurses		\
	color_set.3xcurses		\
	COLORS.3xcurses			\
	def_shell_mode.3xcurses		\
	erase.3xcurses			\
	erasewchar.3xcurses		\
	flash.3xcurses			\
	get_wstr.3xcurses		\
	getbkgd.3xcurses		\
	getbkgrnd.3xcurses		\
	getmaxyx.3xcurses		\
	getparyx.3xcurses		\
	getstr.3xcurses			\
	getyx.3xcurses			\
	has_colors.3xcurses		\
	has_il.3xcurses			\
	idlok.3xcurses			\
	in_wchstr.3xcurses		\
	inchstr.3xcurses		\
	init_color.3xcurses		\
	init_pair.3xcurses		\
	ins_wstr.3xcurses		\
	insstr.3xcurses			\
	instr.3xcurses			\
	inwstr.3xcurses			\
	is_wintouched.3xcurses		\
	isendwin.3xcurses		\
	key_name.3xcurses		\
	killchar.3xcurses		\
	killwchar.3xcurses		\
	leaveok.3xcurses		\
	mvadd_wch.3xcurses		\
	mvadd_wchnstr.3xcurses		\
	mvadd_wchstr.3xcurses		\
	mvaddch.3xcurses		\
	mvaddchnstr.3xcurses		\
	mvaddchstr.3xcurses		\
	mvaddnstr.3xcurses		\
	mvaddnwstr.3xcurses		\
	mvaddstr.3xcurses		\
	mvaddwstr.3xcurses		\
	mvchgat.3xcurses		\
	mvdelch.3xcurses		\
	mvget_wch.3xcurses		\
	mvget_wstr.3xcurses		\
	mvgetch.3xcurses		\
	mvgetn_wstr.3xcurses		\
	mvgetnstr.3xcurses		\
	mvgetstr.3xcurses		\
	mvhline_set.3xcurses		\
	mvhline.3xcurses		\
	mvin_wch.3xcurses		\
	mvin_wchnstr.3xcurses		\
	mvin_wchstr.3xcurses		\
	mvinch.3xcurses			\
	mvinchnstr.3xcurses		\
	mvinchstr.3xcurses		\
	mvinnstr.3xcurses		\
	mvinnwstr.3xcurses		\
	mvins_nwstr.3xcurses		\
	mvins_wch.3xcurses		\
	mvins_wstr.3xcurses		\
	mvinsch.3xcurses		\
	mvinsnstr.3xcurses		\
	mvinsstr.3xcurses		\
	mvinstr.3xcurses		\
	mvinwstr.3xcurses		\
	mvvline_set.3xcurses		\
	mvvline.3xcurses		\
	mvwadd_wch.3xcurses		\
	mvwadd_wchnstr.3xcurses		\
	mvwadd_wchstr.3xcurses		\
	mvwaddch.3xcurses		\
	mvwaddchnstr.3xcurses		\
	mvwaddchstr.3xcurses		\
	mvwaddnstr.3xcurses		\
	mvwaddnwstr.3xcurses		\
	mvwaddstr.3xcurses		\
	mvwaddwstr.3xcurses		\
	mvwchgat.3xcurses		\
	mvwdelch.3xcurses		\
	mvwget_wch.3xcurses		\
	mvwget_wstr.3xcurses		\
	mvwgetch.3xcurses		\
	mvwgetn_wstr.3xcurses		\
	mvwgetnstr.3xcurses		\
	mvwgetstr.3xcurses		\
	mvwhline_set.3xcurses		\
	mvwhline.3xcurses		\
	mvwin_wch.3xcurses		\
	mvwin_wchnstr.3xcurses		\
	mvwin_wchstr.3xcurses		\
	mvwinch.3xcurses		\
	mvwinchnstr.3xcurses		\
	mvwinchstr.3xcurses		\
	mvwinnstr.3xcurses		\
	mvwinnwstr.3xcurses		\
	mvwins_nwstr.3xcurses		\
	mvwins_wch.3xcurses		\
	mvwins_wstr.3xcurses		\
	mvwinsch.3xcurses		\
	mvwinsnstr.3xcurses		\
	mvwinsstr.3xcurses		\
	mvwinstr.3xcurses		\
	mvwinwstr.3xcurses		\
	mvwprintw.3xcurses		\
	mvwscanw.3xcurses		\
	mvwvline_set.3xcurses		\
	mvwvline.3xcurses		\
	newterm.3xcurses		\
	newwin.3xcurses			\
	nocbreak.3xcurses		\
	noecho.3xcurses			\
	nonl.3xcurses			\
	noraw.3xcurses			\
	overwrite.3xcurses		\
	pair_content.3xcurses		\
	PAIR_NUMBER.3xcurses		\
	pecho_wchar.3xcurses		\
	pnoutrefresh.3xcurses		\
	prefresh.3xcurses		\
	printw.3xcurses			\
	putwin.3xcurses			\
	qiflush.3xcurses		\
	raw.3xcurses			\
	refresh.3xcurses		\
	reset_prog_mode.3xcurses	\
	reset_shell_mode.3xcurses	\
	restartterm.3xcurses		\
	savetty.3xcurses		\
	scanw.3xcurses			\
	scr_init.3xcurses		\
	scr_restore.3xcurses		\
	scr_set.3xcurses		\
	scroll.3xcurses			\
	scrollok.3xcurses		\
	set_curterm.3xcurses		\
	setscrreg.3xcurses		\
	setupterm.3xcurses		\
	slk_attr_off.3xcurses		\
	slk_attr_on.3xcurses		\
	slk_attr_set.3xcurses		\
	slk_attron.3xcurses		\
	slk_attrset.3xcurses		\
	slk_clear.3xcurses		\
	slk_color.3xcurses		\
	slk_init.3xcurses		\
	slk_label.3xcurses		\
	slk_noutrefresh.3xcurses	\
	slk_refresh.3xcurses		\
	slk_restore.3xcurses		\
	slk_set.3xcurses		\
	slk_touch.3xcurses		\
	slk_wset.3xcurses		\
	standout.3xcurses		\
	start_color.3xcurses		\
	subpad.3xcurses			\
	subwin.3xcurses			\
	term_attrs.3xcurses		\
	tgetflag.3xcurses		\
	tgetnum.3xcurses		\
	tgetstr.3xcurses		\
	tgoto.3xcurses			\
	tigetnum.3xcurses		\
	tigetstr.3xcurses		\
	timeout.3xcurses		\
	touchline.3xcurses		\
	touchwin.3xcurses		\
	tparm.3xcurses			\
	tputs.3xcurses			\
	unget_wch.3xcurses		\
	untouchwin.3xcurses		\
	vid_attr.3xcurses		\
	vid_puts.3xcurses		\
	vidputs.3xcurses		\
	vline_set.3xcurses		\
	vline.3xcurses			\
	wadd_wch.3xcurses		\
	wadd_wchnstr.3xcurses		\
	wadd_wchstr.3xcurses		\
	waddch.3xcurses			\
	waddchnstr.3xcurses		\
	waddchstr.3xcurses		\
	waddnstr.3xcurses		\
	waddnwstr.3xcurses		\
	waddstr.3xcurses		\
	waddwstr.3xcurses		\
	wattr_get.3xcurses		\
	wattr_off.3xcurses		\
	wattr_on.3xcurses		\
	wattr_set.3xcurses		\
	wattroff.3xcurses		\
	wattron.3xcurses		\
	wattrset.3xcurses		\
	wbkgd.3xcurses			\
	wbkgdset.3xcurses		\
	wbkgrnd.3xcurses		\
	wbkgrndset.3xcurses		\
	wborder_set.3xcurses		\
	wborder.3xcurses		\
	wchgat.3xcurses			\
	wclear.3xcurses			\
	wclrtobot.3xcurses		\
	wclrtoeol.3xcurses		\
	wcolor_set.3xcurses		\
	wcursyncup.3xcurses		\
	wdelch.3xcurses			\
	wdeleteln.3xcurses		\
	wecho_wchar.3xcurses		\
	wechochar.3xcurses		\
	werase.3xcurses			\
	wget_wch.3xcurses		\
	wget_wstr.3xcurses		\
	wgetbkgrnd.3xcurses		\
	wgetch.3xcurses			\
	wgetn_wstr.3xcurses		\
	wgetnstr.3xcurses		\
	wgetstr.3xcurses		\
	whline_set.3xcurses		\
	whline.3xcurses			\
	win_wch.3xcurses		\
	win_wchnstr.3xcurses		\
	win_wchstr.3xcurses		\
	winch.3xcurses			\
	winchnstr.3xcurses		\
	winchstr.3xcurses		\
	winnstr.3xcurses		\
	winnwstr.3xcurses		\
	wins_nwstr.3xcurses		\
	wins_wch.3xcurses		\
	wins_wstr.3xcurses		\
	winsch.3xcurses			\
	winsdelln.3xcurses		\
	winsertln.3xcurses		\
	winsnstr.3xcurses		\
	winsstr.3xcurses		\
	winstr.3xcurses			\
	winwstr.3xcurses		\
	wmove.3xcurses			\
	wnoutrefresh.3xcurses		\
	wprintw.3xcurses		\
	wredrawln.3xcurses		\
	wrefresh.3xcurses		\
	wscanw.3xcurses			\
	wscrl.3xcurses			\
	wsetscrreg.3xcurses		\
	wstandend.3xcurses		\
	wstandout.3xcurses		\
	wsyncdown.3xcurses		\
	wsyncup.3xcurses		\
	wtimeout.3xcurses		\
	wtouchln.3xcurses		\
	wvline_set.3xcurses		\
	wvline.3xcurses

add_wchstr.3xcurses			:= SOFILE = man3xcurses/add_wchnstr.3xcurses
addchnstr.3xcurses			:= SOFILE = man3xcurses/addchstr.3xcurses
addstr.3xcurses				:= SOFILE = man3xcurses/addnstr.3xcurses
addwstr.3xcurses			:= SOFILE = man3xcurses/addnwstr.3xcurses
attr_off.3xcurses			:= SOFILE = man3xcurses/attr_get.3xcurses
attr_on.3xcurses			:= SOFILE = man3xcurses/attr_get.3xcurses
attr_set.3xcurses			:= SOFILE = man3xcurses/attr_get.3xcurses
attron.3xcurses				:= SOFILE = man3xcurses/attroff.3xcurses
attrset.3xcurses			:= SOFILE = man3xcurses/attroff.3xcurses
bkgdset.3xcurses			:= SOFILE = man3xcurses/bkgd.3xcurses
bkgrndset.3xcurses			:= SOFILE = man3xcurses/bkgrnd.3xcurses
box_set.3xcurses			:= SOFILE = man3xcurses/border_set.3xcurses
box.3xcurses				:= SOFILE = man3xcurses/border.3xcurses
color_content.3xcurses			:= SOFILE = man3xcurses/can_change_color.3xcurses
COLOR_PAIR.3xcurses			:= SOFILE = man3xcurses/can_change_color.3xcurses
COLOR_PAIRS.3xcurses			:= SOFILE = man3xcurses/can_change_color.3xcurses
color_set.3xcurses			:= SOFILE = man3xcurses/attr_get.3xcurses
COLORS.3xcurses				:= SOFILE = man3xcurses/can_change_color.3xcurses
def_shell_mode.3xcurses			:= SOFILE = man3xcurses/def_prog_mode.3xcurses
erase.3xcurses				:= SOFILE = man3xcurses/clear.3xcurses
erasewchar.3xcurses			:= SOFILE = man3xcurses/erasechar.3xcurses
flash.3xcurses				:= SOFILE = man3xcurses/beep.3xcurses
get_wstr.3xcurses			:= SOFILE = man3xcurses/getn_wstr.3xcurses
getbkgd.3xcurses			:= SOFILE = man3xcurses/bkgd.3xcurses
getbkgrnd.3xcurses			:= SOFILE = man3xcurses/bkgrnd.3xcurses
getmaxyx.3xcurses			:= SOFILE = man3xcurses/getbegyx.3xcurses
getparyx.3xcurses			:= SOFILE = man3xcurses/getbegyx.3xcurses
getstr.3xcurses				:= SOFILE = man3xcurses/getnstr.3xcurses
getyx.3xcurses				:= SOFILE = man3xcurses/getbegyx.3xcurses
has_colors.3xcurses			:= SOFILE = man3xcurses/can_change_color.3xcurses
has_il.3xcurses				:= SOFILE = man3xcurses/has_ic.3xcurses
idlok.3xcurses				:= SOFILE = man3xcurses/clearok.3xcurses
in_wchstr.3xcurses			:= SOFILE = man3xcurses/in_wchnstr.3xcurses
inchstr.3xcurses			:= SOFILE = man3xcurses/inchnstr.3xcurses
init_color.3xcurses			:= SOFILE = man3xcurses/can_change_color.3xcurses
init_pair.3xcurses			:= SOFILE = man3xcurses/can_change_color.3xcurses
ins_wstr.3xcurses			:= SOFILE = man3xcurses/ins_nwstr.3xcurses
insstr.3xcurses				:= SOFILE = man3xcurses/insnstr.3xcurses
instr.3xcurses				:= SOFILE = man3xcurses/innstr.3xcurses
inwstr.3xcurses				:= SOFILE = man3xcurses/innwstr.3xcurses
is_wintouched.3xcurses			:= SOFILE = man3xcurses/is_linetouched.3xcurses
isendwin.3xcurses			:= SOFILE = man3xcurses/endwin.3xcurses
key_name.3xcurses			:= SOFILE = man3xcurses/keyname.3xcurses
killchar.3xcurses			:= SOFILE = man3xcurses/erasechar.3xcurses
killwchar.3xcurses			:= SOFILE = man3xcurses/erasechar.3xcurses
leaveok.3xcurses			:= SOFILE = man3xcurses/clearok.3xcurses
mvadd_wch.3xcurses			:= SOFILE = man3xcurses/add_wch.3xcurses
mvadd_wchnstr.3xcurses			:= SOFILE = man3xcurses/add_wchnstr.3xcurses
mvadd_wchstr.3xcurses			:= SOFILE = man3xcurses/add_wchnstr.3xcurses
mvaddch.3xcurses			:= SOFILE = man3xcurses/addch.3xcurses
mvaddchnstr.3xcurses			:= SOFILE = man3xcurses/addchstr.3xcurses
mvaddchstr.3xcurses			:= SOFILE = man3xcurses/addchstr.3xcurses
mvaddnstr.3xcurses			:= SOFILE = man3xcurses/addnstr.3xcurses
mvaddnwstr.3xcurses			:= SOFILE = man3xcurses/addnwstr.3xcurses
mvaddstr.3xcurses			:= SOFILE = man3xcurses/addnstr.3xcurses
mvaddwstr.3xcurses			:= SOFILE = man3xcurses/addnwstr.3xcurses
mvchgat.3xcurses			:= SOFILE = man3xcurses/chgat.3xcurses
mvdelch.3xcurses			:= SOFILE = man3xcurses/delch.3xcurses
mvget_wch.3xcurses			:= SOFILE = man3xcurses/get_wch.3xcurses
mvget_wstr.3xcurses			:= SOFILE = man3xcurses/getn_wstr.3xcurses
mvgetch.3xcurses			:= SOFILE = man3xcurses/getch.3xcurses
mvgetn_wstr.3xcurses			:= SOFILE = man3xcurses/getn_wstr.3xcurses
mvgetnstr.3xcurses			:= SOFILE = man3xcurses/getnstr.3xcurses
mvgetstr.3xcurses			:= SOFILE = man3xcurses/getnstr.3xcurses
mvhline_set.3xcurses			:= SOFILE = man3xcurses/hline_set.3xcurses
mvhline.3xcurses			:= SOFILE = man3xcurses/hline.3xcurses
mvin_wch.3xcurses			:= SOFILE = man3xcurses/in_wch.3xcurses
mvin_wchnstr.3xcurses			:= SOFILE = man3xcurses/in_wchnstr.3xcurses
mvin_wchstr.3xcurses			:= SOFILE = man3xcurses/in_wchnstr.3xcurses
mvinch.3xcurses				:= SOFILE = man3xcurses/inch.3xcurses
mvinchnstr.3xcurses			:= SOFILE = man3xcurses/inchnstr.3xcurses
mvinchstr.3xcurses			:= SOFILE = man3xcurses/inchnstr.3xcurses
mvinnstr.3xcurses			:= SOFILE = man3xcurses/innstr.3xcurses
mvinnwstr.3xcurses			:= SOFILE = man3xcurses/innwstr.3xcurses
mvins_nwstr.3xcurses			:= SOFILE = man3xcurses/ins_nwstr.3xcurses
mvins_wch.3xcurses			:= SOFILE = man3xcurses/ins_wch.3xcurses
mvins_wstr.3xcurses			:= SOFILE = man3xcurses/ins_nwstr.3xcurses
mvinsch.3xcurses			:= SOFILE = man3xcurses/insch.3xcurses
mvinsnstr.3xcurses			:= SOFILE = man3xcurses/insnstr.3xcurses
mvinsstr.3xcurses			:= SOFILE = man3xcurses/insnstr.3xcurses
mvinstr.3xcurses			:= SOFILE = man3xcurses/innstr.3xcurses
mvinwstr.3xcurses			:= SOFILE = man3xcurses/innwstr.3xcurses
mvvline_set.3xcurses			:= SOFILE = man3xcurses/hline_set.3xcurses
mvvline.3xcurses			:= SOFILE = man3xcurses/hline.3xcurses
mvwadd_wch.3xcurses			:= SOFILE = man3xcurses/add_wch.3xcurses
mvwadd_wchnstr.3xcurses			:= SOFILE = man3xcurses/add_wchnstr.3xcurses
mvwadd_wchstr.3xcurses			:= SOFILE = man3xcurses/add_wchnstr.3xcurses
mvwaddch.3xcurses			:= SOFILE = man3xcurses/addch.3xcurses
mvwaddchnstr.3xcurses			:= SOFILE = man3xcurses/addchstr.3xcurses
mvwaddchstr.3xcurses			:= SOFILE = man3xcurses/addchstr.3xcurses
mvwaddnstr.3xcurses			:= SOFILE = man3xcurses/addnstr.3xcurses
mvwaddnwstr.3xcurses			:= SOFILE = man3xcurses/addnwstr.3xcurses
mvwaddstr.3xcurses			:= SOFILE = man3xcurses/addnstr.3xcurses
mvwaddwstr.3xcurses			:= SOFILE = man3xcurses/addnwstr.3xcurses
mvwchgat.3xcurses			:= SOFILE = man3xcurses/chgat.3xcurses
mvwdelch.3xcurses			:= SOFILE = man3xcurses/delch.3xcurses
mvwget_wch.3xcurses			:= SOFILE = man3xcurses/get_wch.3xcurses
mvwget_wstr.3xcurses			:= SOFILE = man3xcurses/getn_wstr.3xcurses
mvwgetch.3xcurses			:= SOFILE = man3xcurses/getch.3xcurses
mvwgetn_wstr.3xcurses			:= SOFILE = man3xcurses/getn_wstr.3xcurses
mvwgetnstr.3xcurses			:= SOFILE = man3xcurses/getnstr.3xcurses
mvwgetstr.3xcurses			:= SOFILE = man3xcurses/getnstr.3xcurses
mvwhline_set.3xcurses			:= SOFILE = man3xcurses/hline_set.3xcurses
mvwhline.3xcurses			:= SOFILE = man3xcurses/hline.3xcurses
mvwin_wch.3xcurses			:= SOFILE = man3xcurses/in_wch.3xcurses
mvwin_wchnstr.3xcurses			:= SOFILE = man3xcurses/in_wchnstr.3xcurses
mvwin_wchstr.3xcurses			:= SOFILE = man3xcurses/in_wchnstr.3xcurses
mvwinch.3xcurses			:= SOFILE = man3xcurses/inch.3xcurses
mvwinchnstr.3xcurses			:= SOFILE = man3xcurses/inchnstr.3xcurses
mvwinchstr.3xcurses			:= SOFILE = man3xcurses/inchnstr.3xcurses
mvwinnstr.3xcurses			:= SOFILE = man3xcurses/innstr.3xcurses
mvwinnwstr.3xcurses			:= SOFILE = man3xcurses/innwstr.3xcurses
mvwins_nwstr.3xcurses			:= SOFILE = man3xcurses/ins_nwstr.3xcurses
mvwins_wch.3xcurses			:= SOFILE = man3xcurses/ins_wch.3xcurses
mvwins_wstr.3xcurses			:= SOFILE = man3xcurses/ins_nwstr.3xcurses
mvwinsch.3xcurses			:= SOFILE = man3xcurses/insch.3xcurses
mvwinsnstr.3xcurses			:= SOFILE = man3xcurses/insnstr.3xcurses
mvwinsstr.3xcurses			:= SOFILE = man3xcurses/insnstr.3xcurses
mvwinstr.3xcurses			:= SOFILE = man3xcurses/innstr.3xcurses
mvwinwstr.3xcurses			:= SOFILE = man3xcurses/innwstr.3xcurses
mvwprintw.3xcurses			:= SOFILE = man3xcurses/mvprintw.3xcurses
mvwscanw.3xcurses			:= SOFILE = man3xcurses/mvscanw.3xcurses
mvwvline_set.3xcurses			:= SOFILE = man3xcurses/hline_set.3xcurses
mvwvline.3xcurses			:= SOFILE = man3xcurses/hline.3xcurses
newterm.3xcurses			:= SOFILE = man3xcurses/initscr.3xcurses
newwin.3xcurses				:= SOFILE = man3xcurses/derwin.3xcurses
nocbreak.3xcurses			:= SOFILE = man3xcurses/cbreak.3xcurses
noecho.3xcurses				:= SOFILE = man3xcurses/echo.3xcurses
nonl.3xcurses				:= SOFILE = man3xcurses/nl.3xcurses
noraw.3xcurses				:= SOFILE = man3xcurses/cbreak.3xcurses
overwrite.3xcurses			:= SOFILE = man3xcurses/overlay.3xcurses
pair_content.3xcurses			:= SOFILE = man3xcurses/can_change_color.3xcurses
PAIR_NUMBER.3xcurses			:= SOFILE = man3xcurses/can_change_color.3xcurses
pecho_wchar.3xcurses			:= SOFILE = man3xcurses/pechochar.3xcurses
pnoutrefresh.3xcurses			:= SOFILE = man3xcurses/newpad.3xcurses
prefresh.3xcurses			:= SOFILE = man3xcurses/newpad.3xcurses
printw.3xcurses				:= SOFILE = man3xcurses/mvprintw.3xcurses
putwin.3xcurses				:= SOFILE = man3xcurses/getwin.3xcurses
qiflush.3xcurses			:= SOFILE = man3xcurses/noqiflush.3xcurses
raw.3xcurses				:= SOFILE = man3xcurses/cbreak.3xcurses
refresh.3xcurses			:= SOFILE = man3xcurses/doupdate.3xcurses
reset_prog_mode.3xcurses		:= SOFILE = man3xcurses/def_prog_mode.3xcurses
reset_shell_mode.3xcurses		:= SOFILE = man3xcurses/def_prog_mode.3xcurses
restartterm.3xcurses			:= SOFILE = man3xcurses/del_curterm.3xcurses
savetty.3xcurses			:= SOFILE = man3xcurses/resetty.3xcurses
scanw.3xcurses				:= SOFILE = man3xcurses/mvscanw.3xcurses
scr_init.3xcurses			:= SOFILE = man3xcurses/scr_dump.3xcurses
scr_restore.3xcurses			:= SOFILE = man3xcurses/scr_dump.3xcurses
scr_set.3xcurses			:= SOFILE = man3xcurses/scr_dump.3xcurses
scroll.3xcurses				:= SOFILE = man3xcurses/scrl.3xcurses
scrollok.3xcurses			:= SOFILE = man3xcurses/clearok.3xcurses
set_curterm.3xcurses			:= SOFILE = man3xcurses/del_curterm.3xcurses
setscrreg.3xcurses			:= SOFILE = man3xcurses/clearok.3xcurses
setupterm.3xcurses			:= SOFILE = man3xcurses/del_curterm.3xcurses
slk_attr_off.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_attr_on.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_attr_set.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_attron.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_attrset.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_clear.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_color.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_init.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_label.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_noutrefresh.3xcurses		:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_refresh.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_restore.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_set.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_touch.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
slk_wset.3xcurses			:= SOFILE = man3xcurses/slk_attroff.3xcurses
standout.3xcurses			:= SOFILE = man3xcurses/standend.3xcurses
start_color.3xcurses			:= SOFILE = man3xcurses/can_change_color.3xcurses
subpad.3xcurses				:= SOFILE = man3xcurses/newpad.3xcurses
subwin.3xcurses				:= SOFILE = man3xcurses/derwin.3xcurses
term_attrs.3xcurses			:= SOFILE = man3xcurses/termattrs.3xcurses
tgetflag.3xcurses			:= SOFILE = man3xcurses/tgetent.3xcurses
tgetnum.3xcurses			:= SOFILE = man3xcurses/tgetent.3xcurses
tgetstr.3xcurses			:= SOFILE = man3xcurses/tgetent.3xcurses
tgoto.3xcurses				:= SOFILE = man3xcurses/tgetent.3xcurses
tigetnum.3xcurses			:= SOFILE = man3xcurses/tigetflag.3xcurses
tigetstr.3xcurses			:= SOFILE = man3xcurses/tigetflag.3xcurses
timeout.3xcurses			:= SOFILE = man3xcurses/notimeout.3xcurses
touchline.3xcurses			:= SOFILE = man3xcurses/is_linetouched.3xcurses
touchwin.3xcurses			:= SOFILE = man3xcurses/is_linetouched.3xcurses
tparm.3xcurses				:= SOFILE = man3xcurses/tigetflag.3xcurses
tputs.3xcurses				:= SOFILE = man3xcurses/putp.3xcurses
unget_wch.3xcurses			:= SOFILE = man3xcurses/ungetch.3xcurses
untouchwin.3xcurses			:= SOFILE = man3xcurses/is_linetouched.3xcurses
vid_attr.3xcurses			:= SOFILE = man3xcurses/vidattr.3xcurses
vid_puts.3xcurses			:= SOFILE = man3xcurses/vidattr.3xcurses
vidputs.3xcurses			:= SOFILE = man3xcurses/vidattr.3xcurses
vline_set.3xcurses			:= SOFILE = man3xcurses/hline_set.3xcurses
vline.3xcurses				:= SOFILE = man3xcurses/hline.3xcurses
wadd_wch.3xcurses			:= SOFILE = man3xcurses/add_wch.3xcurses
wadd_wchnstr.3xcurses			:= SOFILE = man3xcurses/add_wchnstr.3xcurses
wadd_wchstr.3xcurses			:= SOFILE = man3xcurses/add_wchnstr.3xcurses
waddch.3xcurses				:= SOFILE = man3xcurses/addch.3xcurses
waddchnstr.3xcurses			:= SOFILE = man3xcurses/addchstr.3xcurses
waddchstr.3xcurses			:= SOFILE = man3xcurses/addchstr.3xcurses
waddnstr.3xcurses			:= SOFILE = man3xcurses/addnstr.3xcurses
waddnwstr.3xcurses			:= SOFILE = man3xcurses/addnwstr.3xcurses
waddstr.3xcurses			:= SOFILE = man3xcurses/addnstr.3xcurses
waddwstr.3xcurses			:= SOFILE = man3xcurses/addnwstr.3xcurses
wattr_get.3xcurses			:= SOFILE = man3xcurses/attr_get.3xcurses
wattr_off.3xcurses			:= SOFILE = man3xcurses/attr_get.3xcurses
wattr_on.3xcurses			:= SOFILE = man3xcurses/attr_get.3xcurses
wattr_set.3xcurses			:= SOFILE = man3xcurses/attr_get.3xcurses
wattroff.3xcurses			:= SOFILE = man3xcurses/attroff.3xcurses
wattron.3xcurses			:= SOFILE = man3xcurses/attroff.3xcurses
wattrset.3xcurses			:= SOFILE = man3xcurses/attroff.3xcurses
wbkgd.3xcurses				:= SOFILE = man3xcurses/bkgd.3xcurses
wbkgdset.3xcurses			:= SOFILE = man3xcurses/bkgd.3xcurses
wbkgrnd.3xcurses			:= SOFILE = man3xcurses/bkgrnd.3xcurses
wbkgrndset.3xcurses			:= SOFILE = man3xcurses/bkgrnd.3xcurses
wborder_set.3xcurses			:= SOFILE = man3xcurses/border_set.3xcurses
wborder.3xcurses			:= SOFILE = man3xcurses/border.3xcurses
wchgat.3xcurses				:= SOFILE = man3xcurses/chgat.3xcurses
wclear.3xcurses				:= SOFILE = man3xcurses/clear.3xcurses
wclrtobot.3xcurses			:= SOFILE = man3xcurses/clrtobot.3xcurses
wclrtoeol.3xcurses			:= SOFILE = man3xcurses/clrtoeol.3xcurses
wcolor_set.3xcurses			:= SOFILE = man3xcurses/attr_get.3xcurses
wcursyncup.3xcurses			:= SOFILE = man3xcurses/syncok.3xcurses
wdelch.3xcurses				:= SOFILE = man3xcurses/delch.3xcurses
wdeleteln.3xcurses			:= SOFILE = man3xcurses/deleteln.3xcurses
wecho_wchar.3xcurses			:= SOFILE = man3xcurses/echo_wchar.3xcurses
wechochar.3xcurses			:= SOFILE = man3xcurses/echochar.3xcurses
werase.3xcurses				:= SOFILE = man3xcurses/clear.3xcurses
wget_wch.3xcurses			:= SOFILE = man3xcurses/get_wch.3xcurses
wget_wstr.3xcurses			:= SOFILE = man3xcurses/getn_wstr.3xcurses
wgetbkgrnd.3xcurses			:= SOFILE = man3xcurses/bkgrnd.3xcurses
wgetch.3xcurses				:= SOFILE = man3xcurses/getch.3xcurses
wgetn_wstr.3xcurses			:= SOFILE = man3xcurses/getn_wstr.3xcurses
wgetnstr.3xcurses			:= SOFILE = man3xcurses/getnstr.3xcurses
wgetstr.3xcurses			:= SOFILE = man3xcurses/getnstr.3xcurses
whline_set.3xcurses			:= SOFILE = man3xcurses/hline_set.3xcurses
whline.3xcurses				:= SOFILE = man3xcurses/hline.3xcurses
win_wch.3xcurses			:= SOFILE = man3xcurses/in_wch.3xcurses
win_wchnstr.3xcurses			:= SOFILE = man3xcurses/in_wchnstr.3xcurses
win_wchstr.3xcurses			:= SOFILE = man3xcurses/in_wchnstr.3xcurses
winch.3xcurses				:= SOFILE = man3xcurses/inch.3xcurses
winchnstr.3xcurses			:= SOFILE = man3xcurses/inchnstr.3xcurses
winchstr.3xcurses			:= SOFILE = man3xcurses/inchnstr.3xcurses
winnstr.3xcurses			:= SOFILE = man3xcurses/innstr.3xcurses
winnwstr.3xcurses			:= SOFILE = man3xcurses/innwstr.3xcurses
wins_nwstr.3xcurses			:= SOFILE = man3xcurses/ins_nwstr.3xcurses
wins_wch.3xcurses			:= SOFILE = man3xcurses/ins_wch.3xcurses
wins_wstr.3xcurses			:= SOFILE = man3xcurses/ins_nwstr.3xcurses
winsch.3xcurses				:= SOFILE = man3xcurses/insch.3xcurses
winsdelln.3xcurses			:= SOFILE = man3xcurses/insdelln.3xcurses
winsertln.3xcurses			:= SOFILE = man3xcurses/insertln.3xcurses
winsnstr.3xcurses			:= SOFILE = man3xcurses/insnstr.3xcurses
winsstr.3xcurses			:= SOFILE = man3xcurses/insnstr.3xcurses
winstr.3xcurses				:= SOFILE = man3xcurses/innstr.3xcurses
winwstr.3xcurses			:= SOFILE = man3xcurses/innwstr.3xcurses
wmove.3xcurses				:= SOFILE = man3xcurses/move.3xcurses
wnoutrefresh.3xcurses			:= SOFILE = man3xcurses/doupdate.3xcurses
wprintw.3xcurses			:= SOFILE = man3xcurses/mvprintw.3xcurses
wredrawln.3xcurses			:= SOFILE = man3xcurses/redrawwin.3xcurses
wrefresh.3xcurses			:= SOFILE = man3xcurses/doupdate.3xcurses
wscanw.3xcurses				:= SOFILE = man3xcurses/mvscanw.3xcurses
wscrl.3xcurses				:= SOFILE = man3xcurses/scrl.3xcurses
wsetscrreg.3xcurses			:= SOFILE = man3xcurses/clearok.3xcurses
wstandend.3xcurses			:= SOFILE = man3xcurses/standend.3xcurses
wstandout.3xcurses			:= SOFILE = man3xcurses/standend.3xcurses
wsyncdown.3xcurses			:= SOFILE = man3xcurses/syncok.3xcurses
wsyncup.3xcurses			:= SOFILE = man3xcurses/syncok.3xcurses
wtimeout.3xcurses			:= SOFILE = man3xcurses/notimeout.3xcurses
wtouchln.3xcurses			:= SOFILE = man3xcurses/is_linetouched.3xcurses
wvline_set.3xcurses			:= SOFILE = man3xcurses/hline_set.3xcurses
wvline.3xcurses				:= SOFILE = man3xcurses/hline.3xcurses

include ../Makefile.man

install: $(ROOTMANFILES)
