#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	7ipp

MANFILES=				\
	dlcosmk.7ipp			\
	dscpmk.7ipp			\
	flowacct.7ipp			\
	ipgpc.7ipp			\
	ipqos.7ipp			\
	tokenmt.7ipp			\
	tswtclmt.7ipp

MANSO=					\

include ../Makefile.man

install: $(ROOTMANFILES)
