#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3stmf

MANFILES=				\
	stmfAddToHostGroup.3stmf	\
	stmfAddToTargetGroup.3stmf	\
	stmfAddViewEntry.3stmf		\
	stmfClearProviderData.3stmf	\
	stmfCreateHostGroup.3stmf	\
	stmfCreateLu.3stmf		\
	stmfCreateLuResource.3stmf	\
	stmfCreateTargetGroup.3stmf	\
	stmfDeleteHostGroup.3stmf	\
	stmfDeleteLu.3stmf		\
	stmfDeleteTargetGroup.3stmf	\
	stmfDestroyProxyDoor.3stmf	\
	stmfDevidFromIscsiName.3stmf	\
	stmfDevidFromWwn.3stmf		\
	stmfFreeLuResource.3stmf	\
	stmfFreeMemory.3stmf		\
	stmfGetAluaState.3stmf		\
	stmfGetHostGroupList.3stmf	\
	stmfGetHostGroupMembers.3stmf	\
	stmfGetLogicalUnitList.3stmf	\
	stmfGetLogicalUnitProperties.3stmf\
	stmfGetLuResource.3stmf		\
	stmfGetPersistMethod.3stmf	\
	stmfGetProviderData.3stmf	\
	stmfGetProviderDataProt.3stmf	\
	stmfGetState.3stmf		\
	stmfGetTargetGroupList.3stmf	\
	stmfGetTargetGroupMembers.3stmf	\
	stmfGetTargetList.3stmf		\
	stmfGetTargetProperties.3stmf	\
	stmfGetViewEntryList.3stmf	\
	stmfImportLu.3stmf		\
	stmfInitProxyDoor.3stmf		\
	stmfLuStandby.3stmf		\
	stmfModifyLu.3stmf		\
	stmfOfflineLogicalUnit.3stmf	\
	stmfOfflineTarget.3stmf		\
	stmfOnlineLogicalUnit.3stmf	\
	stmfOnlineTarget.3stmf		\
	stmfPostProxyMsg.3stmf		\
	stmfRemoveFromHostGroup.3stmf	\
	stmfRemoveFromTargetGroup.3stmf	\
	stmfRemoveViewEntry.3stmf	\
	stmfSetAluaState.3stmf		\
	stmfSetLuProp.3stmf		\
	stmfSetPersistMethod.3stmf	\
	stmfSetProviderData.3stmf	\
	stmfSetProviderDataProt.3stmf	\
	stmfValidateView.3stmf

MANSO=					\
	stmfGetLuProp.3stmf		\
	stmfModifyLuByFname.3stmf

stmfGetLuProp.3stmf			:= SOFILE = man3stmf/stmfSetLuProp.3stmf
stmfModifyLuByFname.3stmf		:= SOFILE = man3stmf/stmfModifyLu.3stmf

include ../Makefile.man

install: $(ROOTMANFILES)
