#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3xtsol

MANFILES=				\
	XTSOLgetClientAttributes.3xtsol	\
	XTSOLgetPropAttributes.3xtsol	\
	XTSOLgetPropLabel.3xtsol	\
	XTSOLgetPropUID.3xtsol		\
	XTSOLgetResAttributes.3xtsol	\
	XTSOLgetResLabel.3xtsol		\
	XTSOLgetResUID.3xtsol		\
	XTSOLgetSSHeight.3xtsol		\
	XTSOLgetWorkstationOwner.3xtsol	\
	XTSOLIsWindowTrusted.3xtsol	\
	XTSOLMakeTPWindow.3xtsol	\
	XTSOLsetPolyInstInfo.3xtsol	\
	XTSOLsetPropLabel.3xtsol	\
	XTSOLsetPropUID.3xtsol		\
	XTSOLsetResLabel.3xtsol		\
	XTSOLsetResUID.3xtsol		\
	XTSOLsetSessionHI.3xtsol	\
	XTSOLsetSessionLO.3xtsol	\
	XTSOLsetSSHeight.3xtsol		\
	XTSOLsetWorkstationOwner.3xtsol

MANSO=					\

include ../Makefile.man

install: $(ROOTMANFILES)
