#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	7d

MANFILES=				\
	aac.7d				\
	afe.7d				\
	ahci.7d				\
	amd8111s.7d			\
	amr.7d				\
	arcmsr.7d			\
	arn.7d				\
	asy.7d				\
	ata.7d				\
	atge.7d				\
	ath.7d				\
	atu.7d				\
	audio.7d			\
	audio1575.7d			\
	audio810.7d			\
	audiocmi.7d			\
	audiocs.7d			\
	audioemu10k.7d			\
	audioens.7d			\
	audiohd.7d			\
	audioixp.7d			\
	audiols.7d			\
	audiop16x.7d			\
	audiopci.7d			\
	audiosolo.7d			\
	audiots.7d			\
	audiovia823x.7d			\
	audiovia97.7d			\
	av1394.7d			\
	bbc_beep.7d			\
	bcm_sata.7d			\
	bfe.7d				\
	bge.7d				\
	blk2scsa.7d			\
	bpp.7d				\
	bscv.7d				\
	cgsix.7d			\
	chxge.7d			\
	cmdk.7d				\
	console.7d			\
	cpuid.7d			\
	ctsmc.7d			\
	cvc.7d				\
	cvcredir.7d			\
	dad.7d				\
	dca.7d				\
	dcam1394.7d			\
	dda.7d				\
	devinfo.7d			\
	dm2s.7d				\
	dmd.7d				\
	dmfe.7d				\
	dnet.7d				\
	dpt.7d				\
	dr.7d				\
	dtrace.7d			\
	ecpp.7d				\
	ehci.7d				\
	eri.7d				\
	esp.7d				\
	fas.7d				\
	fasttrap.7d			\
	fbt.7d				\
	fcip.7d				\
	fcoe.7d				\
	fcoei.7d			\
	fcoet.7d			\
	fcp.7d				\
	fctl.7d				\
	fd.7d				\
	fp.7d				\
	gld.7d				\
	gpio_87317.7d			\
	grbeep.7d			\
	hci1394.7d			\
	heci.7d				\
	hermon.7d			\
	hid.7d				\
	hme.7d				\
	hubd.7d				\
	hwahc.7d			\
	hwarc.7d			\
	hxge.7d				\
	i915.7d				\
	ib.7d				\
	ibcm.7d				\
	ibd.7d				\
	ibdm.7d				\
	ibdma.7d			\
	ibtl.7d				\
	idn.7d				\
	ieee1394.7d			\
	igb.7d				\
	ii.7d				\
	ipnet.7d			\
	ipw.7d				\
	iscsi.7d			\
	iser.7d				\
	iwh.7d				\
	iwi.7d				\
	ixgbe.7d			\
	kfb.7d				\
	kmdb.7d				\
	kstat.7d			\
	ksyms.7d			\
	llc1.7d				\
	lockstat.7d			\
	lofi.7d				\
	log.7d				\
	lp.7d				\
	lx_systrace.7d			\
	mc-opl.7d			\
	md.7d				\
	mediator.7d			\
	mega_sas.7d			\
	mem.7d				\
	mpt_sas.7d			\
	mr_sas.7d			\
	msglog.7d			\
	mt.7d				\
	mxfe.7d				\
	myri10ge.7d			\
	n2cp.7d				\
	n2rng.7d			\
	ncp.7d				\
	npe.7d				\
	ntwdt.7d			\
	ntxn.7d				\
	null.7d				\
	nulldriver.7d			\
	nv_sata.7d			\
	nxge.7d				\
	ohci.7d				\
	openprom.7d			\
	oplkmdrv.7d			\
	oplmsu.7d			\
	oplpanel.7d			\
	pcan.7d				\
	pcata.7d			\
	pcic.7d				\
	pcicmu.7d			\
	pcie_pci.7d			\
	pcipsy.7d			\
	pcisch.7d			\
	pcmcia.7d			\
	pcmem.7d			\
	pcram.7d			\
	pcwl.7d				\
	physmem.7d			\
	pm.7d				\
	poll.7d				\
	profile.7d			\
	ptm.7d				\
	pts.7d				\
	pty.7d				\
	qlc.7d				\
	radeon.7d			\
	ral.7d				\
	ramdisk.7d			\
	random.7d			\
	rge.7d				\
	rtw.7d				\
	rum.7d				\
	rwd.7d				\
	rwn.7d				\
	sad.7d				\
	sata.7d				\
	schpc.7d			\
	scsa1394.7d			\
	scsa2usb.7d			\
	sd.7d				\
	sda.7d				\
	sdcard.7d			\
	sdhost.7d			\
	sdp.7d				\
	sdt.7d				\
	ses.7d				\
	sf.7d				\
	sfe.7d				\
	sgen.7d				\
	si3124.7d			\
	smbios.7d			\
	smbus.7d			\
	socal.7d			\
	srpt.7d				\
	ssd.7d				\
	st.7d				\
	stp4020.7d			\
	su.7d				\
	sv.7d				\
	sysmsg.7d			\
	systrace.7d			\
	ticlts.7d			\
	todopol.7d			\
	tpf.7d				\
	tsalarm.7d			\
	tty.7d				\
	ttymux.7d			\
	tzmon.7d			\
	uath.7d				\
	ugen.7d				\
	uhci.7d				\
	ural.7d				\
	urtw.7d				\
	usb_ac.7d			\
	usb_as.7d			\
	usb_ia.7d			\
	usb_mid.7d			\
	usba.7d				\
	usbftdi.7d			\
	usbprn.7d			\
	usbsacm.7d			\
	usbsksp.7d			\
	usbsprl.7d			\
	usbvc.7d			\
	uwba.7d				\
	virtualkm.7d			\
	vni.7d				\
	vr.7d				\
	wbsd.7d				\
	wpi.7d				\
	wscons.7d			\
	wusb_ca.7d			\
	wusb_df.7d			\
	xge.7d				\
	yge.7d				\
	zcons.7d			\
	zero.7d				\
	zs.7d				\
	zsh.7d				\
	zyd.7d

MANSO=					\
	1394.7d				\
	allkmem.7d			\
	bscbus.7d			\
	drmach.7d			\
	fdc.7d				\
	firewire.7d			\
	hwa1480_fw.7d			\
	i2bsc.7d			\
	kmem.7d				\
	lo0.7d				\
	ngdr.7d				\
	ngdrmach.7d			\
	ticots.7d			\
	ticotsord.7d			\
	urandom.7d			\
	usb.7d				\
	uwb.7d

1394.7d					:= SOFILE = man7d/ieee1394.7d
allkmem.7d				:= SOFILE = man7d/mem.7d
bscbus.7d				:= SOFILE = man7d/bscv.7d
drmach.7d				:= SOFILE = man7d/dr.7d
fdc.7d					:= SOFILE = man7d/fd.7d
firewire.7d				:= SOFILE = man7d/ieee1394.7d
hwa1480_fw.7d				:= SOFILE = man7d/wusb_df.7d
i2bsc.7d				:= SOFILE = man7d/bscv.7d
kmem.7d					:= SOFILE = man7d/mem.7d
lo0.7d					:= SOFILE = man7d/ipnet.7d
ngdr.7d					:= SOFILE = man7d/dr.7d
ngdrmach.7d				:= SOFILE = man7d/dr.7d
ticots.7d				:= SOFILE = man7d/ticlts.7d
ticotsord.7d				:= SOFILE = man7d/ticlts.7d
urandom.7d				:= SOFILE = man7d/random.7d
usb.7d					:= SOFILE = man7d/usba.7d
uwb.7d					:= SOFILE = man7d/uwba.7d

include ../Makefile.man

install: $(ROOTMANFILES)
