#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3m

MANFILES=				\
	acos.3m				\
	acosh.3m			\
	asin.3m				\
	asinh.3m			\
	atan.3m				\
	atan2.3m			\
	atanh.3m			\
	cabs.3m				\
	cacos.3m			\
	cacosh.3m			\
	carg.3m				\
	casin.3m			\
	casinh.3m			\
	catan.3m			\
	catanh.3m			\
	cbrt.3m				\
	ccos.3m				\
	ccosh.3m			\
	ceil.3m				\
	cexp.3m				\
	cimag.3m			\
	clog.3m				\
	conj.3m				\
	copysign.3m			\
	cos.3m				\
	cosh.3m				\
	cpow.3m				\
	cproj.3m			\
	creal.3m			\
	csin.3m				\
	csinh.3m			\
	csqrt.3m			\
	ctan.3m				\
	ctanh.3m			\
	erf.3m				\
	erfc.3m				\
	exp.3m				\
	exp2.3m				\
	expm1.3m			\
	fabs.3m				\
	fdim.3m				\
	feclearexcept.3m		\
	fegetenv.3m			\
	fegetexceptflag.3m		\
	fegetround.3m			\
	feholdexcept.3m			\
	feraiseexcept.3m		\
	fesetprec.3m			\
	fetestexcept.3m			\
	feupdateenv.3m			\
	fex_merge_flags.3m		\
	fex_set_handling.3m		\
	fex_set_log.3m			\
	floor.3m			\
	fma.3m				\
	fmax.3m				\
	fmin.3m				\
	fmod.3m				\
	fpclassify.3m			\
	frexp.3m			\
	hypot.3m			\
	ilogb.3m			\
	isfinite.3m			\
	isgreater.3m			\
	isgreaterequal.3m		\
	isinf.3m			\
	isless.3m			\
	islessequal.3m			\
	islessgreater.3m		\
	isnan.3m			\
	isnormal.3m			\
	isunordered.3m			\
	j0.3m				\
	ldexp.3m			\
	lgamma.3m			\
	llrint.3m			\
	llround.3m			\
	log.3m				\
	log10.3m			\
	log1p.3m			\
	log2.3m				\
	logb.3m				\
	lrint.3m			\
	lround.3m			\
	matherr.3m			\
	modf.3m				\
	nan.3m				\
	nearbyint.3m			\
	nextafter.3m			\
	pow.3m				\
	remainder.3m			\
	remquo.3m			\
	rint.3m				\
	round.3m			\
	scalb.3m			\
	scalbln.3m			\
	signbit.3m			\
	significand.3m			\
	sin.3m				\
	sincos.3m			\
	sinh.3m				\
	sqrt.3m				\
	tan.3m				\
	tanh.3m				\
	tgamma.3m			\
	trunc.3m			\
	y0.3m

MANSO=					\
	acosf.3m			\
	acoshf.3m			\
	acoshl.3m			\
	acosl.3m			\
	asinf.3m			\
	asinhf.3m			\
	asinhl.3m			\
	asinl.3m			\
	atan2f.3m			\
	atan2l.3m			\
	atanf.3m			\
	atanhf.3m			\
	atanhl.3m			\
	atanl.3m			\
	cabsf.3m			\
	cabsl.3m			\
	cacosf.3m			\
	cacoshf.3m			\
	cacoshl.3m			\
	cacosl.3m			\
	cargf.3m			\
	cargl.3m			\
	casinf.3m			\
	casinhf.3m			\
	casinhl.3m			\
	casinl.3m			\
	catanf.3m			\
	catanhf.3m			\
	catanhl.3m			\
	catanl.3m			\
	cbrtf.3m			\
	cbrtl.3m			\
	ccosf.3m			\
	ccoshf.3m			\
	ccoshl.3m			\
	ccosl.3m			\
	ceilf.3m			\
	ceill.3m			\
	cexpf.3m			\
	cexpl.3m			\
	cimagf.3m			\
	cimagl.3m			\
	clogf.3m			\
	clogl.3m			\
	conjf.3m			\
	conjl.3m			\
	copysignf.3m			\
	copysignl.3m			\
	cosf.3m				\
	coshf.3m			\
	coshl.3m			\
	cosl.3m				\
	cpowf.3m			\
	cpowl.3m			\
	cprojf.3m			\
	cprojl.3m			\
	crealf.3m			\
	creall.3m			\
	csinf.3m			\
	csinhf.3m			\
	csinhl.3m			\
	csinl.3m			\
	csqrtf.3m			\
	csqrtl.3m			\
	ctanf.3m			\
	ctanhf.3m			\
	ctanhl.3m			\
	ctanl.3m			\
	erfcf.3m			\
	erfcl.3m			\
	erff.3m				\
	erfl.3m				\
	exp2f.3m			\
	exp2l.3m			\
	expf.3m				\
	expl.3m				\
	expm1f.3m			\
	expm1l.3m			\
	fabsf.3m			\
	fabsl.3m			\
	fdimf.3m			\
	fdiml.3m			\
	fegetprec.3m			\
	fesetenv.3m			\
	fesetexceptflag.3m		\
	fesetround.3m			\
	fex_get_handling.3m		\
	fex_get_log_depth.3m		\
	fex_get_log.3m			\
	fex_getexcepthandler.3m		\
	fex_log_entry.3m		\
	fex_set_log_depth.3m		\
	fex_setexcepthandler.3m		\
	floorf.3m			\
	floorl.3m			\
	fmaf.3m				\
	fmal.3m				\
	fmaxf.3m			\
	fmaxl.3m			\
	fminf.3m			\
	fminl.3m			\
	fmodf.3m			\
	fmodl.3m			\
	frexpf.3m			\
	frexpl.3m			\
	gamma_r.3m			\
	gamma.3m			\
	gammaf_r.3m			\
	gammaf.3m			\
	gammal_r.3m			\
	gammal.3m			\
	hypotf.3m			\
	hypotl.3m			\
	ilogbf.3m			\
	ilogbl.3m			\
	j0f.3m				\
	j0l.3m				\
	j1.3m				\
	j1f.3m				\
	j1l.3m				\
	jn.3m				\
	jnf.3m				\
	jnl.3m				\
	ldexpf.3m			\
	ldexpl.3m			\
	lgamma_r.3m			\
	lgammaf_r.3m			\
	lgammaf.3m			\
	lgammal_r.3m			\
	lgammal.3m			\
	llrintf.3m			\
	llrintl.3m			\
	llroundf.3m			\
	llroundl.3m			\
	log10f.3m			\
	log10l.3m			\
	log1pf.3m			\
	log1pl.3m			\
	log2f.3m			\
	log2l.3m			\
	logbf.3m			\
	logbl.3m			\
	logf.3m				\
	logl.3m				\
	lrintf.3m			\
	lrintl.3m			\
	lroundf.3m			\
	lroundl.3m			\
	modff.3m			\
	modfl.3m			\
	nanf.3m				\
	nanl.3m				\
	nearbyintf.3m			\
	nearbyintl.3m			\
	nextafterf.3m			\
	nextafterl.3m			\
	nexttoward.3m			\
	nexttowardf.3m			\
	nexttowardl.3m			\
	powf.3m				\
	powl.3m				\
	remainderf.3m			\
	remainderl.3m			\
	remquof.3m			\
	remquol.3m			\
	rintf.3m			\
	rintl.3m			\
	roundf.3m			\
	roundl.3m			\
	scalbf.3m			\
	scalbl.3m			\
	scalblnf.3m			\
	scalblnl.3m			\
	scalbn.3m			\
	scalbnf.3m			\
	scalbnl.3m			\
	significandf.3m			\
	significandl.3m			\
	sincosf.3m			\
	sincosl.3m			\
	sinf.3m				\
	sinhf.3m			\
	sinhl.3m			\
	sinl.3m				\
	sqrtf.3m			\
	sqrtl.3m			\
	tanf.3m				\
	tanhf.3m			\
	tanhl.3m			\
	tanl.3m				\
	tgammaf.3m			\
	tgammal.3m			\
	truncf.3m			\
	truncl.3m			\
	y0f.3m				\
	y0l.3m				\
	y1.3m				\
	y1f.3m				\
	y1l.3m				\
	yn.3m				\
	ynf.3m				\
	ynl.3m

acosf.3m				:= SOFILE = man3m/acos.3m
acoshf.3m				:= SOFILE = man3m/acosh.3m
acoshl.3m				:= SOFILE = man3m/acosh.3m
acosl.3m				:= SOFILE = man3m/acos.3m
asinf.3m				:= SOFILE = man3m/asin.3m
asinhf.3m				:= SOFILE = man3m/asinh.3m
asinhl.3m				:= SOFILE = man3m/asinh.3m
asinl.3m				:= SOFILE = man3m/asin.3m
atan2f.3m				:= SOFILE = man3m/atan2.3m
atan2l.3m				:= SOFILE = man3m/atan2.3m
atanf.3m				:= SOFILE = man3m/atan.3m
atanhf.3m				:= SOFILE = man3m/atanh.3m
atanhl.3m				:= SOFILE = man3m/atanh.3m
atanl.3m				:= SOFILE = man3m/atan.3m
cabsf.3m				:= SOFILE = man3m/cabs.3m
cabsl.3m				:= SOFILE = man3m/cabs.3m
cacosf.3m				:= SOFILE = man3m/cacos.3m
cacoshf.3m				:= SOFILE = man3m/cacosh.3m
cacoshl.3m				:= SOFILE = man3m/cacosh.3m
cacosl.3m				:= SOFILE = man3m/cacos.3m
cargf.3m				:= SOFILE = man3m/carg.3m
cargl.3m				:= SOFILE = man3m/carg.3m
casinf.3m				:= SOFILE = man3m/casin.3m
casinhf.3m				:= SOFILE = man3m/casinh.3m
casinhl.3m				:= SOFILE = man3m/casinh.3m
casinl.3m				:= SOFILE = man3m/casin.3m
catanf.3m				:= SOFILE = man3m/catan.3m
catanhf.3m				:= SOFILE = man3m/catanh.3m
catanhl.3m				:= SOFILE = man3m/catanh.3m
catanl.3m				:= SOFILE = man3m/catan.3m
cbrtf.3m				:= SOFILE = man3m/cbrt.3m
cbrtl.3m				:= SOFILE = man3m/cbrt.3m
ccosf.3m				:= SOFILE = man3m/ccos.3m
ccoshf.3m				:= SOFILE = man3m/ccosh.3m
ccoshl.3m				:= SOFILE = man3m/ccosh.3m
ccosl.3m				:= SOFILE = man3m/ccos.3m
ceilf.3m				:= SOFILE = man3m/ceil.3m
ceill.3m				:= SOFILE = man3m/ceil.3m
cexpf.3m				:= SOFILE = man3m/cexp.3m
cexpl.3m				:= SOFILE = man3m/cexp.3m
cimagf.3m				:= SOFILE = man3m/cimag.3m
cimagl.3m				:= SOFILE = man3m/cimag.3m
clogf.3m				:= SOFILE = man3m/clog.3m
clogl.3m				:= SOFILE = man3m/clog.3m
conjf.3m				:= SOFILE = man3m/conj.3m
conjl.3m				:= SOFILE = man3m/conj.3m
copysignf.3m				:= SOFILE = man3m/copysign.3m
copysignl.3m				:= SOFILE = man3m/copysign.3m
cosf.3m					:= SOFILE = man3m/cos.3m
coshf.3m				:= SOFILE = man3m/cosh.3m
coshl.3m				:= SOFILE = man3m/cosh.3m
cosl.3m					:= SOFILE = man3m/cos.3m
cpowf.3m				:= SOFILE = man3m/cpow.3m
cpowl.3m				:= SOFILE = man3m/cpow.3m
cprojf.3m				:= SOFILE = man3m/cproj.3m
cprojl.3m				:= SOFILE = man3m/cproj.3m
crealf.3m				:= SOFILE = man3m/creal.3m
creall.3m				:= SOFILE = man3m/creal.3m
csinf.3m				:= SOFILE = man3m/csin.3m
csinhf.3m				:= SOFILE = man3m/csinh.3m
csinhl.3m				:= SOFILE = man3m/csinh.3m
csinl.3m				:= SOFILE = man3m/csin.3m
csqrtf.3m				:= SOFILE = man3m/csqrt.3m
csqrtl.3m				:= SOFILE = man3m/csqrt.3m
ctanf.3m				:= SOFILE = man3m/ctan.3m
ctanhf.3m				:= SOFILE = man3m/ctanh.3m
ctanhl.3m				:= SOFILE = man3m/ctanh.3m
ctanl.3m				:= SOFILE = man3m/ctan.3m
erfcf.3m				:= SOFILE = man3m/erfc.3m
erfcl.3m				:= SOFILE = man3m/erfc.3m
erff.3m					:= SOFILE = man3m/erf.3m
erfl.3m					:= SOFILE = man3m/erf.3m
exp2f.3m				:= SOFILE = man3m/exp2.3m
exp2l.3m				:= SOFILE = man3m/exp2.3m
expf.3m					:= SOFILE = man3m/exp.3m
expl.3m					:= SOFILE = man3m/exp.3m
expm1f.3m				:= SOFILE = man3m/expm1.3m
expm1l.3m				:= SOFILE = man3m/expm1.3m
fabsf.3m				:= SOFILE = man3m/fabs.3m
fabsl.3m				:= SOFILE = man3m/fabs.3m
fdimf.3m				:= SOFILE = man3m/fdim.3m
fdiml.3m				:= SOFILE = man3m/fdim.3m
fegetprec.3m				:= SOFILE = man3m/fesetprec.3m
fesetenv.3m				:= SOFILE = man3m/fegetenv.3m
fesetexceptflag.3m			:= SOFILE = man3m/fegetexceptflag.3m
fesetround.3m				:= SOFILE = man3m/fegetround.3m
fex_get_handling.3m			:= SOFILE = man3m/fex_set_handling.3m
fex_get_log_depth.3m			:= SOFILE = man3m/fex_set_log.3m
fex_get_log.3m				:= SOFILE = man3m/fex_set_log.3m
fex_getexcepthandler.3m			:= SOFILE = man3m/fex_set_handling.3m
fex_log_entry.3m			:= SOFILE = man3m/fex_set_log.3m
fex_set_log_depth.3m			:= SOFILE = man3m/fex_set_log.3m
fex_setexcepthandler.3m			:= SOFILE = man3m/fex_set_handling.3m
floorf.3m				:= SOFILE = man3m/floor.3m
floorl.3m				:= SOFILE = man3m/floor.3m
fmaf.3m					:= SOFILE = man3m/fma.3m
fmal.3m					:= SOFILE = man3m/fma.3m
fmaxf.3m				:= SOFILE = man3m/fmax.3m
fmaxl.3m				:= SOFILE = man3m/fmax.3m
fminf.3m				:= SOFILE = man3m/fmin.3m
fminl.3m				:= SOFILE = man3m/fmin.3m
fmodf.3m				:= SOFILE = man3m/fmod.3m
fmodl.3m				:= SOFILE = man3m/fmod.3m
frexpf.3m				:= SOFILE = man3m/frexp.3m
frexpl.3m				:= SOFILE = man3m/frexp.3m
gamma_r.3m				:= SOFILE = man3m/lgamma.3m
gamma.3m				:= SOFILE = man3m/lgamma.3m
gammaf_r.3m				:= SOFILE = man3m/lgamma.3m
gammaf.3m				:= SOFILE = man3m/lgamma.3m
gammal_r.3m				:= SOFILE = man3m/lgamma.3m
gammal.3m				:= SOFILE = man3m/lgamma.3m
hypotf.3m				:= SOFILE = man3m/hypot.3m
hypotl.3m				:= SOFILE = man3m/hypot.3m
ilogbf.3m				:= SOFILE = man3m/ilogb.3m
ilogbl.3m				:= SOFILE = man3m/ilogb.3m
j0f.3m					:= SOFILE = man3m/j0.3m
j0l.3m					:= SOFILE = man3m/j0.3m
j1.3m					:= SOFILE = man3m/j0.3m
j1f.3m					:= SOFILE = man3m/j0.3m
j1l.3m					:= SOFILE = man3m/j0.3m
jn.3m					:= SOFILE = man3m/j0.3m
jnf.3m					:= SOFILE = man3m/j0.3m
jnl.3m					:= SOFILE = man3m/j0.3m
ldexpf.3m				:= SOFILE = man3m/ldexp.3m
ldexpl.3m				:= SOFILE = man3m/ldexp.3m
lgamma_r.3m				:= SOFILE = man3m/lgamma.3m
lgammaf_r.3m				:= SOFILE = man3m/lgamma.3m
lgammaf.3m				:= SOFILE = man3m/lgamma.3m
lgammal_r.3m				:= SOFILE = man3m/lgamma.3m
lgammal.3m				:= SOFILE = man3m/lgamma.3m
llrintf.3m				:= SOFILE = man3m/llrint.3m
llrintl.3m				:= SOFILE = man3m/llrint.3m
llroundf.3m				:= SOFILE = man3m/llround.3m
llroundl.3m				:= SOFILE = man3m/llround.3m
log10f.3m				:= SOFILE = man3m/log10.3m
log10l.3m				:= SOFILE = man3m/log10.3m
log1pf.3m				:= SOFILE = man3m/log1p.3m
log1pl.3m				:= SOFILE = man3m/log1p.3m
log2f.3m				:= SOFILE = man3m/log2.3m
log2l.3m				:= SOFILE = man3m/log2.3m
logbf.3m				:= SOFILE = man3m/logb.3m
logbl.3m				:= SOFILE = man3m/logb.3m
logf.3m					:= SOFILE = man3m/log.3m
logl.3m					:= SOFILE = man3m/log.3m
lrintf.3m				:= SOFILE = man3m/lrint.3m
lrintl.3m				:= SOFILE = man3m/lrint.3m
lroundf.3m				:= SOFILE = man3m/lround.3m
lroundl.3m				:= SOFILE = man3m/lround.3m
modff.3m				:= SOFILE = man3m/modf.3m
modfl.3m				:= SOFILE = man3m/modf.3m
nanf.3m					:= SOFILE = man3m/nan.3m
nanl.3m					:= SOFILE = man3m/nan.3m
nearbyintf.3m				:= SOFILE = man3m/nearbyint.3m
nearbyintl.3m				:= SOFILE = man3m/nearbyint.3m
nextafterf.3m				:= SOFILE = man3m/nextafter.3m
nextafterl.3m				:= SOFILE = man3m/nextafter.3m
nexttoward.3m				:= SOFILE = man3m/nextafter.3m
nexttowardf.3m				:= SOFILE = man3m/nextafter.3m
nexttowardl.3m				:= SOFILE = man3m/nextafter.3m
powf.3m					:= SOFILE = man3m/pow.3m
powl.3m					:= SOFILE = man3m/pow.3m
remainderf.3m				:= SOFILE = man3m/remainder.3m
remainderl.3m				:= SOFILE = man3m/remainder.3m
remquof.3m				:= SOFILE = man3m/remquo.3m
remquol.3m				:= SOFILE = man3m/remquo.3m
rintf.3m				:= SOFILE = man3m/rint.3m
rintl.3m				:= SOFILE = man3m/rint.3m
roundf.3m				:= SOFILE = man3m/round.3m
roundl.3m				:= SOFILE = man3m/round.3m
scalbf.3m				:= SOFILE = man3m/scalb.3m
scalbl.3m				:= SOFILE = man3m/scalb.3m
scalblnf.3m				:= SOFILE = man3m/scalbln.3m
scalblnl.3m				:= SOFILE = man3m/scalbln.3m
scalbn.3m				:= SOFILE = man3m/scalbln.3m
scalbnf.3m				:= SOFILE = man3m/scalbln.3m
scalbnl.3m				:= SOFILE = man3m/scalbln.3m
significandf.3m				:= SOFILE = man3m/significand.3m
significandl.3m				:= SOFILE = man3m/significand.3m
sincosf.3m				:= SOFILE = man3m/sincos.3m
sincosl.3m				:= SOFILE = man3m/sincos.3m
sinf.3m					:= SOFILE = man3m/sin.3m
sinhf.3m				:= SOFILE = man3m/sinh.3m
sinhl.3m				:= SOFILE = man3m/sinh.3m
sinl.3m					:= SOFILE = man3m/sin.3m
sqrtf.3m				:= SOFILE = man3m/sqrt.3m
sqrtl.3m				:= SOFILE = man3m/sqrt.3m
tanf.3m					:= SOFILE = man3m/tan.3m
tanhf.3m				:= SOFILE = man3m/tanh.3m
tanhl.3m				:= SOFILE = man3m/tanh.3m
tanl.3m					:= SOFILE = man3m/tan.3m
tgammaf.3m				:= SOFILE = man3m/tgamma.3m
tgammal.3m				:= SOFILE = man3m/tgamma.3m
truncf.3m				:= SOFILE = man3m/trunc.3m
truncl.3m				:= SOFILE = man3m/trunc.3m
y0f.3m					:= SOFILE = man3m/y0.3m
y0l.3m					:= SOFILE = man3m/y0.3m
y1.3m					:= SOFILE = man3m/y0.3m
y1f.3m					:= SOFILE = man3m/y0.3m
y1l.3m					:= SOFILE = man3m/y0.3m
yn.3m					:= SOFILE = man3m/y0.3m
ynf.3m					:= SOFILE = man3m/y0.3m
ynl.3m					:= SOFILE = man3m/y0.3m

include ../Makefile.man

install: $(ROOTMANFILES)
