#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3mp

MANFILES=				\
	mp.3mp

MANSO=					\
	mp_gcd.3mp			\
	mp_itom.3mp			\
	mp_madd.3mp			\
	mp_mcmp.3mp			\
	mp_mdiv.3mp			\
	mp_mfree.3mp			\
	mp_min.3mp			\
	mp_mout.3mp			\
	mp_msqrt.3mp			\
	mp_msub.3mp			\
	mp_mtox.3mp			\
	mp_mult.3mp			\
	mp_pow.3mp			\
	mp_rpow.3mp			\
	mp_sdiv.3mp			\
	mp_xtom.3mp

mp_gcd.3mp				:= SOFILE = man3mp/mp.3mp
mp_itom.3mp				:= SOFILE = man3mp/mp.3mp
mp_madd.3mp				:= SOFILE = man3mp/mp.3mp
mp_mcmp.3mp				:= SOFILE = man3mp/mp.3mp
mp_mdiv.3mp				:= SOFILE = man3mp/mp.3mp
mp_mfree.3mp				:= SOFILE = man3mp/mp.3mp
mp_min.3mp				:= SOFILE = man3mp/mp.3mp
mp_mout.3mp				:= SOFILE = man3mp/mp.3mp
mp_msqrt.3mp				:= SOFILE = man3mp/mp.3mp
mp_msub.3mp				:= SOFILE = man3mp/mp.3mp
mp_mtox.3mp				:= SOFILE = man3mp/mp.3mp
mp_mult.3mp				:= SOFILE = man3mp/mp.3mp
mp_pow.3mp				:= SOFILE = man3mp/mp.3mp
mp_rpow.3mp				:= SOFILE = man3mp/mp.3mp
mp_sdiv.3mp				:= SOFILE = man3mp/mp.3mp
mp_xtom.3mp				:= SOFILE = man3mp/mp.3mp

include ../Makefile.man

install: $(ROOTMANFILES)
