#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3ext

MANFILES=				\
	auto_ef.3ext			\
	crypt.3ext			\
	demangle.3ext			\
	ecb_crypt.3ext			\
	efi_alloc_and_init.3ext		\
	ld_support.3ext			\
	md4.3ext			\
	md5.3ext			\
	NOTE.3ext			\
	read_vtoc.3ext			\
	rtld_audit.3ext			\
	rtld_db.3ext			\
	sendfile.3ext			\
	sendfilev.3ext			\
	sha1.3ext			\
	sha2.3ext			\
	stdarg.3ext			\
	SUNW_C_GetMechSession.3ext	\
	tsalarm_get.3ext		\
	varargs.3ext

MANSO=					\
	_NOTE.3ext			\
	auto_ef_file.3ext		\
	auto_ef_free.3ext		\
	auto_ef_get_encoding.3ext	\
	auto_ef_get_score.3ext		\
	auto_ef_str.3ext		\
	cbc_crypt.3ext			\
	cplus_demangle.3ext		\
	crypt_close.3ext		\
	des_crypt.3ext			\
	des_encrypt.3ext		\
	DES_FAILED.3ext			\
	des_setkey.3ext			\
	des_setparity.3ext		\
	efi_alloc_and_read.3ext		\
	efi_free.3ext			\
	efi_use_whole_disk.3ext		\
	efi_write.3ext			\
	encrypt.3ext			\
	la_activity.3ext		\
	la_amd64_pltenter.3ext		\
	la_i86_pltenter.3ext		\
	la_objfilter.3ext		\
	la_objopen.3ext			\
	la_objsearch.3ext		\
	la_pltexit.3ext			\
	la_pltexit64.3ext		\
	la_preinit.3ext			\
	la_sparcv8_pltenter.3ext	\
	la_sparcv9_pltenter.3ext	\
	la_symbind32.3ext		\
	la_symbind64.3ext		\
	la_version.3ext			\
	ld_atexit.3ext			\
	ld_atexit64.3ext		\
	ld_file.3ext			\
	ld_file64.3ext			\
	ld_input_done.3ext		\
	ld_input_section.3ext		\
	ld_input_section64.3ext		\
	ld_open.3ext			\
	ld_open64.3ext			\
	ld_section.3ext			\
	ld_section64.3ext		\
	ld_start.3ext			\
	ld_start64.3ext			\
	ld_version.3ext			\
	MD4Final.3ext			\
	MD4Init.3ext			\
	MD4Update.3ext			\
	md5_calc.3ext			\
	MD5Final.3ext			\
	MD5Init.3ext			\
	MD5Update.3ext			\
	rd_delete.3ext			\
	rd_errstr.3ext			\
	rd_event_addr.3ext		\
	rd_event_enable.3ext		\
	rd_event_getmsg.3ext		\
	rd_init.3ext			\
	rd_loadobj_iter.3ext		\
	rd_log.3ext			\
	rd_new.3ext			\
	rd_objpad_enable.3ext		\
	rd_plt_resolution.3ext		\
	rd_reset.3ext			\
	run_crypt.3ext			\
	run_setkey.3ext			\
	setkey.3ext			\
	SHA1Final.3ext			\
	SHA1Init.3ext			\
	SHA1Update.3ext			\
	SHA256Final.3ext		\
	SHA256Init.3ext			\
	SHA256Update.3ext		\
	SHA2Final.3ext			\
	SHA2Init.3ext			\
	SHA2Update.3ext			\
	SHA384Final.3ext		\
	SHA384Init.3ext			\
	SHA384Update.3ext		\
	SHA512Final.3ext		\
	SHA512Init.3ext			\
	SHA512Update.3ext		\
	SUNW_C_KeyToObject.3ext		\
	tsalarm_set.3ext		\
	write_vtoc.3ext

_NOTE.3ext				:= SOFILE = man3ext/NOTE.3ext
auto_ef_file.3ext			:= SOFILE = man3ext/auto_ef.3ext
auto_ef_free.3ext			:= SOFILE = man3ext/auto_ef.3ext
auto_ef_get_encoding.3ext		:= SOFILE = man3ext/auto_ef.3ext
auto_ef_get_score.3ext			:= SOFILE = man3ext/auto_ef.3ext
auto_ef_str.3ext			:= SOFILE = man3ext/auto_ef.3ext
cbc_crypt.3ext				:= SOFILE = man3ext/ecb_crypt.3ext
cplus_demangle.3ext			:= SOFILE = man3ext/demangle.3ext
crypt_close.3ext			:= SOFILE = man3ext/crypt.3ext
des_crypt.3ext				:= SOFILE = man3ext/crypt.3ext
des_encrypt.3ext			:= SOFILE = man3ext/crypt.3ext
DES_FAILED.3ext				:= SOFILE = man3ext/ecb_crypt.3ext
des_setkey.3ext				:= SOFILE = man3ext/crypt.3ext
des_setparity.3ext			:= SOFILE = man3ext/ecb_crypt.3ext
efi_alloc_and_read.3ext			:= SOFILE = man3ext/efi_alloc_and_init.3ext
efi_free.3ext				:= SOFILE = man3ext/efi_alloc_and_init.3ext
efi_use_whole_disk.3ext			:= SOFILE = man3ext/efi_alloc_and_init.3ext
efi_write.3ext				:= SOFILE = man3ext/efi_alloc_and_init.3ext
encrypt.3ext				:= SOFILE = man3ext/crypt.3ext
la_activity.3ext			:= SOFILE = man3ext/rtld_audit.3ext
la_amd64_pltenter.3ext			:= SOFILE = man3ext/rtld_audit.3ext
la_i86_pltenter.3ext			:= SOFILE = man3ext/rtld_audit.3ext
la_objfilter.3ext			:= SOFILE = man3ext/rtld_audit.3ext
la_objopen.3ext				:= SOFILE = man3ext/rtld_audit.3ext
la_objsearch.3ext			:= SOFILE = man3ext/rtld_audit.3ext
la_pltexit.3ext				:= SOFILE = man3ext/rtld_audit.3ext
la_pltexit64.3ext			:= SOFILE = man3ext/rtld_audit.3ext
la_preinit.3ext				:= SOFILE = man3ext/rtld_audit.3ext
la_sparcv8_pltenter.3ext		:= SOFILE = man3ext/rtld_audit.3ext
la_sparcv9_pltenter.3ext		:= SOFILE = man3ext/rtld_audit.3ext
la_symbind32.3ext			:= SOFILE = man3ext/rtld_audit.3ext
la_symbind64.3ext			:= SOFILE = man3ext/rtld_audit.3ext
la_version.3ext				:= SOFILE = man3ext/rtld_audit.3ext
ld_atexit.3ext				:= SOFILE = man3ext/ld_support.3ext
ld_atexit64.3ext			:= SOFILE = man3ext/ld_support.3ext
ld_file.3ext				:= SOFILE = man3ext/ld_support.3ext
ld_file64.3ext				:= SOFILE = man3ext/ld_support.3ext
ld_input_done.3ext			:= SOFILE = man3ext/ld_support.3ext
ld_input_section.3ext			:= SOFILE = man3ext/ld_support.3ext
ld_input_section64.3ext			:= SOFILE = man3ext/ld_support.3ext
ld_open.3ext				:= SOFILE = man3ext/ld_support.3ext
ld_open64.3ext				:= SOFILE = man3ext/ld_support.3ext
ld_section.3ext				:= SOFILE = man3ext/ld_support.3ext
ld_section64.3ext			:= SOFILE = man3ext/ld_support.3ext
ld_start.3ext				:= SOFILE = man3ext/ld_support.3ext
ld_start64.3ext				:= SOFILE = man3ext/ld_support.3ext
ld_version.3ext				:= SOFILE = man3ext/ld_support.3ext
MD4Final.3ext				:= SOFILE = man3ext/md4.3ext
MD4Init.3ext				:= SOFILE = man3ext/md4.3ext
MD4Update.3ext				:= SOFILE = man3ext/md4.3ext
md5_calc.3ext				:= SOFILE = man3ext/md5.3ext
MD5Final.3ext				:= SOFILE = man3ext/md5.3ext
MD5Init.3ext				:= SOFILE = man3ext/md5.3ext
MD5Update.3ext				:= SOFILE = man3ext/md5.3ext
rd_delete.3ext				:= SOFILE = man3ext/rtld_db.3ext
rd_errstr.3ext				:= SOFILE = man3ext/rtld_db.3ext
rd_event_addr.3ext			:= SOFILE = man3ext/rtld_db.3ext
rd_event_enable.3ext			:= SOFILE = man3ext/rtld_db.3ext
rd_event_getmsg.3ext			:= SOFILE = man3ext/rtld_db.3ext
rd_init.3ext				:= SOFILE = man3ext/rtld_db.3ext
rd_loadobj_iter.3ext			:= SOFILE = man3ext/rtld_db.3ext
rd_log.3ext				:= SOFILE = man3ext/rtld_db.3ext
rd_new.3ext				:= SOFILE = man3ext/rtld_db.3ext
rd_objpad_enable.3ext			:= SOFILE = man3ext/rtld_db.3ext
rd_plt_resolution.3ext			:= SOFILE = man3ext/rtld_db.3ext
rd_reset.3ext				:= SOFILE = man3ext/rtld_db.3ext
run_crypt.3ext				:= SOFILE = man3ext/crypt.3ext
run_setkey.3ext				:= SOFILE = man3ext/crypt.3ext
setkey.3ext				:= SOFILE = man3ext/crypt.3ext
SHA1Final.3ext				:= SOFILE = man3ext/sha1.3ext
SHA1Init.3ext				:= SOFILE = man3ext/sha1.3ext
SHA1Update.3ext				:= SOFILE = man3ext/sha1.3ext
SHA256Final.3ext			:= SOFILE = man3ext/sha2.3ext
SHA256Init.3ext				:= SOFILE = man3ext/sha2.3ext
SHA256Update.3ext			:= SOFILE = man3ext/sha2.3ext
SHA2Final.3ext				:= SOFILE = man3ext/sha2.3ext
SHA2Init.3ext				:= SOFILE = man3ext/sha2.3ext
SHA2Update.3ext				:= SOFILE = man3ext/sha2.3ext
SHA384Final.3ext			:= SOFILE = man3ext/sha2.3ext
SHA384Init.3ext				:= SOFILE = man3ext/sha2.3ext
SHA384Update.3ext			:= SOFILE = man3ext/sha2.3ext
SHA512Final.3ext			:= SOFILE = man3ext/sha2.3ext
SHA512Init.3ext				:= SOFILE = man3ext/sha2.3ext
SHA512Update.3ext			:= SOFILE = man3ext/sha2.3ext
SUNW_C_KeyToObject.3ext			:= SOFILE = man3ext/SUNW_C_GetMechSession.3ext
tsalarm_set.3ext			:= SOFILE = man3ext/tsalarm_get.3ext
write_vtoc.3ext				:= SOFILE = man3ext/read_vtoc.3ext

include ../Makefile.man

install: $(ROOTMANFILES)
