'\" te
.\" Copyright (c) 2001 Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright (c) 2012-2013, J. Schilling
.\" Copyright (c) 2013, Andreas Roehler
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH dacf.conf 4 "15 May 2001" "SunOS 5.11" "File Formats"
.SH NAME
dacf.conf \- device auto-configuration configuration file
.SH SYNOPSIS
.LP
.nf
\fB/etc/dacf.conf\fR
.fi

.SH DESCRIPTION
.sp
.LP
The kernel uses the
.B dacf.conf
file to automatically configure hot
plugged devices. Because the
.B dacf.conf
file contains important kernel
state information, it should not be modified.
.sp
.LP
The format of the
.B /etc/dacf.conf
file is not public and might change
in versions of the Solaris operating environment that are not compatible
with Solaris 8.
.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i)
lw(2.75i) |lw(2.75i)
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWcsr
.TE

.SH SEE ALSO
.sp
.LP
.BR attributes (5)
.SH NOTES
.sp
.LP
 This document does not constitute an
.BR API .
The
.B /etc/dacf.conf
file might not exist or might contain different contents or interpretations in
versions of the Solaris operating environment that are not compatible with Solaris 8. The existence of this notice does not imply that any other documentation lacking this notice constitutes an
.BR API .
