'\" te
.\" Copyright (c) 2003 Sun Microsystems, Inc. All rights reserved.
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH dhcpsvc.conf 4 "26 Jun 2003" "SunOS 5.11" "File Formats"
.SH NAME
dhcpsvc.conf \- file containing service configuration parameters for the DHCP
service
.SH DESCRIPTION
.sp
.LP
The \fBdhcpsvc.conf\fR file resides in directory
.B /etc/inet
and contains
parameters for specifying Dynamic Host Configuration Protocol (\fBDHCP\fR)
service configuration settings, including the type and location of \fBDHCP\fR
data store used.
.sp
.LP
The description of the \fBdhcpsvc.conf\fR file in this man page is informational
only. The preferred method of setting or modifying values within the
\fBdhcpsvc.conf\fR file is by using \fBdhcpconfig\fR(1M) or the \fBdhcpmgr\fR(1M)
utility. Do not edit the \fBdhcpsvc.conf\fR file.
.sp
.LP
The \fBdhcpsvc.conf\fR file format is
.BR ASCII ;
comment lines begin with the
crosshatch (\fB#\fR) character. Parameters consist of a keyword followed by an
equals (\fB=\fR) sign followed by the parameter value, of the form:
.sp
.in +2
.nf
\fIKeyword\fR=\fIValue\fR
.fi
.in -2
.sp

.sp
.LP
The following
.I Keyword
and
.I Value
parameters are supported:
.sp
.ne 2
.mk
.na
.B BOOTP_COMPAT
.ad
.RS 28n
.rt
String.
.B automatic
or
.BR manual .
Enables support of
.B BOOTP
clients.
Default is no
.BR BOOTP .
Value selects
.B BOOTP
address allocation method.
\fBautomatic\fR to support all BOOTP clients, \fBmanual\fR to support only
registered
.B BOOTP
clients.
.B server
mode only parameter.
.RE

.sp
.ne 2
.mk
.na
.B CACHE_TIMEOUT
.ad
.RS 28n
.rt
Integer. Number of seconds the server caches data from data store. Used to
improve performance. Default is 10 seconds.
.B server
mode only parameter.
.RE

.sp
.ne 2
.mk
.na
.B CONVER
.ad
.RS 28n
.rt
Integer. Container version. Used by DHCP administrative tools to identify which
version of the public module is being used to administer the data store.
\fBCONVER\fR should \fBnot\fR be changed manually.
.RE

.sp
.ne 2
.mk
.na
.B DAEMON_ENABLED
.ad
.RS 28n
.rt
\fBTRUE\fR/\fBFALSE\fR. If \fBTRUE\fR, the DHCP daemon can be run. If
.BR FALSE ,
DHCP daemon process exits immediately if the daemon is started.
Default is
.BR TRUE .
Generic parameter.
.RE

.sp
.ne 2
.mk
.na
.B HOSTS_DOMAIN
.ad
.RS 28n
.rt
String. Defines name service domain that DHCP administration tools use when
managing the hosts table. Valid only when
.B HOSTS_RESOURCE
is set to
\fBnisplus\fR or \fBdns\fR.
.RE

.sp
.ne 2
.mk
.na
.B HOSTS_RESOURCE
.ad
.RS 28n
.rt
String. Defines what name service resource should be used by the DHCP
administration tools when managing the hosts table. Current valid values are
\fBfiles\fR,
.BR nisplus ,
and
.BR dns .
.RE

.sp
.ne 2
.mk
.na
.B ICMP_VERIFY
.ad
.RS 28n
.rt
\fBTRUE\fR/\fBFALSE\fR. Toggles \fBICMP\fR echo verification of IP addresses.
Default is
.BR TRUE .
\fBserver\fR mode only parameter.
.RE

.sp
.ne 2
.mk
.na
.B INTERFACES
.ad
.RS 28n
.rt
String. Comma-separated list of interface names to listen to. Generic
parameter.
.RE

.sp
.ne 2
.mk
.na
.B LOGGING_FACILITY
.ad
.RS 28n
.rt
Integer. Local facility number (\fB0\fR-\fB7\fR inclusive) to log \fBDHCP\fR
events to. Default is not to log transactions. Generic parameter.
.RE

.sp
.ne 2
.mk
.na
.B OFFER_CACHE_TIMEOUT
.ad
.RS 28n
.rt
Integer. Number of seconds before
.B OFFER
cache timeouts occur. Default is
\fB10\fR seconds. \fBserver\fR mode only parameter.
.RE

.sp
.ne 2
.mk
.na
.B OWNER_IP
.ad
.RS 28n
.rt
String. List of supplemental ownership addresses  that will be used by the DHCP
server in determining the
.B dhcp_network
records that are under its
management. Addresses are in the dotted Internet form of an IPv4 address. Primary
value is the IP address associated with the system's primary interface
(\fInodename\fR ==
.IR hostname ).
Server-mode-only parameter. Note that using
\fBOWNER_IP\fR has some performance impact, thus using a large number might not
be advisable.
.RE

.sp
.ne 2
.mk
.na
.B PATH
.ad
.RS 28n
.rt
Path to DHCP data tables within the data store specified by the RESOURCE
parameter. The value of the
.B PATH
keyword is specific to the RESOURCE.
.RE

.sp
.ne 2
.mk
.na
.B RELAY_DESTINATIONS
.ad
.RS 28n
.rt
String. Comma-separated list of host names and/or
.B IP
addresses of relay
destinations.
.B relay
mode only parameter.
.RE

.sp
.ne 2
.mk
.na
\fBRELAY_HOPS\fR 
.ad
.RS 28n
.rt
Integer. Max number of
.B BOOTP
relay hops before packet is dropped. Default
is
.BR 4 .
Generic parameter.
.RE

.sp
.ne 2
.mk
.na
.B RESCAN_INTERVAL
.ad
.RS 28n
.rt
Integer. Number of minutes between automatic
.B dhcptab
rescans. Default is
not to do rescans.
.B server
mode only parameter.
.RE

.sp
.ne 2
.mk
.na
.B RESOURCE
.ad
.RS 28n
.rt
Data store resource used. Use this parameter to name the public module. See the
\fBPATH\fR keyword in \fBdhcp_modules\fR(5).
.RE

.sp
.ne 2
.mk
.na
.B RESOURCE_CONFIG
.ad
.RS 28n
.rt
String. The private layer provides for module-specific configuration information
through the use of the
.B RESOURCE_CONFIG
keyword. See
.BR dhcp_modules (5).
.sp
Providers can access
.B RESOURCE_CONFIG
using the configure function by
specifying an optional service provider layer API function:
.sp
.in +2
.nf
int configure(const char *configp);
.fi
.in -2

If this function is defined by the public module provider, it is called during
module load time by the private layer, with the contents of the
\fBRESOURCE_CONFIG\fR string acquired by the administrative interface (in the
case of the
.BR dhcpmgr ,
through the use of a public module-specific java bean
extending the
.B dhcpmgr
to provide a configuration dialog for this
information.
.RE

.sp
.ne 2
.mk
.na
.B RUN_MODE
.ad
.RS 28n
.rt
\fBserver\fR or
.BR relay .
Selects daemon run mode. Default is \fBserver\fR.
.RE

.sp
.ne 2
.mk
.na
.B SECONDARY_SERVER_TIMEOUT
.ad
.RS 28n
.rt
Integer. The number of seconds a secondary server waits for a primary server to
respond before responding itself. Default is
.B 20
seconds. This is a server
mode only parameter.
.RE

.sp
.ne 2
.mk
.na
.B UPDATE_TIMEOUT
.ad
.RS 28n
.rt
Integer. Number of seconds to wait for a response from the DNS server before
timing out. If this parameter is present, the DHCP daemon updates DNS on behalf
of DHCP clients, and waits the number of seconds specified for a response before
timing out. You can use
.B UPDATE_TIMEOUT
without specifying a number to
enable DNS updates with the default timeout of 15 seconds. If this parameter is
not present, the DHCP daemon does not update DNS for DHCP clients.
.RE

.sp
.ne 2
.mk
.na
.B VERBOSE
.ad
.RS 28n
.rt
\fBTRUE\fR/\fBFALSE\fR. Toggles verbose mode, determining amount of status and
error messages reported by the daemon. Default is
.BR FALSE .
Set to
.BR TRUE
only for debugging. Generic parameter.
.RE

.SH SEE ALSO
.sp
.LP
.BR dhcpmgr (1M),
.BR in.dhcpd (1M),
.BR dhcp (5),
.BR dhcp_modules (5)
.sp
.LP
.I System Administration Guide: IP Services
