'\" te
.\" Copyright 1989 AT&T  Copyright (c) 1988 Sun Microsystems, Inc. - All Rights Reserved.
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH ethers 4 "22 Jul 2004" "SunOS 5.11" "File Formats"
.SH NAME
ethers \- Ethernet address to hostname database or domain
.SH DESCRIPTION
.sp
.LP
The
.B ethers
file is a local source of information about the (48-bit)
Ethernet addresses of hosts on the Internet. The
.B ethers
file can be
used in conjunction with or instead of other
.B ethers
sources, including
the
.B NIS
maps
.B ethers.byname
and
.BR ethers.byaddr ,
the
.B NIS+
table
.BR ethers ,
or Ethernet address data stored on an LDAP
server. Programs use the
.BR ethers (3SOCKET)
routines to access this
information.
.sp
.LP
The
.B ethers
file has one line for each host on an Ethernet. The line
has the following format:
.sp
.LP
.I Ethernet-address official-host-name
.sp
.LP
Items are separated by any number of
.B SPACE
.RB and/or " TAB"
characters. A `\fB#\fR' indicates the beginning of a comment extending to
the end of line.
.sp
.LP
The standard form for Ethernet addresses is
"\fIx\fB:\fIx\fB:\fIx\fB:\fIx\fB:\fIx\fB:\fIx\fR"
where
.I x
is a hexadecimal number between 0 and ff, representing one
byte. The address bytes are always in network order. Host names may contain
any printable character other than
.BR SPACE ,
.BR TAB ,
.BR NEWLINE ,
or
comment character.
.SH FILES
.sp
.ne 2
.mk
.na
.B /etc/ethers
.ad
.RS 15n
.rt

.RE

.SH SEE ALSO
.sp
.LP
.BR ethers (3SOCKET),
.BR hosts (4),
.BR nsswitch.conf (4)
