'\" te
.\" Copyright (C) 1999, Sun Microsystems, Inc. All Rights Reserved
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH inet_type 4 "16 Jun 1999" "SunOS 5.11" "File Formats"
.SH NAME
inet_type \- default Internet protocol type
.SH SYNOPSIS
.LP
.nf
\fB/etc/default/inet_type\fR
.fi

.SH DESCRIPTION
.sp
.LP
The
.B inet_type
file defines the default
.B IP
protocol to use.
Currently this file is only used by the \fBifconfig\fR(1M) and
.BR netstat (1M)
commands.
.sp
.LP
The
.B inet_type
file can contain a number of
.BR <variable>=<value>
lines. Currently, the only variable defined is
.BR DEFAULT_IP ,
which can be
assigned a value of
.BR IP_VERSION4 ,
.BR IP_VERSION6 ,
or
.BR BOTH .
.sp
.LP
The output displayed by the \fBifconfig\fR and
.B netstat
commands can be
controlled by the value of
.B DEFAULT_IP
set in
.B inet_type
file. By
default, both commands display the IPv4 and IPv6 information available on the
system. The user can choose to suppress display of IPv6 information by setting
the value of
.BR DEFAULT_IP .
The following shows the possible values for
\fBDEFAULT_IP\fR and the resulting \fBifconfig\fR and \fBnetstat\fR output that
will be displayed:
.sp
.ne 2
.mk
.na
.B IP_VERSION4
.ad
.RS 15n
.rt
Displays only IPv4 related information. The output displayed is backward
compatible with older versions of the \fBifconfig\fR(1M) and \fBnetstat\fR(1M)
commands.
.RE

.sp
.ne 2
.mk
.na
.B IP_VERSION6
.ad
.RS 15n
.rt
Displays both IPv4 and IPv6 related information for \fBifconfig\fR and
.BR netstat .
.RE

.sp
.ne 2
.mk
.na
.B BOTH
.ad
.RS 15n
.rt
Displays both IPv4 and IPv6 related information for \fBifconfig\fR and
.BR netstat .
.RE

.sp
.LP
The command-line options to the \fBifconfig\fR and
.B netstat
commands
override the effect of
.B DEFAULT_IP
as set in the
.B inet_type
file. For
example, even if the value of
.B DEFAULT_IP
is
.BR IP_VERSION4 ,
the
command
.sp
.in +2
.nf
example% \fBifconfig -a6\fR
.fi
.in -2
.sp

.sp
.LP
will display all IPv6 interfaces.
.SH EXAMPLES
.LP
\fBExample 1\fR Suppressing IPv6 Related Output
.sp
.LP
This is what the
.B inet_type
file must contain if you want to suppress
IPv6 related output:

.sp
.in +2
.nf
DEFAULT_IP=IP_VERSION4
.fi
.in -2

.SH SEE ALSO
.sp
.LP
\fBifconfig\fR(1M), \fBnetstat\fR(1M)
