'\" te
.\" Copyright (c) 2003, Sun Microsystems, Inc.
.\" All Rights Reserved
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH mddb.cf 4 "8 Aug 2003" "SunOS 5.11" "File Formats"
.SH NAME
mddb.cf \- metadevice state database replica locations
.SH SYNOPSIS
.LP
.nf
\fB/etc/lvm/mddb.cf\fR
.fi

.SH DESCRIPTION
.sp
.LP
The \fB/etc/lvm/mddb.cf\fR file is created when the
.BR metadb (1M)
command is invoked. You should never directly edit this file.
.sp
.LP
The file \fB/etc/lvm/mddb.cf\fR is used by the
.BR metainit (1M)
command
to find the locations of the metadevice state databases replicas. The
\fBmetadb\fR command creates the file and updates it each time it is run.
Similar information is entered in the \fB/kernel/drv/md.conf\fR file.
.sp
.LP
Each metadevice state database replica has a unique entry in the
\fB/etc/lvm/mddb.cf\fR file. Each entry contains the \fIdriver\fR and
\fIminor\fR unit numbers associated with the block physical device where a
replica is stored. Each entry also contains the block number of the master
block, which contains a list of all other blocks in the replica.
.sp
.LP
Entries in the \fB/etc/lvm/mddb.cf\fR file are of the form: \fIdriver_name
\|\|minor_t \|\|daddr_t \| \|checksum\fR where \fIdriver_name\fR and
\fIminor_t\fR represent the device number of the physical device storing
this replica.
.I daddr_t
is the disk block address.
.I checksum
is
used to make certain the entry has not been corrupted. A pound sign (#)
introduces a comment.
.SH EXAMPLES
.LP
\fBExample 1\fR Sample File
.sp
.LP
The following example shows a \fBmddb.cf\fR file.

.sp
.in +2
.nf
#metadevice database location file do not hand edit
#driver minor_t daddr_t device id       checksum
sd      152     16      id1,sd@SSEAGATE_JDD288110MC9LH/a        -2613
.fi
.in -2
.sp

.sp
.LP
In the example above, the value for
.B daddr_t
indicates that the offset
from the start of a given partition is 16 disk blocks from the start of that
partition.

.SH FILES
.sp
.ne 2
.mk
.na
\fB/etc/lvm/mddb.cf\fR
.ad
.RS 23n
.rt

.RE

.sp
.ne 2
.mk
.na
\fB/kernel/drv/md.conf\fR
.ad
.RS 23n
.rt

.RE

.SH SEE ALSO
.sp
.LP
.BR mdmonitord (1M),
.BR metaclear (1M),
.BR metadb (1M),
.BR metadetach (1M),
.BR metahs (1M),
.BR metainit (1M),
.BR metaoffline (1M),
.BR metaonline (1M),
.BR metaparam (1M),
.BR metarecover (1M),
.BR metarename (1M),
.BR metareplace (1M),
.BR metaroot (1M),
.BR metassist (1M),
.BR metaset (1M),
.BR metastat (1M),
.BR metasync (1M),
.BR metattach (1M),
.BR md.cf (4),
.BR md.tab (4),
.BR attributes (5),
.BR md (7D)
.sp
.LP
.I Solaris Volume Manager Administration Guide
