'\" te
.\" Copyright (c) 2004 Sun Microsystems, Inc. All rights reserved.
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH nfs 4 "13 Oct 2004" "SunOS 5.11" "File Formats"
.SH NAME
nfs \- file containing parameter values for NFS-related daemons
.SH SYNOPSIS
.LP
.nf
\fB/etc/default/nfs\fR
.fi

.SH DESCRIPTION
.sp
.LP
The \fBnfs\fR file resides in directory \fB/etc/default\fR and provides
startup parameters for the \fBnfsd\fR(1M) and
.BR lockd (1M)
daemons.
.sp
.LP
The
.B nfs
file format is
.BR ASCII ;
comment lines begin with the
crosshatch (\fB#\fR) character. Parameters consist of a keyword followed by
an equals (\fB=\fR) sign followed by the parameter value, of the form:
.sp
.in +2
.nf
\fIkeyword\fR=\fIvalue\fR
.fi
.in -2
.sp

.sp
.LP
The following parameters are currently supported in the
.B nfs
file:
.sp
.ne 2
.mk
.na
\fBNFS_CLIENT_VERSMIN=\fInum\fR
.ad
.br
.na
\fBNFS_CLIENT_VERSMAX=\fInum\fR
.ad
.sp .6
.RS 4n
The NFS client only uses NFS versions in the range specified by these
variables. Valid values or versions are:
.BR 2 ,
.BR 3 ,
and
.BR 4 .
By
default these variables are unspecified (commented out) and the client's
default minimum is Version 2. The default maximum is Version 4. You can
override this range on a per-mount basis by using the
.B "-o vers="
option
to
.BR mount_nfs (1M).
.RE

.sp
.ne 2
.mk
.na
\fBNFS_SERVER_VERSMIN=\fInum\fR
.ad
.br
.na
\fBNFS_SERVER_VERSMAX=\fInum\fR
.ad
.sp .6
.RS 4n
The NFS server only uses NFS versions in the range specified by these
variables. Valid values or versions are:
.BR 2 ,
.BR 3 ,
and
.BR 4 .
As
with the client, the default is to leave these variables commented out and
the default minimum version is
.BR 2 ,
while the default maximum version is
.BR 4 .
.RE

.sp
.ne 2
.mk
.na
.B NFS_SERVER_DELEGATION=on | off
.ad
.sp .6
.RS 4n
By default, this variable is commented out and the NFS server provides
delegations to clients. The user can turn off delegations for all exported
filesystems by setting this variable to
.B off
(case-sensitive). This
variable only applies to NFS Version 4.
.RE

.sp
.ne 2
.mk
.na
\fBNFSMAPID_DOMAIN=\fIdomain-string\fR
.ad
.sp .6
.RS 4n
By default, the
.B nfsmapid
uses the DNS domain of the system. This
setting overrides the default. This domain is used for identifying user and
group attribute strings in the NFS Version 4 protocol. Clients and servers
must match with this domain for operation to proceed normally. This variable
only applies to NFS Version 4. See "Setting \fBNFSMAPID_DOMAIN\fR," below
for further details.
.RE

.sp
.ne 2
.mk
.na
\fBNFSD_MAX_CONNECTIONS=\fInum\fR
.ad
.sp .6
.RS 4n
Sets the maximum number of concurrent, connection-oriented connections. The
default is unlimited and is obtained by not setting (that is, commenting
out)
.BR NFSD_MAX_CONNECTIONS .
Equivalent to the
.B -c
option in
.BR nfsd .
.RE

.sp
.ne 2
.mk
.na
\fBNFSD_LISTEN_BACKLOG=\fInum\fR
.ad
.sp .6
.RS 4n
Set connection queue length for the NFS over a connection-oriented
transport. The default value is 32, meaning 32 entries in the queue.
Equivalent to the
.B -l
option in
.BR nfsd .
.RE

.sp
.ne 2
.mk
.na
.B NFSD_PROTOCOL=ALL
.ad
.sp .6
.RS 4n
Start
.B nfsd
over the specified protocol only. Equivalent to the
.B -p
option in
.BR nfsd .
.B ALL
is equivalent to
.B -a
on the
.B nfsd
command line. Mutually exlusive of
.BR NFSD_DEVICE .
One or the
other of
.B NFSD_DEVICE
and
.B NFSD_PROTOCOL
must be commented out.
For the UDP protocol, only version 2 and version 3 service is established.
NFS Version 4 is not supported for the UDP protocol.
.RE

.sp
.ne 2
.mk
.na
\fBNFSD_DEVICE=\fIdevname\fR
.ad
.sp .6
.RS 4n
Start NFS daemon for the transport specified by the given device only.
Equivalent to the
.B -t
option in
.BR nfsd .
Mutually exclusive of
.BR NFSD_PROTOCOL .
One or the other of
.B NFSD_DEVICE
and
.B NFSD_PROTOCOL
must be commented out.
.RE

.sp
.ne 2
.mk
.na
\fBNFSD_SERVERS=\fInum\fR
.ad
.sp .6
.RS 4n
Maximum number of concurrent NFS requests. Equivalent to last numeric
argument on the
.B nfsd
command line. The default is
.BR 16 .
.RE

.sp
.ne 2
.mk
.na
\fBLOCKD_LISTEN_BACKLOG=\fInum\fR
.ad
.sp .6
.RS 4n
Set connection queue length for
.B lockd
over a connection-oriented
transport. The default and minimum value is
.BR 32 .
.RE

.sp
.ne 2
.mk
.na
\fBLOCKD_SERVERS=\fInum\fR
.ad
.sp .6
.RS 4n
Maximum number of concurrent
.B lockd
requests. The default is
.BR 20 .
.RE

.sp
.ne 2
.mk
.na
\fBLOCKD_RETRANSMIT_TIMEOUT=\fInum\fR
.ad
.sp .6
.RS 4n
Retransmit timeout, in seconds, before
.B lockd
retries. The default is
.BR 5 .
.RE

.sp
.ne 2
.mk
.na
\fBGRACE_PERIOD=\fInum\fR
.ad
.sp .6
.RS 4n
Grace period, in seconds, that all clients (both
.B NLM
and
.BR NFSv4 )
have to reclaim locks after a server reboot. This parameter also controls
the
.B NFSv4
lease interval and overrides the deprecated setting
.BR LOCKD_GRACE_PERIOD .
The default is
.BR 90 .
.RE

.sp
.ne 2
.mk
.na
\fBLOCKD_GRACE_PERIOD=\fInum\fR
.ad
.sp .6
.RS 4n
Deprecated. Same as \fBGRACE_PERIOD=\fInum\fR above. The default is
.BR 90 .
.RE

.SS "Setting \fBNFSMAPID_DOMAIN\fR"
.sp
.LP
As described above, the setting for
.B NFSMAPID_DOMAIN
overrides the
domain used by \fBnfsmapid\fR(1M) for building and comparing outbound and
inbound attribute strings, respectively. This setting overrides any other
mechanism for setting the NFSv4 domain. In the absence of a
.B NFSMAPID_DOMAIN
setting, the \fBnfsmapid\fR(1M) daemon determines the
NFSv4 domain as follows:
.RS +4
.TP
.ie t \(bu
.el o
If a properly configured \fB/etc/resolv.conf\fR (see \fBresolv.conf\fR(4))
exists,
.B nfsmapid
queries specified nameserver(s) for the domain.
.RE
.RS +4
.TP
.ie t \(bu
.el o
If a properly configured \fB/etc/resolv.conf\fR (see \fBresolv.conf\fR(4))
exists, but the queried nameserver does not have a proper record of the
domain name,
.B nfsmapid
attempts to obtain the domain name through the
BIND interface (see
.BR resolver (3RESOLV)).
.RE
.RS +4
.TP
.ie t \(bu
.el o
If no \fB/etc/resolv.conf\fR exists, \fBnfsmapid\fR falls back on using the
configured domain name (see
.BR domainname (1M)),
which is returned with
the leading domain suffix removed. For example, for
.BR widgets.sales.acme.com ,
.B sales.acme.com
is returned.
.RE
.RS +4
.TP
.ie t \(bu
.el o
If
.B /etc/resolv.conf
does not exist, no domain name has been
configured (or no \fB/etc/defaultdomain\fR exists), \fBnfsmapid\fR falls
back on obtaining the domain name from the host name, if the host name
contains a fully qualified domain name (FQDN).
.RE
.sp
.LP
If a domainname is still not obtained following all of the preceding steps,
.B nfsmapid
will have no domain configured. This results in the following
behavior:
.RS +4
.TP
.ie t \(bu
.el o
Outbound "owner" and "owner_group" attribute strings are encoded as literal
id's. For example, the UID 12345 is encoded as
.BR 12345 .
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBnfsmapid\fR ignores the "domain" portion of the inbound attribute string
and performs name service lookups only for the user or group. If the
user/group exists in the local system name service databases, then the
proper uid/gid will be mapped even when no domain has been configured.
.sp
This behavior implies that the same administrative user/group domain exists
between NFSv4 client and server (that is, the same uid/gid's for
users/groups on both client and server). In the case of overlapping id
spaces, the inbound attribute string could potentially be mapped to the
wrong id. However, this is not functionally different from mapping the
inbound string to
.BR nobody ,
yet provides greater flexibility.
.RE
.SH SEE ALSO
.sp
.LP
.BR lockd (1M),
.BR mount_nfs (1M),
.BR nfsd (1M),
.BR nfsmapid (1M)
.sp
.LP
.I System Administration Guide: Network Services
