'\" te
.\" Copyright (C) 2003, Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright (c) 2012-2013, J. Schilling
.\" Copyright (c) 2013, Andreas Roehler
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.opensource.org/licenses/cddl1.txt
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH slp.conf 4 "18 Feb 2003" "SunOS 5.11" "File Formats"
.SH NAME
slp.conf \- configuration file for Service Location Protocol agents
.SH SYNOPSIS
.LP
.nf
\fB/etc/inet/slp.conf\fR
.fi

.SH DESCRIPTION
.sp
.LP
\fBslp.conf\fR  provides all  Service Location Protocol ("\fBSLP\fR") agents
with their  operational  configuration. \fBslpd\fR(1M) reads \fBslp.conf\fR on
startup. Service Agents ("\fBSA\fRs") and User Agents ("\fBUA\fRs") read
.B slp.conf
on invocation of the
.B SA
and
.B UA
library routines;
configuration parameters are then cached on a per-process basis. All \fBSA\fR's
must use the same set of properties as
.B slpd
on the local machine, since
.B slpd
acts as an
.B SA
server.
.sp
.LP
The configuration file format consists of a newline-delimited list of zero or
more property definitions. Each property definition corresponds to a particular
configurable
.BR SLP ,
network, or other parameter in one or more of the three
.B SLP
agents. The file format grammar is shown in
.I "RFC 2234"
as
follows:
.sp
.in +2
.nf
config-file   =  line-list
line-list     =  line / line line-list
line          =  property-line / comment-line
comment-line  =  ( "#" / ";" ) 1*allchar newline
property-line =  property newline
property      =  tag "=" value-list
tag           =  prop / prop "." tag
prop          =  1*tagchar
value-list    =  value / value "," value-list
value         =  int / bool /
                 "(" value-list ")" / string
int           =  1*DIGIT
bool          =  "true" / "false" / "TRUE" / "FALSE"
newline       =  CR / ( CRLF )
string        =  1*stringchar
tagchar       =  DIGIT / ALPHA / tother / escape
tother        =  %x21-%x2d / %x2f /
                 %x3a / %x3c-%x40 /
                 %x5b-%x60 / %7b-%7e
                 ; i.e., all characters except `.',
                 ; and `='.
stringchar    =  DIGIT / ALPHA / sother / escape
sother        =  %x21-%x29 / %x2a-%x2b /
                 %x2d-%x2f / %x3a-%x40 /
                 %x5b-%x60 / %7b-%7e
                 ; i.e., all characters except `,'
allchar       =  DIGIT / ALPHA / HTAB / SP
escape        =  "\" HEXDIG HEXDIG
                 ; Used for reserved characters
.fi
.in -2

.sp
.LP
The properties fall into one of the following categories:
.RS +4
.TP
.ie t \(bu
.el o
.B DA
Configuration
.RE
.RS +4
.TP
.ie t \(bu
.el o
Static Scope Configuration
.RE
.RS +4
.TP
.ie t \(bu
.el o
Tracing and Logging
.RE
.RS +4
.TP
.ie t \(bu
.el o
Serialized Proxy Registrations
.RE
.RS +4
.TP
.ie t \(bu
.el o
Networking Configuration Parameters
.RE
.RS +4
.TP
.ie t \(bu
.el o
.B UA
Configuration
.RE
.SS "DA Configuration"
.sp
.LP
The following are configuration properties and their parameters for
.BR DA s:
.sp
.ne 2
.mk
.na
.B net.slp.isDA
.ad
.RS 24n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Boolean
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B False
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
.B True
or
.BR False
.RE

A boolean that indicates whether
.BR slpd "(1M) is to act as  a"
.BR DA .
If
.BR False ,
.BR slpd (1M)
is not run as a
.BR DA .
.RE

.sp
.ne 2
.mk
.na
.B net.slp.DAHeartBeat
.ad
.RS 24n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Integer
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
10800 seconds (3 hours)
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
2000 - 259200000 seconds
.RE

A 32-bit integer  giving the  number of seconds for  the passive \fBDA\fR
advertisement heartbeat. The default value is  10800 seconds. This property is
ignored if
.B net.slp.isDA
is
.BR False .
.RE

.sp
.ne 2
.mk
.na
.B net.slp.DAAttributes
.ad
.RS 24n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
List of Strings
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
Unassigned
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
List of Attribute Tag/Value List Pairs
.RE

A comma-separated list of parenthesized attribute tag/value list pairs that the
.B DA
must advertise in
.B DA
advertisements.  The property must be in the
.B SLP
attribute list wire format, which requires that you use a backslash
("\e") to escape reserved characters. See \fIRFC 2608\fR for more information on
reserved characters, or refer to the \fISystem Administration Guide: Network
Services\fR.
.RE

.SS "Static Scope Configuration"
.sp
.LP
The following properties and their parameters allow you to configure various
aspects of scope and
.B DA
handling:
.sp
.ne 2
.mk
.na
.B net.slp.useScopes
.ad
.RS 23n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
List of Strings
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.BR Default ,
for
.B SA
and
.BR DA ;
unassigned for
.BR UA .
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
List of Strings
.RE

A list of  strings indicating either the scopes that a
.B UA
or an
.BR SA
is allowed to use when making requests, or the scopes  a
.B DA
must support.
If not present for the
.B DA
and
.BR SA ,
the default scope
.B Default
is
used. If not present for the
.BR UA ,
then the user scoping model is in force,
in which active and passive
.B DA
or
.B SA
discovery are used for scope
discovery. The scope
.B Default
is used if no other information is available.
If a
.B DA
or
.B SA
gets another  scope in a request, a
.B SCOPE_NOT_SUPPORTED
error is  returned, unless the request was multicast,
in which case it is dropped. If a
.B DA
receives another scope in  a
registration, a
.B SCOPE_NOT_SUPPORTED
error will be returned.  Unlike other
properties, this property is "read-only", so  attempts to change it
programmatically after the configuration file has been  read are ignored.
.RE

.sp
.ne 2
.mk
.na
.B net.slp.DAAddresses
.ad
.RS 23n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
List of Strings
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
Unassigned
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
IPv4 addresses or host names
.RE

A  list of
.B IP
addresses  or
.BR DNS "-resolvable  names that denote the"
\fBDA\fRs to  use for statically  configured \fBUA\fRs and  \fBSA\fRs. The
property is read by \fBslpd\fR(1M), and registrations are forwarded to the
\fBDA\fRs. The \fBDA\fRs are provided to \fBUA\fRs upon request. Unlike other
properties, this property is "read-only", so attempts to change it after the
configuration file has been read are ignored.
.sp
The following grammar describes the property:
.sp
.in +2
.nf
addr-list  =  addr / addr "," addr-list
addr       =  fqdn / hostnumber
fqdn       =  ALPHA / ALPHA *[ anum / "-" ] anum
anum       =  ALPHA / DIGIT
hostnumber =  1*3DIGIT 3("." 1*3DIGIT)
.fi
.in -2

The following is an example using this grammar:
.sp
.in +2
.nf
sawah,mandi,sambal
.fi
.in -2

.B IP
addresses can be used instead of host names in networks where
.BR DNS
.RB "is not deployed, but network administrators are reminded that using" " IP"
addresses will complicate machine renumbering, since the
.B SLP
configuration
property files in statically configured networks will have to be changed.
.RE

.SS "Tracing and Logging"
.sp
.LP
These properties direct tracing and logging information to be sent to
.B syslogd
at the
.B LOG_INFO
priority. These properties affect
.BR slpd (1M)
only.
.sp
.ne 2
.mk
.na
.B net.slp.traceDATraffic
.ad
.RS 26n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Boolean
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B False
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
.B True
or
.BR False
.RE

Set \fBnet.slp.traceDATraffic\fR to \fBTrue\fR to enable logging of \fBDA\fR
traffic by
.BR slpd .
.RE

.sp
.ne 2
.mk
.na
.B net.slp.traceMsg
.ad
.RS 26n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Boolean
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B False
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
.B True
or
.BR False
.RE

Set
.B net.slp.traceMsg
to
.B True
to display details about
.BR SLP
messages. The  fields  in all  incoming  messages  and outgoing replies are
printed by
.BR slpd .
.RE

.sp
.ne 2
.mk
.na
.B net.slp.traceDrop
.ad
.RS 26n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Boolean
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B False
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
.B True
or
.BR False
.RE

Set this property to
.B True
to display details when an
.BR SLP "message is"
dropped by
.B slpd
for any reason.
.RE

.sp
.ne 2
.mk
.na
.B net.slp.traceReg
.ad
.RS 26n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Boolean
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B False
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
.B True
or
.BR False
.RE

Set this property to
.B True
to display the  table of service advertisements
when a registration or deregistration is processed by
.BR slpd .
.RE

.SS "Serialized Proxy Registrations"
.sp
.LP
The following properties  control  reading  and  writing serialized
registrations.
.sp
.ne 2
.mk
.na
.B net.slp.serializedRegURL
.ad
.RS 28n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
String
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
Unassigned
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
Valid
.BR URL
.RE

A  string containing  a
.B URL
pointing to a document, which contains
serialized registrations that should  be processed when the
.B slpd
starts up.

.RE

.SS "Networking Configuration Parameters"
.sp
.LP
The properties that follow allow you to set various network configuration
parameters:
.sp
.ne 2
.mk
.na
.B net.slp.isBroadcastOnly
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Boolean
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B False
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
.B True
or
.BR False
.RE

A  boolean that indicates if  broadcast  should  be  used instead of multicast.

.RE

.sp
.ne 2
.mk
.na
.B net.slp.multicastTTL
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Positive Integer
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B 255
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
A positive integer from 1 to 255.
.RE

A positive integer  less than or  equal to 255 that defines the multicast
.BR TTL .
.RE

.sp
.ne 2
.mk
.na
.B net.slp.DAActiveDiscoveryInterval
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Integer
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
900 seconds (15 minutes)
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
From 300 to 10800 seconds
.RE

A 16-bit positive integer giving the number of seconds between
.B DA
active
discovery queries. The default value is 900 seconds (15 minutes). If the property
is set to zero, active discovery is turned off. This is useful when the \fBDA\fRs
available are explicitly restricted to those obtained from the
.B net.slp.DAAddresses
property.
.RE

.sp
.ne 2
.mk
.na
.B net.slp.multicastMaximumWait
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Integer
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
15000 milliseconds (15 seconds)
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
 1000 to 60000 milliseconds
.RE

A 32-bit integer giving the maximum value for the sum of the
.B net.slp.multicastTimeouts
values and
.BR net.slp.DADiscoveryTimeouts
values in milliseconds.
.RE

.sp
.ne 2
.mk
.na
.B net.slp.multicastTimeouts
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
List of Integers
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B 3000,3000,3000,3000
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
List of Positive Integers
.RE

A list of 32-bit integers used as timeouts, in milliseconds, to implement the
multicast convergence algorithm. Each value specifies the time to wait before
sending the next request, or until nothing new has been learned from two
successive requests. In a fast network the aggressive values of
.B 1000,1250,1500,2000,4000
allow better performance. The sum of the list must
equal
.BR net.slp.multicastMaximumWait .
.RE

.sp
.ne 2
.mk
.na
.B net.slp.passiveDADetection
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Boolean
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B True
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
.B True
or
.BR False
.RE

A  boolean indicating whether
.B slpd
should perform passive
.BR DA
detection.
.RE

.sp
.ne 2
.mk
.na
.B net.slp.DADiscoveryTimeouts
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
List of Integers.
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B 2000,2000,2000,2000,3000,4000
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
List of Positive Integers
.RE

A list of 32-bit integers used as timeouts, in milliseconds, to implement the
multicast convergence algorithm during active
.B DA
discovery.  Each value
specifies the time to wait before sending the next request, or until nothing new
has been learned from two successive requests. The sum of the list must equal
.BR net.slp.multicastMaximumWait .
.RE

.sp
.ne 2
.mk
.na
.B net.slp.datagramTimeouts
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
List of Integers
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B 3000,3000,3000
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
List of Positive Integers
.RE

A list of 32-bit integers used as timeouts, in milliseconds, to implement
unicast datagram transmission to \fBDA\fRs.  The \fIn\fRth value gives the time
to block waiting for a reply on the
.IR n "th try to contact the"
.BR DA .
.RE

.sp
.ne 2
.mk
.na
.B net.slp.randomWaitBound
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Integer
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
1000 milliseconds (1 second)
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
1000 to 3000 milliseconds
.RE

Sets the upper bound for calculating the random wait time before attempting to
contact a
.BR DA .
.RE

.sp
.ne 2
.mk
.na
.B net.slp.MTU
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Integer
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
1400
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
128 to 8192
.RE

A 16-bit integer that specifies the network  packet size, in bytes. The packet
size includes
.B IP
and
.B TCP
or
.B UDP
headers.
.RE

.sp
.ne 2
.mk
.na
.B net.slp.interfaces
.ad
.sp .6
.RS 4n
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
List of Strings
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
Default interface
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
IPv4 addresses or host names
.RE

List of strings giving the
.B IP
addresses or host names of the network
interface cards on which the
.B DA
or
.B SA
should listen on port 427 for
multicast, unicast
.BR UDP ,
and
.B TCP
messages. The default value is
unassigned, indicating that the default network interface card should be used. An
example is:
.sp
.in +2
.nf
195.42.42.42,195.42.142.1,195.42.120.1
.fi
.in -2

The example machine has three interfaces on which the
.B DA
should listen.
Note that if
.B IP
addresses are used, the property must be renumbered if the
network is renumbered.
.RE

.SS "UA Configuration"
.sp
.LP
The following configuration parameters apply to the
.BR UA :
.sp
.ne 2
.mk
.na
.B net.slp.locale
.ad
.RS 22n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
String
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B en
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
See
.I "RFC 1766"
for a list of the locale language tag names.
.RE

A
.I "RFC 1766"
Language  Tag for  the language  locale. Setting this
property causes the property  value  to become the default  locale for
.BR SLP
messages.
.RE

.sp
.ne 2
.mk
.na
.B net.slp.maxResults
.ad
.RS 22n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
Integer
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
.B -1
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
.BR -1 ,
positive integer
.RE

A 32 bit-integer that specifies the maximum number of results to accumulate and
return for a synchronous request before the timeout, or the maximum number of
results to return through a callback if the request results are reported
asynchronously. Positive integers and
.B -1
are legal values.  If the value of
.B net.slp.maxResults
is
.BR -1 ,
all results should be returned.
.RE

.sp
.ne 2
.mk
.na
.B net.slp.typeHint
.ad
.RS 22n
.rt
.sp
.ne 2
.mk
.na
.B Setting Type
.ad
.RS 19n
.rt
List of Strings
.RE

.sp
.ne 2
.mk
.na
.B Default Value
.ad
.RS 19n
.rt
Unassigned
.RE

.sp
.ne 2
.mk
.na
.B Range of Values
.ad
.RS 19n
.rt
Service type names
.RE

A list of service type names.  In the absence of any \fBDA\fRs, \fBUA\fRs
perform
.B SA
discovery to find scopes.  If the \fBnet.slp.typeHint\fR
property is set, only \fBSA\fR's advertising types on the list respond. Note that
\fBUA\fRs set this property programmatically. It is not typically set in the
configuration file. The default is unassigned, meaning do not restrict the
type.
.RE

.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i)
lw(2.75i) |lw(2.75i)
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWslpr
_
CSIEnabled
_
Interface Stability		Standard
.TE

.SH SEE ALSO
.sp
.LP
.BR slpd (1M),
.BR slpd.reg (4),
.BR slp_api (3SLP),
.BR slp (7P)
.sp
.LP
.I System Administration Guide: Network Services
.sp
.LP
Alvestrand, H.\fIRFC 1766: Tags for the Identification of Languages\fR. Network
Working Group. March 1995.
.sp
.LP
Crocker, D., Overell, P.\fIRFC 2234, Augmented BNF for Syntax Specifications:
ABNF\fR. The Internet Society. 1997.
.sp
.LP
Kempf, J. and Guttman, E.
.IR "RFC 2614, An API for Service Location" .
The
Internet Society. June 1999.
