'\" te
.\" Copyright 1989 AT&T  Copyright (c) 1997, Sun Microsystems, Inc.  All Rights Reserved
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.TH ttydefs 4 "27 Jan 1994" "SunOS 5.11" "File Formats"
.SH NAME
ttydefs \- file contains terminal line settings information for ttymon
.SH DESCRIPTION
.sp
.LP
\fB/etc/ttydefs\fR is an administrative file that contains records divided
into fields by colons (":").   This information used by \fBttymon\fR to set
up the speed and terminal settings for a TTY port.
.sp
.LP
The \fBttydefs\fR file contains the following fields:
.sp
.ne 2
.mk
.na
.I ttylabel
.ad
.RS 17n
.rt
The string
.B ttymon
.RI "tries to match against the TTY port's" " ttylabel"
field in the port monitor administrative file. It often describes the speed
at which the terminal is supposed to run, for example,
.BR 1200 .
.RE

.sp
.ne 2
.mk
.na
\fIinitial-flags\fR
.ad
.RS 17n
.rt
Contains the initial
.BR termio "(7I) settings to which the terminal is to"
be set. For example, the system administrator will be able to specify what
the default erase and kill characters will be. \fIinitial-flags\fR must be
specified in the syntax recognized by the
.B stty
command.
.RE

.sp
.ne 2
.mk
.na
\fIfinal-flags\fR
.ad
.RS 17n
.rt
\fIfinal-flags\fR must be specified in the same format as
\fIinitial-flags\fR. \fBttymon\fR sets these final settings after a
connection request has been made and immediately prior to invoking a port's
service.
.RE

.sp
.ne 2
.mk
.na
.I autobaud
.ad
.RS 17n
.rt
If the autobaud field contains the character 'A,' autobaud will  be enabled.
Otherwise, autobaud will be disabled.
.B ttymon
determines what line speed
to set the TTY port to by analyzing the carriage returns entered. If autobaud
has been disabled, the hunt sequence is used for baud rate determination.
.RE

.sp
.ne 2
.mk
.na
.I nextlabel
.ad
.RS 17n
.rt
If the user indicates that the current terminal setting is not appropriate
by sending a BREAK,
.B ttymon
searchs for a \fBttydefs\fR entry whose
\fIttylabel\fR field matches  the \fInextlabel\fR field. If a match is found,
\fBttymon\fR uses that field as its \fIttylabel\fR field. A series of speeds
is often linked together in this way into a closed set called a hunt
sequence. For example,
.B 4800
may be linked to
.BR 1200 ,
which in turn
is linked to
.BR 2400 ,
which is finally linked to
.BR 4800 .
.RE

.SH SEE ALSO
.sp
.LP
.BR sttydefs (1M),
.BR ttymon (1M),
.BR termio (7I)
.sp
.LP
.I System Administration Guide: Basic Administration
