#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.opensource.org/licenses/cddl1.txt
#

#
# Copyright 2012 Jörg Schilling.  All rights reserved.
#

#
# Definitions common to section subdirectories for manual pages.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.

MANSECT=	3slp

MANFILES=				\
	slp_api.3slp			\
	slp_strerror.3slp		\
	SLPClose.3slp			\
	SLPDelAttrs.3slp		\
	SLPDereg.3slp			\
	SLPEscape.3slp			\
	SLPFindAttrs.3slp		\
	SLPFindScopes.3slp		\
	SLPFindSrvs.3slp		\
	SLPFindSrvTypes.3slp		\
	SLPFree.3slp			\
	SLPGetProperty.3slp		\
	SLPGetRefreshInterval.3slp	\
	SLPOpen.3slp			\
	SLPParseSrvURL.3slp		\
	SLPReg.3slp			\
	SLPSetProperty.3slp		\
	SLPUnescape.3slp

MANSO=					\

include ../Makefile.man

install: $(ROOTMANFILES)
